### ISSUE TITLE
Black list certain characters on Registration

### ISSUE THREAD

**Issue by adelikat** [TASVideos/tasvideos#1010]
The old site allowed whatever.  New site only allows characters that were actually used.  Because if you restrict characters for registration, it blocks them on log in too (due to the identity framework).

What we need is to keep a list of characters, outside of the built-in stuff, that we check and block new registrations for.  This would be all special characters other than . and @, and (controversial opinion alert) NO SPACES allowed.

**Comment by meshuggahtas** [comment]
Writing a TODO for myself: contact adelikat about potential problems

**Comment by adelikat** [comment]
Closing, spaces are no longer allowed, and I've accomplished what I wanted to for this ticket
