### ISSUE TITLE
Debugger detected an issue in pager engine

### ISSUE THREAD

**Issue by ThunderAxe31** [TASVideos/tasvideos#1011]
Repro:
1. Open a forum thread that has at least 6 pages
2. Open the browser debugger (I used Opera, latest version)
3. Click on the ![image](https://user-images.githubusercontent.com/36802254/149985881-abd2f5ec-490e-4496-b501-bbf859a071b9.png) button in the middle of the pager, which opens the dropdown
4. An issue will appear in the browser debugger, see below for more details:

```
Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform

A page or script is accessing at least one of navigator.userAgent, navigator.appVersion, and navigator.platform. Starting in Chrome 101, the amount of information available in the User Agent string will be reduced.
To fix this issue, replace the usage of navigator.userAgent, navigator.appVersion, and navigator.platform with feature detection, progressive enhancement, or migrate to navigator.userAgentData.
Note that for performance reasons, only the first access to one of the properties is shown.
```

Affected resource: https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js
Chromium explanation: https://blog.chromium.org/2021/09/user-agent-reduction-origin-trial-and-dates.html

![image](https://user-images.githubusercontent.com/36802254/149984356-89086efb-6e19-42fb-a667-5520f40fbe8a.png)

**Comment by TiKevin83** [comment]
This just means we'll have to keep bootstrap updated in case this affects their library before Chrome 101

**Comment by TiKevin83** [comment]
it's a closed issue in their repo, closing here with note
https://github.com/twbs/bootstrap/issues/34599
