### ISSUE TITLE
For submission encodes let users put in regular youtube links instead of forcing embed links

### ISSUE THREAD

**Issue by Masterjun3** [TASVideos/tasvideos#1012]
Parsing the id of youtube links with regex is one of the internet's favorite discussion topics. We shouldn't make users force embed links when most don't even know what those look like.

**Comment by SamsaraTAS** [comment]
Whatever the current implementation is doing seems to be a bit busted: 
![embed](https://user-images.githubusercontent.com/14018768/154347384-917069c7-90d4-46be-b44d-53145e3cbbdf.png)

The videos will still embed on the submission page, but "Link to Video" leads to that increasingly broken link.

I feel like the easiest way of doing this would be to have that field just ask for the video ID, like the Youtube wiki module.

**Comment by Masterjun3** [comment]
Regular YouTube links work now.
