### ISSUE TITLE
Genesis movie gives different timing between submission and userfile

### ISSUE THREAD

**Issue by ThunderAxe31** [TASVideos/tasvideos#1013]
Yes, it's the very same movie file.

https://tasvideos.org/7283S
![image](https://user-images.githubusercontent.com/36802254/149988504-a0b4bc4c-255e-489a-a794-b52e2f325a47.png)

https://tasvideos.org/userfiles/info/637781221746390722
![image](https://user-images.githubusercontent.com/36802254/149988524-1dce5151-a8be-4f72-b49f-9d7e064d779c.png)

**Comment by meshuggahtas** [comment]
Hmm... I'm getting different numbers....
https://tasvideos.org/7283S - **04:54.51**
The submission timing using wiki - [module:frames|amount=17645|fps=59.922751013550524]  - **04:54.56**
https://tasvideos.org/userfiles/info/637781221746390722 - **04:55.00**

On the other hand, another recent Genesis submission is ok
https://tasvideos.org/7290S - **09:32.65**
[module:frames|amount=34315|fps=59.922751013550524] - **09:32.65 same**

While another Genesis submission also has difference
https://tasvideos.org/7296S - **1:47:01.42**
[module:frames|amount=384789|fps=59.922751013550524]  - **1:47:01.41**

Going to edit this issue after I upload them as userfiles temporarily for investigating this issue

**Comment by SandTAS** [comment]
As for UserFiles, to me it looks like the difference is explained by the time being rounded to the nearest whole second. See how the UserFile time always ends in .00.

||submission|UserFile|
|---|---:|---:|
|7283S|04:54.51|04:55.00|
|7290S|09:32.65|09:33.00|
|7296S|1:47:01.42|1:47:01.00|

It's not only Genesis movies; I noticed the same thing with UserFiles in #1061 for a DOS game.
