### ISSUE TITLE
Make icon and description in top-left (watermark?) clickable

### ISSUE THREAD

**Issue by Andre601** [TASVideos/tasvideos#1019]
It feels a bit odd that only `TASVideos` is actually clickable and the image and small description aren't. This should be changed to make it easier to navigate to the main site.

![image](https://user-images.githubusercontent.com/11576465/150116860-9ad73dd6-3135-484f-9d66-bf7d1db7e343.png)

Also, perhaps the different sections (Home, Movies, Forum, etc) could be a bit larger? The text feels kinda small, especially on larger screens which are fairly common in this day and age of the internet.
The width of the page isn't really used that well and could be improved.

![image](https://user-images.githubusercontent.com/11576465/150116985-84c8ef6b-0b25-4857-aabd-f901b1b06def.png)

**Comment by meshuggahtas** [comment]
Clicking whole banner (logo+megamans+headline+description): probably OK

Fonts: I think the fonts are big enough. You can change your font size in your browser. I didn't tested but I guess you can also increase DPI or changing system font size. And there are a lot of extensions and other 3rd party softwares to be choose from. If you need help, just comment in this issue and I will help you once you tell me what platform and browser you use.

Wikipedia for comparison
![wiki](https://user-images.githubusercontent.com/31288337/150120502-242d81fc-3709-4e4d-8fee-a8fa3ce826a3.PNG)

**Comment by Andre601** [comment]
> Fonts: I think the fonts are big enough. You can change your font size in your browser. I didn't tested but I guess you can also increase DPI or changing system font size. And there are a lot of extensions and other 3rd party softwares to be choose from. If you need help, just comment in this issue and I will help you once you tell me what platform and browser you use.

I see it differently here.
Changing font size in browser would be a global thing that could negatively affect other sites too, so that one would be out of the question.
Same goes for the System font size.
Not a fan of installing yet another extension to fix/change something. I already have enough of those and I usually stick with the ones that apply to more than one site.

Also, the Wikipedia comparison you make is imo not justified.
The text, while somewhat similar in size, does have a bit of a different highlighting. On Tasvideos is it just text while here the text is separated into visible tabs, which makes it more visible for me.
Additionally does it not feel that empty on their page. Not sure why. Maybe because their logo is a bit larger or because the tabs with the main (important) text isn't that far up.
On Tasvideos does it feel a little bit empty. You have this relatively large gap on the right with nothing to fill it out. Perhaps give the text a bit more padding on the left and right to not have it that much squished together?

**Comment by meshuggahtas** [comment]
My mom uses CTRL+ (Zooming in) as in increasing everything. She uses Chrome and Firefox and they perfectly worked for nearly every websites except those Instagram and Facebook pages where there is an image viewing feature, which never supports these zoomings.

The majority of browsers (Safari, Chrome, Firefox, Edge) have settings for page dependent settings.

The comparison I added for future contributors looking at this issue.

The last time this was discussed (user request to change design for everyone else) we concluded to not change it. Last time discussion with 3 working workaround: https://github.com/TASVideos/tasvideos/issues/691#issuecomment-1003350790 

If you need a different workaround, please input your browser and platform so I can help you what you need to change for this particular page so every other visitor don't need to change their own settings.
