### ISSUE TITLE
Hide poll results until you voted or wish to see the results

### ISSUE THREAD

**Issue by Masterjun3** [TASVideos/tasvideos#1022]
For ideal conditions we probably want to hide forum poll results until the user either asks for them, they already voted, or they can't vote in the first place.
This is how it worked on the old site, and we probably want to restore this functionality, since the current system gives the voter no choice but to see the results, possibly affecting voting behavior. ([citation needed], but it sounds like proper logic :D)

**Comment by meshuggahtas** [comment]
List of places with votes:
- Awards
- Submissions

List of places with ratings:
- Publications

I wanted to write my suggestions about hiding and showing, but I need to rethink them first. 

I would like to propose (probably in another issue) a feature request of letting users hide these values to let them make their unbiased opinion.

Similar function on different websites:
- E-sport websites: A simple toggle on their front page that hides the result of every match, to let them view the matches without knowing the end result --> I can see doing this for rating movies. The idea is that the ratings should be always shown for everyone except if you would like to start rating movie without being biased by knowing the current value(s) of a TAS
- Forums **(Masterjun's original issue)**: As we had on the old site, "vote if you want to see the results" is a widely accepted way to encourage users to vote while also getting their opinion. Obviously some of the staff members might be allowed to see poll results (supported currently)
- Awards: Depending on communities, the current vote distributions are usually shown, but both of showing or hiding partial and full results have their own benefits and risks. Benefits such as ability to see how the rest of the community see a particular product, risks such as brigading or last minute votings.

Please say if I should make this kind of feature request in a different issue.
