### ISSUE TITLE
Some Broken Links are not broken

### ISSUE THREAD

**Issue by meshuggahtas** [TASVideos/tasvideos#1026]
https://tasvideos.org/WikiOrphans
- https://tasvideos.org/Morimoto - the page doesn't exits but a reroute to HomePage works, shouldn't be listed in there
- https://tasvideos.org/Search?SearchTerms=megaman - the page exists and works, shouldn't be listed in there
- https://tasvideos.org/Activity/Judges/Masterjun - the page exists and works, shouldn't be listed in there
- https://tasvideos.org/SubmitMovie - the page exists and works, shouldn't be listed in there

[module:BrokenLinks]

**Comment by adelikat** [comment]
The morimoto is an example of one that is still a broken link, as it should not be used.  The redirect is a hack workaround for these kinds of issues

**Comment by adelikat** [comment]
2 things we seem to need to build here
1) filter out query strings before deciding a link is valid
2) create a static list of developed pages through reflection (we already have this for https://tasvideos.org/Wiki/SiteMap) and use that to filter.  We need to make sure it is a "starts with" logic to filter out parameters as url such as Activity/Judges/Masterjun

**Comment by nattthebear** [comment]
> We need to make sure it is a "starts with" logic to filter out parameters as url such as Activity/Judges/Masterjun

Is there some more precise routing data available, rather than assuming that pages will always have subpath parameters?

**Comment by meshuggahtas** [comment]
One of the following terms should list all the routes, I'm unsure which one is it as I'm new to Blazor, so I rather list more relevant stuffs:
- https://github.com/TASVideos/tasvideos/search?q=asp-route-path
- https://github.com/TASVideos/tasvideos/search?q=asp-page
- https://github.com/TASVideos/tasvideos/search?q=asp-route-query
- [Route("  for example [Route("api/v1/[controller]")]
