### ISSUE TITLE
Rom hashes can't be reused and SGB platform redundancy

### ISSUE THREAD

**Issue by coolkirby2000** [TASVideos/tasvideos#1030]
TASVideos' [Rom list](https://tasvideos.org/Games/1473/Roms/List) feature is ​useful for authors of submissions to ensure they're using a verified good ROM. These lists will become more important in the future [when they're reflected on publication pages](https://github.com/TASVideos/tasvideos/issues/906#issuecomment-1008992699).

This may be by design, but the site prohibits adding a second ROM with the same MD5 or SHA1 hash, either to the same Game or a different one.

This is only an issue with GB and SGB Game entries for the same game which use the same ROM, like [GB Donkey Kong](https://tasvideos.org/2241G) and its [SGB copy](https://tasvideos.org/1026G). [Here is a full list](https://tasvideos.org/Forum/Topics/22854) of these pairs of Games. As console verification (via GBP/GBI) requires that GB games be played in GBA mode and parsed as GB, the GB version of a game is preferred for submission. So hashes for its Roms will likely be filled first.

I see three options going forward:
1. Change nothing. SGB submissions of Donkey Kong, etc. will not be able to choose a Rom if the GB game already uses it. On the other hand, all Rom lists will be safe from typos allowing a hash to be accidentally added twice.
2. Allow hashes to be reused. This will allow GB and SGB entries to use the same Rom, but is a workaround that's only useful for this one platform redundancy and removes the protection against typos.
3. Merge SGB Game entries/movies into the GB entries. This will let a GB game in any form use the one entry for each Rom hash, and avoid a blank Rom field, which would cause issues for submissions and publications. It also standardizes the nomenclature for these games, as GB, GB-in-GBA and GB-in-SGB are all just the GB ROM anyway. If we do this, we would probably need to relabel all SGB games as GB to be consistent, removing this redundant platform from the site.

What are everyone's thoughts on this issue?

**Comment by adelikat** [comment]
The unique constraint on GameVersion (formerly known as Rom) is gone so I'm closing this ticket.  As for how to handle this situation, it is a matter of staff decisions, but whatever needs to be done can be now
