### ISSUE TITLE
Crazy Microsoft.AspNetCore.Mvc.Rendering.SelectListItem in the URL

### ISSUE THREAD

**Issue by Masterjun3** [TASVideos/tasvideos#1038]
Go to https://tasvideos.org/Subs-List and click on one of the table column headers to sort.
The resulting URL will look similar to this:
`https://tasvideos.org/Submissions/Index?Sort=System&Years=&AvailableYears=Microsoft.AspNetCore.Mvc.Rendering.SelectListItem|Microsoft.AspNetCore.Mvc.Rendering.SelectListItem|Microsoft.AspNetCore.Mvc.Rendering.SelectListItem|Microsoft.AspNetCore.Mvc.Rendering.SelectListItem|Microsoft.AspNetCore.Mvc.Rendering.SelectListItem|Microsoft.AspNetCore.Mvc.Rendering.SelectListItem|Microsoft.AspNetCore.Mvc.Rendering.SelectListItem|Microsoft.AspNetCore.Mvc.Rendering.SelectListItem|Microsoft.AspNetCore.Mvc.Rendering.SelectListItem|Microsoft.AspNetCore.Mvc.Rendering.SelectListItem|Microsoft.AspNetCore.Mvc.Rendering.SelectListItem|Microsoft.AspNetCore.Mvc.Rendering.SelectListItem|Microsoft.AspNetCore.Mvc.Rendering.SelectListItem|Microsoft.AspNetCore.Mvc.Rendering.SelectListItem|Microsoft.AspNetCore.Mvc.Rendering.SelectListItem|Microsoft.AspNetCore.Mvc.Rendering.SelectListItem|Microsoft.AspNetCore.Mvc.Rendering.SelectListItem|Microsoft.AspNetCore.Mvc.Rendering.SelectListItem|Microsoft.AspNetCore.Mvc.Rendering.SelectListItem|Microsoft.AspNetCore.Mvc.Rendering.SelectListItem|Microsoft.AspNetCore.Mvc.Rendering.SelectListItem|Microsoft.AspNetCore.Mvc.Rendering.SelectListItem|Microsoft.AspNetCore.Mvc.Rendering.SelectListItem&System=&User=&GameId=&StatusFilter=New|JudgingUnderWay|Accepted|PublicationUnderway|NeedsMoreInfo|Delayed&Default=New|JudgingUnderWay|Accepted|PublicationUnderway|NeedsMoreInfo|Delayed&All=New|Delayed|NeedsMoreInfo|JudgingUnderWay|Accepted|PublicationUnderway|Published|Rejected|Cancelled&PageSize=100&CurrentPage=1`

**Comment by nattthebear** [comment]
The page appears to be fully functional, so what's the ask here?  Are you concerned that this particular page is hurting the overall perf of the website?  Is it important to be able to hotlink to individual sorts?  Do you just not like URLs?

**Comment by TiKevin83** [comment]
could we reimplement it as a range element? It would mean you couldn't select "2013 and 2015 but not 2014" but would be a lot easier to use and probably a cleaner URL

**Comment by meshuggahtas** [comment]
Well, my observations:
- Google Chrome maximum URL length is 2048 bytes
- Unsure which code we are talking about as github has limitations on searching stuffs
- This very long URL should be shortened for clarity reasons like the ability to understand what link will the visitor go after clicking a column header in a table to order in this scenario. Probably it won't fit in a mobile viewers screen, but they might want to share the page link with their friends. Others might rightfully think it as malicious code for having some famous keywords.

**Comment by Masterjun3** [comment]
This issue now throws a System Error.

**Comment by adelikat** [comment]
Yeah, that link throws an exception but it doesn't seem to generate it anymore.  Click 2022 in the dropdown and you get:
https://tasvideos.org/Subs-List?Search.StatusFilter=0&Search.StatusFilter=3&Search.StatusFilter=4&Search.StatusFilter=5&Search.StatusFilter=2&Search.StatusFilter=1&Search.Years=2022&Search.User=&Search.System=

Not pretty but none of the SelectListItem nonsense

**Comment by TiKevin83** [comment]
@adelikat if you click any of the filter headers an exceltion is still thrown

**Comment by Masterjun3** [comment]
This issue isn't about the dropdowns but the table headers.

**Comment by MiYanni** [comment]
I was about to submit this issue myself. You're `ToString`ing the class itself. It has no `ToString` overload to be used as a query parameter:
![image](https://user-images.githubusercontent.com/17788297/152300736-686e1b0f-33ed-4271-8290-3496b990a510.png)

So, you need a way to render `Microsoft.AspNetCore.Mvc.Rendering.SelectListItem` as a query parameter. I'm assuming they should be a list of years, separated by vertical bars. If I was to happen a guess, you want to render the [Value](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.rendering.selectlistitem.value?view=aspnetcore-6.0) property and not the class itself.

**Comment by TiKevin83** [comment]
Thanks, I was able to pinpoint where that was happening and get a test branch started
https://github.com/TASVideos/tasvideos/tree/bugfix/1038

Something's still broken with those links themselves on that page post our .net 6 upgrade which is preventing me from validating whether that's fully fixed the issue.
