### ISSUE TITLE
Highlight unread forums, threads, and posts

### ISSUE THREAD

**Issue by Espyo** [TASVideos/tasvideos#1039]
Currently, the only way to check any unread posts is via the "Posts since last visit" button on the top-right.
However in the old layout, it was possible to just see at a glance what forums and threads had unread posts, as well as what posts were unread. Even clicking on a thread took you to the first unread post.
That method was much more practical, since users could instantly skip forums or threads about subjects, consoles, or games they have no interest in.
From what I can tell, there is no such feature with the new layout.

**Comment by Masterjun3** [comment]
Duplicate #799.
