### ISSUE TITLE
Stop double-compressing movie files

### ISSUE THREAD

**Issue by YoshiRulz** [TASVideos/tasvideos#1045]

**Comment by meshuggahtas** [comment]
I assume this is about TAS movies uploaded as userfiles and submissions being in a zip formatted movie format, which is probably only supported and allowed to use emulator is BizHawk. Unsure about lsmv for lsnes.

**Comment by adelikat** [comment]
Closing this as a duplicate of https://github.com/TASVideos/tasvideos/issues/1187

I agree we should allow uploading a movie file without it being zipped but it was really difficult to implement while backwards supporting legacy data.  It's more feasible now that we don't have a legacy site to worry about but it still requires rethinking the most complicated pages on the site.
