### ISSUE TITLE
Syncing unlisted YouTube videos on TVC to be public disables embedding

### ISSUE THREAD

**Issue by despoa** [TASVideos/tasvideos#1046]
When a video is first uploaded to YouTube, there's an option on whether or not to allow the video to be embedded on other websites. By default, it is on and can be left on without checking. The problem is that when synchronizing initially unlisted videos on TVC with the publications on the website in order to make them go public, it disables the embedding option on them.

If I have to guess what's causing it, the feature for unlisting videos that disables embedding for those videos is also used for the feature that makes videos go from unlisted to public.

**Comment by Masterjun3** [comment]
Looks like this happens via this note in the [Youtube API](https://developers.google.com/youtube/v3/docs/videos/update):
> Note that this method will override the existing values for all of the mutable properties that are contained in any parts that the parameter value specifies. For example, a video's privacy setting is contained in the `status` part. As such, if your request is updating a private video, and the request's part parameter value includes the `status` part, the video's privacy setting will be updated to whatever value the request body specifies. If the request body does not specify a value, the existing privacy setting will be removed and the video will revert to the default privacy setting.

In other words, the current code changes `status.privacyStatus` and doesn't provide values for the others, so youtube also resets `license`, `publicStatsViewable`, `publishAt`, `selfDeclaredMadeForKids`, and most importantly here `embeddable` to the default setting.
