### ISSUE TITLE
Prevent 400 http error from erasing your post

### ISSUE THREAD

**Issue by ThunderAxe31** [TASVideos/tasvideos#1049]
![image](https://cdn.discordapp.com/attachments/280810924523388928/928563949555830784/unknown.png)
![image](https://user-images.githubusercontent.com/36802254/150951417-dc771486-102c-4ff7-980b-28c1eb2a509c.png)

This seems to be much likely when you take a lot of time while writing your post, ironically. It also happened to me when giving a judgement to a submission. When it happens, you can't recover in any way the text that you've written, because hitting on Back button in your browser brings you to the thread page, instead than the post writing page.

Here are two possible solutions:
1. Prevent this error from happening at all. It never happened to me on old site, and while other kind of errors did happen, they never prevented me from recovering my written text by hitting Back button in the browser.
2. Load an intermediate page before trying to submit the post text to the server. This way there will always be the possibility of going back to the posting page, regardless of the nature of the error. Note that on old site, there used to be an intermediate page for making a post, however it was only used for noting that the post was successfully submitted, as the actual data was send from the post-writing page.

In my opinion, the above ideas would be much better than introducing an unnecessary resource-consuming and hacky solution like [backing up typed text remotely](https://github.com/TASVideos/tasvideos/issues/212).

**Comment by Masterjun3** [comment]
Solution 2 doesn't work because of the antiforgery token system telling your browser to never cache the site, so even if you would be able to go back to the page, the text would be gone. You can test this by entering text and going back and forward using the browser keys.

**Comment by ThunderAxe31** [comment]
I tried doing as you said, and I actually got the inputted text again.

**Comment by Masterjun3** [comment]
Oh, then maybe your browser doesn't honor the no-cache field in the header. Maybe that's the reason why you're getting a 400 error. Although it might just be cookie timeout.

**Comment by ThunderAxe31** [comment]
I just performed a test to see if changing IP before hitting the confirmation button causes 404. It doesn't.

**Comment by meshuggahtas** [comment]
Original reporter (judging by the screenshot) used Opera browser on PC Windows.

Tried the followings:
- Changing IP between writing post and sending, no problem
- Create topic, wait 34 minutes, save, no problem

**Comment by meshuggahtas** [comment]
I've just randomly got the 400 error. 
- Windows 10 x64 + Chrome
- Time and date 04.01.2002 20:40 ~ 20:50
- Char count was around 1000
- 2 tabs of tasvideos were open, the post I was about to edit https://tasvideos.org/Forum/Topics/23150?CurrentPage=1&Highlight=513283#513283 and searching for a specific game https://tasvideos.org/Search?SearchTerms=western+reaction
- After submitting edit of the post, I've got error 400. Pressing back showed me the posts in that thread.

**Comment by meshuggahtas** [comment]
Got this error while creating the page https://tasvideos.org/Wiki/Edit?path=HomePages%2FMESHUGGAH%2FWorldRecords
- Windows 10 x64 + Chrome
- Time and date 04.29.2022 09:12 GMT+1
- Char count was around 500
- While creating this Wiki page, I also opened https://tasvideos.org/MovieStatistics for copy pasting a text
- I had viruses on my computer BEFORE this happened. For the future, I will resort using Firefox to see if it also happens on that browser.
- When this bug happens, the 400 error comes nearly instant. Never timed it but I would say less than a half second. Usually when saving a post, it takes time and you can see there is a visible delay.

**Comment by meshuggahtas** [comment]
- Windows 10 x64 + Firefox
- Time and date 03.05.2022 12:08 GMT+1
- Char count ~130
- Opened another tasvideos tab when this happened.

I personally think the bug doesn't depends on user settings or browsers. Now I just will need to test it sometime the following scenario:
1. Attempt to create a post (PM, Wiki page, Forum post)
2. Open 1 tab of a tasvideos page (should be anything)
3. Attempt to save a post

**Comment by vadosnaprimer** [comment]
I only got the blank page upon sending after I've been editing for some hours while switching tabs a lot.

**Comment by meshuggahtas** [comment]
There might be a time condition, I didn't clock them. I will wait for a test server to test this to avoid any unnecessary performance usage on live server.
