### ISSUE TITLE
Search case sensitivity bug

### ISSUE THREAD

**Issue by meshuggahtas** [TASVideos/tasvideos#1053]
- **megaman** and **Megaman** won't give the exact same results. It will be definitely in different orders, and I think they don't result in the same amount of hits

Example:
https://tasvideos.org/Search?SearchTerms=megaman - Wiki and post results
https://tasvideos.org/Search?SearchTerms=Megaman - Wiki and post results in different order

**Comment by adelikat** [comment]
I'm not seeing a difference.  At least not in the example provided, same results, same order.  I'm going to guess this is no longer an issue.
