### ISSUE TITLE
Search partial match bug

### ISSUE THREAD

**Issue by meshuggahtas** [TASVideos/tasvideos#1054]
- There is definitely a bug in what strings get's evaulated as matching. Sometimes it matches a game's name, sometimes it matches a part of a game's name and sometimes it won't show it.

Example:
https://tasvideos.org/Search?SearchTerms=banned shows GBC - Pokémon: Platinum Edition because the name is Kou Dai Yao Guai - Bai Jin **Ban** (ned) edit: the first 3 letters **BAN** of the search term **BANNED** got matches
https://tasvideos.org/Search?SearchTerms=jin+ba shows nothing, 0 results albeit has all the parts except missing 1 letter
https://tasvideos.org/Search?SearchTerms=jin+ban shows many results

**Comment by TiKevin83** [comment]
The "jin ba" one I do find weird, but generally I don't think these are bugs. The search is a lot more powerful working like this, if you want it to match more literally you can search with quotes as in `"jin ban"` and if you want it to make inferences based around English verb tenses like different tenses of the word ban you can get all that power with the default.

**Comment by nattthebear** [comment]
There's no bug here.  We're using a reasonable fuzzy search text engine and it's returning reasonable results.
