### ISSUE TITLE
Percentages in poll results are incorrectly decimal rounded

### ISSUE THREAD

**Issue by ThunderAxe31** [TASVideos/tasvideos#1056]
Example: https://tasvideos.org/Forum/Topics/22982 `13+86=99`
![image](https://user-images.githubusercontent.com/36802254/151323501-1ff3a8d4-5d6f-49a5-a80c-204191b17152.png)
The problem is that that `86%` should be an `87%` instead, as it's actually `86.66666666...`

**Comment by meshuggahtas** [comment]
I personally vote for percentages up to 2nd decimal point rounded. So to Masterjun's example, it would be 28.57%, 28.57%, 42.86% summing up to 100%. I'm unsure about the math part, but I guess the loss of precision might go through 100 as well as be fewer.

**Comment by Masterjun3** [comment]
That just moves the problem. You can easily construct a situation where rounding to the second decimal gives the exact same problem. So that's not a solution to this problem.

**Comment by meshuggahtas** [comment]
The solution would be writing out the whole number which we probably want to avoid. And there is also a part of precision that becomes pointless for accounting the participation and votes for these polls where the maximum number would be probably around 100.

So I'm suggesting the enhancement of what I wrote above to improve this design.

**Comment by ThunderAxe31** [comment]
> By design. But I'm open to suggestions. What would be your solution to a vote result with 2, 2, and 3 people, giving percentages of 28.571...%, 28.571...%, and 42.857...%?

Thank you, that's a great example. Now I see there is no simple solution to this issue, and it's not worth to figure out complex solutions for something so trivial. I'm closing this.
