### ISSUE TITLE
Quick rate a publication inline

### ISSUE THREAD

**Issue by adelikat** [TASVideos/tasvideos#106]
We want the ability to quickly rate a movie without leaving the publication page itself.

**Comment by meshuggahtas** [comment]
Personal notes:
- Rating is now only entertainment
- Ratings currently have the "rule" **Do not rate a movie before watching it in full** which means the implementation should respect this. I don't have easy to integrate suggestion.
- Outdated ratings description on 2nd tab when rating <-- TODO add to my personal wiki todo list
