### ISSUE TITLE
Forum/Mood report PHP link

### ISSUE THREAD

**Issue by meshuggahtas** [TASVideos/tasvideos#1067]
1. https://tasvideos.org/Profile/Settings
2. Click on Check Mood Avatars
3. https://tasvideos.org/forum/moodreport.php?username=MESHUGGAH which shows adelikat's moods

I'm not sure what is the intent, but the link has .php and the username variable has no effect.

**Comment by adelikat** [comment]
The url having .php is an artifact of backwards compatibility.  If you set up a route, it's the url the RazorPages technology likes to generate.  It isn't great, but it is also harmless.

Obviously the intent is for you to see your own avatars, not mine
