### ISSUE TITLE
UI Moan: Light mode link color hard to see against background

### ISSUE THREAD

**Issue by scrimpeh** [TASVideos/tasvideos#1069]
See attached picture, the link color of thread title is not very visible. Very minor thing, it's better in Dark Mode.

Might be simplest to just remove the link here, since I don't think there's much purpose in clicking it.

![grafik](https://user-images.githubusercontent.com/10942815/151999431-74b7b2d3-e896-495a-9618-3232fcca52a2.png)

**Comment by vadosnaprimer** [comment]
Those links are valuable for navigation

![изображение](https://user-images.githubusercontent.com/7092625/152003659-15975bed-d4ec-48e8-a2d2-ee9335008a5a.png)

but yeah the color is too dark.

**Comment by scrimpeh** [comment]
Oh yeah, that is a much more important place where it crops up. Can't just remove the link then.

**Comment by nattthebear** [comment]
Oooof.  https://contrastchecker.com/?c=0d6efa&b=6a37a0

**Comment by TiKevin83** [comment]
This shouldn't be too hard to fix, it probably wasn't considered when links were added to the headings

**Comment by Masterjun3** [comment]
Wasn't really a priority for me considering the design of said titles needed to change anyway #1021.
