### ISSUE TITLE
Judges cannot edit submission when Publication Underway

### ISSUE THREAD

**Issue by CasualPokePlayer** [TASVideos/tasvideos#1073]
Judges don't have permission to change publication class once it goes to Publication Underway, resulting in the site throwing a `A submission can not be accepted without a PublicationClass` error upon any edits to a submission. Senior Judges/Admins are effectively needed to replace movie files at this stage. This is really only relevant when movie file has issues like cycle count missing/other misc header issues and the judge judging the movie forgot to fix the movie.

**Comment by adelikat** [comment]
Fixed by 592985919a96779b89a32e940ab7861456067b7e
