### ISSUE TITLE
Some pages give System Errors consistently

### ISSUE THREAD

**Issue by coolkirby2000** [TASVideos/tasvideos#1075]
Some site pages always lead to a System Error page, like [WikiOrphans](https://tasvideos.org/WikiOrphans) and [Pseudo-orphans](https://tasvideos.org/HomePages/sgrunt/PseudoOrphans). Could be a module on the page that was recently changed, it's only been happening for the past four days or so.

This happens whether I'm logged in or out, and on three different browsers (Android Firefox, Android Chrome, Amazon Silk).

**Comment by adelikat** [comment]
Each page is a different issue, this isn't one related issue.  But probably the 2 orphan pages are the same issue.

Submission thing is known and there is a PR to fix this already

**Comment by coolkirby2000** [comment]
Okay, I edited the OP to only contain the orphan pages issue.

**Comment by adelikat** [comment]
Yeah, the orphans query broke.  We did a major upgrade from .NET 5 to 6, seems there are some queries that no longer work and need to be rethought
