### ISSUE TITLE
Homepage embedded publication errors

### ISSUE THREAD

**Issue by coolkirby2000** [TASVideos/tasvideos#1076]
On Homepages like [mine](https://tasvideos.org/HomePages/CoolKirby) (see My Published TASes tab) and [EZGames'](https://tasvideos.org/HomePages/EZGames69) (see Published Movies tab), embedded publications:
1. Always show a rating of 0
2. Reload the current Homepage instead of linking to the movie when its title is clicked (you can see this on my page when hovering over [2500M](https://tasvideos.org/2500M), it erroneously links to https://tasvideos.org/HomePages/CoolKirby)
3. Redirect to Access denied page when Edit is clicked, as [Publications/Edit/](https://tasvideos.org/Publications/Edit/2500) is replaced with [Wiki/Edit?id=](https://tasvideos.org/Wiki/Edit?id=2500).

The rating, pub link, and Edit button all work on a publication's actual page.

**Comment by meshuggahtas** [comment]
4. Fastest Completion links to https://tasvideos.org/HomePages/FastestCompletion
5. Commentary links to https://tasvideos.org/HomePages/Commentaries

**Comment by meshuggahtas** [comment]
OK, only my bug mention remains: Movie Special Categories erroneously links to https://tasvideos.org/HomePages/
