### ISSUE TITLE
BBCode button's css styles are inconsistent

### ISSUE THREAD

**Issue by YoshiRulz** [TASVideos/tasvideos#1080]
![Screenshot_20220205_185404](https://user-images.githubusercontent.com/13409956/152635281-0356660a-c1e8-407d-98e2-4c58b5b32d07.png)
These 3 sets of buttons aren't just different colours, they have different hover and mousedown behaviours. edit: as in `:hover`/`:active` in CSS, JS events aren't used for that

**Comment by nattthebear** [comment]
> different mousedown behaviours

Seems the same to me

**Comment by meshuggahtas** [comment]
I'm not really sure if I checked it correctly, but I didn't saw different hover or mousedown behaviour. Even the click has the same event handler. I only used Chrome F12 JS console and named the event handler to see if its different for the **5** sets of buttons

**Comment by YoshiRulz** [comment]
Still present in https://github.com/TASVideos/tasvideos/commit/16979ff9fe8335dfbf2e7b6ebde83f98506e1ade

**Comment by Masterjun3** [comment]
It should probably be specified in the title that this is a difference purely in the *css style* of the buttons, all *functional* behaviors are the same and work fine.

**Comment by adelikat** [comment]
cool, they are different.  What is the complaint? I don't know what to do to close this.  Is it just because they are different colors?

**Comment by Masterjun3** [comment]
This image shows the issue specifically:
![image](https://user-images.githubusercontent.com/22375320/157059268-da212a4f-4acc-4db1-9570-2545baf0465a.png)

All of the middle buttons are hovered over with the cursor.
With the first style nothing happens, with the second style the background changes and there is an outline, with the third style only the background changes.

This is the inconsistency that was mentioned.

**Comment by adelikat** [comment]
So these behaviors are just the default behaviors of the different bootstrap button types.  The only reasonable thing we can do is make them the same color.  I thought different colors would help separate the different functionalities.  Does that make sense, or should they be the same?

**Comment by YoshiRulz** [comment]
s/`btn-secondary`/`bg-secondary text-dark`/ and s/`btn-success`/`bg-success text-dark`/ fixes that. It seems `btn-*` are semantic, while `bg-*` only use the named colours.
