### ISSUE TITLE
System Error when trying to create page that was deleted

### ISSUE THREAD

**Issue by Masterjun3** [TASVideos/tasvideos#1083]
On my homepage I have a page
https://tasvideos.org/HomePages/Masterjun/Doc/AGDQ2018
and the parent page
https://tasvideos.org/HomePages/Masterjun/Doc
does not exist anymore.
From what I can see in the Discord logs, this page was deleted on January 2nd:
```
Page HomePages/Masterjun/Doc DELETED by adelikat
(2 revisions)
```
Not sure why it had to be deleted, but well, it isn't the focus of this issue.

The actual problem is that when I try to recreate (edit) it, I get a system error.
```
System Error
An unexpected error has occurred.
The information has been logged and will be investigated as we continue to improve the reliability of the site.
```

**Comment by meshuggahtas** [comment]
Is your original Doc page had any text, or you just used it as a directory?

It looks like there are some other pages being deleted for the same unknown reason

List of all deleted "directory" pages, only 3 total:
https://tasvideos.org/HomePages/Masterjun/Doc
https://tasvideos.org/HomePages/Noxxa/Awards
https://tasvideos.org/HomePages/Ready%20Steady%20Yeti/Subs

How I wrote this list:
- Go to https://tasvideos.org/HomePages
- CTRL+F for / (107 matches as of writing)
- If you only see Doc / AGDQ2018 but not Doc before that entry, the page named Doc is deleted
