### ISSUE TITLE
Encode Embed Link generates broken Link to video

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#1084]
Example https://tasvideos.org/7292S

The video can be viewed embedded, but `Link to video` is https://www.youtube.com/embed/ttps://www.youtube.com/embed/DNKW92NuviY and I can't fix it by fixing what is entered in the field. Putting https://www.youtube.com/embed/DNKW92NuviY turns into https://www.youtube.com/embed/ttps://www.youtube.com/embed/DNKW92NuviY after you save, and only entering the ID shows `The Encode Embed Link field is not a valid fully-qualified http, https, or ftp URL.`

**Comment by Invariel** [comment]
It looks like it's trying to double up the URL but where it's trying to put the code (after the / after the first 'embed') it's inserting the entire string again at character 1+.  Should be a relatively easy fix once someone can look at that code.

**Comment by vadosnaprimer** [comment]
<s>It refuses to save.</s>
