### ISSUE TITLE
Make titles bigger on certain pages

### ISSUE THREAD

**Issue by Masterjun3** [TASVideos/tasvideos#1087]
On busy pages like submission threads or submission pages the title can get buried in the design of surrounding elements.
I made them bigger to counteract this, but the size increase was removed in the title redesign.

Example:
![image](https://user-images.githubusercontent.com/22375320/152945260-e4181768-ff7b-4cde-a480-8f02425dc8e9.png)
In this image the status is bigger than the title, making the status, judge, and publisher look more important than the actual title and author.

**Comment by adelikat** [comment]
How about making the status smaller instead?

**Comment by Masterjun3** [comment]
That is probably fine. But I also mentioned that I wanted the *submission thread* header to be bigger.
But this issue isn't really important to me anymore, so you can close it anytime, if you want.
