### ISSUE TITLE
Break up the right menu at narrow res

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#1102]
![изображение](https://user-images.githubusercontent.com/7092625/153760381-e88542f0-24e7-4bb5-904a-9a87dcffd262.png)

It feels like the right menu needs some linebreaks just like the left one has. This pic is right before they all collapse to hamburger, but wider res may look better on bigger resolutions too?

**Comment by Masterjun3** [comment]
Oh this was also fixed in #1123.
