### ISSUE TITLE
Weird behavior with URL case sensitivity

### ISSUE THREAD

**Issue by Stovent** [TASVideos/tasvideos#1105]
At the end of the [Emulator Resources page](https://tasvideos.org/EmulatorResources), there is the dropdown menu with all the subpages.
In here, LibTAS is listed twice. One with a lower case L in the URL, and one with the upper case L.

The lower case one returns a NotFound error, but what bugs me is that the NotFound page says `Although the site handles URLs case-insensitively`, and indeed I can access my homepage with any capitalization in the URL. But why does the libTAS page gives an error in this case ?

**Comment by meshuggahtas** [comment]
This problem has been already reported and the discussion over there covers this: https://github.com/TASVideos/tasvideos/issues/726

Closing issue.
