### ISSUE TITLE
Most Active Editors is missing movie edits

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#1107]
Old site had both types

![изображение](https://user-images.githubusercontent.com/7092625/154812183-784cd8c3-660f-47ea-aa9f-ed3195d87eaa.png)

New one only counts wiki

![изображение](https://user-images.githubusercontent.com/7092625/154812194-f09bf66e-9d1c-4d1a-8c83-55cdfec85c0a.png)

**Comment by adelikat** [comment]
We don't track movie edits in the new code, sorry
