### ISSUE TITLE
[Feature Request] "Random Movie Showcase" on the Main Page

### ISSUE THREAD

**Issue by ViGadeomes** [TASVideos/tasvideos#1111]
Taken from the very old forum thread for the change of Vault tier suggested by Samsara and some others.

Back in the day, Vault was so underrated that Vault movies had no chances for beeing watched but even today, all Moons and Standard movies that aren't Recommended for newcomers don't have a lot of chances to be watched by people that aren't really on the site so this feature still applies.

So the suggestion is to add under the featured movie on the Main Page a movie randomly taken from all TASvideos movies. 

The implementation is still to discuss : I would prefer this to be each time the TASvideos Main page loads (so on the user side) instead of it beeing on the site side (like the featured movies for newcomers) but it really depends on the ressources needed.

**Comment by Masterjun3** [comment]
Does this require a code change?
[Currently](https://tasvideos.org/Wiki/ViewSource?path=System/FrontPage) the first featured movie is taken from Newcomer Recommendations if the user is not logged in, and from Stars if the user is logged in.
If a change is wanted it would just need to be edited there.

**Comment by ViGadeomes** [comment]
Yes it would need a code change because what is asked is in addition to the first featured movie : taking one randomly from Moons or Standard class which would never be featured in any situation as of right now. It would be a second "featured" (if we can call it this way) movie that we can call "Random Movie Showcase" as it has been suggested by Samsara and others back in the day.

**Comment by Masterjun3** [comment]
You could just add a second module in the wiki source code. What exact change do you need from the site code?

**Comment by ViGadeomes** [comment]
Oh ok, sorry then. I didn't think it was possible with wiki modules, wasn't sure how it works behind. closing the issue then...
