### ISSUE TITLE
Remove "Please do not fill the forums with movie requests" from forum header

### ISSUE THREAD

**Issue by ThunderAxe31** [TASVideos/tasvideos#1115]
Current full line of text https://tasvideos.org/Forum
`Welcome, this is the discussion board of TASVideos. Please do not fill the forums with movie requests. Enjoy your stay.`

This is what all visitors get greeted with. This is a very old line of text, a legacy from [2008](https://web.archive.org/web/20080517103031/http://tasvideos.org/forum/). I think that's completely unnecessary and should be removed entirely. And maybe put some more useful links instead.

**Comment by vadosnaprimer** [comment]
Agreed.

**Comment by adelikat** [comment]
Removed the "please do not fille forums with movie requests" line.  But more importantly I changed it so that the header renders System/ForumHeader, so this is no longer a dev problem
