### ISSUE TITLE
Editable but not viewable page Roles/Details

### ISSUE THREAD

**Issue by meshuggahtas** [TASVideos/tasvideos#1116]
- Link of the page returns 404 error https://tasvideos.org/Roles/Details
- This page is linked multiple times @ https://tasvideos.org/Staff
- Link of the page to be edited shows there is content and the page exists https://tasvideos.org/Wiki/Edit?path=Roles/Details

Have no idea where is the problem.

**Comment by adelikat** [comment]
Roles/Details is no longer a wiki page, it was deleted for being redundant.  Now this url is for linking to a single role by adding it to the url: https://tasvideos.org/Roles/Details/Judge

I cleaned up the Staff page to stop linking to the now deleted
