### ISSUE TITLE
404 error on non existing profile links

### ISSUE THREAD

**Issue by meshuggahtas** [TASVideos/tasvideos#1119]
- https://tasvideos.org/Users/Profile/MisterEpic

Non existing home page links correctly redirects to DoesNotExist https://tasvideos.org/HomePages/MisterEpic

**Comment by Masterjun3** [comment]
Not sure why a non existing profile should link to `HomePageDoesNotExist`. I don't see the bug in linking to a 404 error.

**Comment by meshuggahtas** [comment]
I was thinking about [PageDoesNotExist](https://tasvideos.org/Wiki/PageDoesNotExist)

**Comment by Masterjun3** [comment]
That's for Wiki pages. That Page offers you to edit and thus create the page. It wouldn't make sense.
