### ISSUE TITLE
Increase size limit for forum PMs

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#1120]
Current limit seems to be 10**1**0 chars. If somebody can pack all the relevant info into that limit, good, but if not, they just have to send **more** PMs in a row. I don't feel this solves any problems without causing new ones.

I don't know what the limit should be though. Would depend on how often people send huge PMs and how big they can actually be.

**Comment by meshuggahtas** [comment]
I think PM size limit should be the same as Forum  Post size limit.
