### ISSUE TITLE
Don't erase the poll options if the user forgets to set the Question text

### ISSUE THREAD

**Issue by ThunderAxe31** [TASVideos/tasvideos#1122]
Repro:
1. Open the page for creating a new poll.
2. Click on "Add poll".
3. Add at least two Options for the poll.
4. Add something in the "Title" field.
5. Write your post text.
6. Don't write anything in the "Question" text field.
7. Hit "Save" button on bottom.
Result: the site will create your topic without a poll, without warning you. As a consequence, the users will be confused and you'll have to add the poll options post by editing the topic.

Suggested solution 1#: Make the "Question" field non-obligatory.
Suggested solution 2#: Make the page refusing to submit the topic if then "Question" field is left blank, just like it does when you leave the "Title" field blank.

**Comment by Masterjun3** [comment]
Reopening due to revert in 188f294f8e858a36858cf43dc17d43b5e6214302
