### ISSUE TITLE
Add SubmissionStatus "Playground"

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#1131]
We have 22 out of 24 votes for this approach to the "concept demo" section of the site. 0 against, 2 indifferent.
https://tasvideos.org/Forum/Topics/22927

In the future we'll need to have a module that displays submissions with this status on game pages in some way but I think that should be a separate issue after some discussion. Also we'll need to give tasers of a game privs to move its submissions between rejected and playground but that requires even more discussion, and this can be decided only by judges for now, at least until we have a solid agreement about the rules.

**Comment by SamsaraTAS** [comment]
Any step we take here is a huge one. Just having the submission status means Judges can start applying it now while we all continue to discuss the exact implementation we want to go with.

**Comment by Masterjun3** [comment]
Not sure about how useful it is to implement a part of a system that isn't even worked out yet. I think the "delayed" submission status works for now until site staff has worked out the system a bit more. Implementing this as it is now would practically be wasted time.

**Comment by vadosnaprimer** [comment]
Why is it wasted time exactly? Will the part that's already decided and agreed have to be undone because of some reason?

**Comment by Masterjun3** [comment]
Adding a new submission status has a lot of parts that need to be implemented. Where does the submission thread go based on where the current submission resides, who can set or reset the status with which permissions.
These are things that you have to implement for a new status, there is no "default" status. And if the rules on those aren't decided, the site developer has to just implement whatever and hope it won't be hard to adjust once the rules are decided.

Just check out this function and you should see why a "rules to be decided" doesn't really work.
https://github.com/TASVideos/tasvideos/blob/f327f881422891a33845110929393512ad04333d/TASVideos.Core/Services/QueueService.cs#L72-L167
