### ISSUE TITLE
Sorting Activity/Judges

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#1132]
Ideally there would be options to sort by date or by status, but I would personally be fine if it just sorts by date instead of status like it does currently.

**Comment by adelikat** [comment]
Submission create date or judge date?

**Comment by vadosnaprimer** [comment]
Ideally judge date. We're looking at decisions so it makes sense to sort by date of a decision, which may not be even remotely close to submission date.

**Comment by vadosnaprimer** [comment]
I realized I missed a detail, and after checking how this works I need help. Is there a way to put certain statuses at the very top and then sort **the rest** by id?

**Comment by adelikat** [comment]
Yes
