### ISSUE TITLE
404 error on Profile page of users with / character in their name

### ISSUE THREAD

**Issue by meshuggahtas** [TASVideos/tasvideos#1133]
- 404 error when trying to visit their page: https://tasvideos.org/Users/Profile/%2F*-
- Manually changing %2F to a /: https://tasvideos.org/Users/Profile//*-
[Users/Profile//*-](https://tasvideos.org/Users/Profile//*-) may take you to the intended page if the site guessed your intents right.

Total number of users with / in their name: 3

Remaining 2 users' profile page:
- https://tasvideos.org/Users/Profile/Time%2FSpaceMage
- https://tasvideos.org/Users/Profile/Xpenguin%20%2F%20IZVAC

**Comment by Masterjun3** [comment]
Yeah this was discussed before going live and the user needs to be renamed. We heavily rely on / being a page separator.

**Comment by Masterjun3** [comment]
Reverted the opening post and title to a previous revision because unrelated information was added and made the issue confusing.

**Comment by meshuggahtas** [comment]
Sorry, I didn't found where should I dump this information.

 I wanted to list all problematic usernames, so I went to search for the "allow only specific characters for new usernames" but I don't know which issue to choose:
- https://github.com/TASVideos/tasvideos/issues/119
- https://github.com/TASVideos/tasvideos/issues/61
- Or create a new issue?

**Comment by meshuggahtas** [comment]
1. Information dump: I meant as collecting every potential username problems. Dump as in every relevant information.

2. Space Question mark: 
- I wrote this: **Characters used in existing usernames but has problems on other places:**
- I meant this: These characters are used but they might not work on every possible places. There is too many places to just simply answer where this should work or where not. Sending PM to user, uploading movie as that user, posting on forum, editing wiki page, making anything with such user... Since I have no definitive answer, I just vaguely said it might have problems at other places. There is also no test server as I know and since I can't test special cases (can't register usernames on my own demo server since there is no email sending as far as I know).
- Question mark: [https://tasvideos.org/Users/Profile/What?! ](https://tasvideos.org/Users/Profile/What?! )Does not work. I get 404 error.This is a direct issue for those who register with such name. A question mark in the profile name might won't work on pages where there are other parameters of the URL after the presence of the username.
- Space: I didn't find a place where this is 100% a direct issue, only thing I know is that a username with a single space (1 byte username) will redirect their user profile to Users/List. Test link with a space: [https://tasvideos.org/Users/Profile/ ](https://tasvideos.org/Users/Profile/ )
3. Hashtag and Question mark as first character:
- I wrote this: **Characters used in existing usernames but needs to be banned in case it's in the first place (starts with):**
- I meant this: There are usernames that has these characters (hashtag for this point) which won't work if it's the first place. A user named #Something won't have a working profile page. 
- primorial#soup is not first character, I just showed that someone uses that character already
- This is a direct issue for... point 2 last line

I've got tired writing this post but that's all information/known issue I had to say after I checked every single username yesterday.

**Comment by Masterjun3** [comment]
> These characters are used but they might not work on every possible places.

> I didn't find a place where this is 100% a direct issue

This is exactly what I mean. Do not do this. Don't *assume* things don't work. **Only report direct issues!**

> A user named #Something won't have a working profile page.

There is no such user, and you can't register an account like that. You're assuming things again.

> [https://tasvideos.org/Users/Profile/What?! ](https://tasvideos.org/Users/Profile/What?!)Does not work.

Your link is wrong. It's https://tasvideos.org/Users/Profile/What%3F%21 . You need to escape special characters. That's how URLs work.

**Comment by Masterjun3** [comment]
No, the website can't do anything about users using URLs wrong. The browser doesn't even send the URL fragment to the server.
Also, I'm going to collapse this conversation, as it is unrelated to the issue.

**Comment by adelikat** [comment]
Closing this issue 

> Reverted the opening post and title to a previous revision because unrelated information was added and made the issue confusing.

This.  The user's just need to be renamed.  @vadosnaprimer @MemoryTAS , if needed I can provide a list of users with / in their name to change.  This is an admin task and not a site development problem, so closing this ticket

**Comment by vadosnaprimer** [comment]
> This. The user's just need to be renamed. @vadosnaprimer @MemoryTAS , if needed I can provide a list of users with / in their name to change. This is an admin task and not a site development problem, so closing this ticket

Let's have them as a discord pin.
