### ISSUE TITLE
Double clicking Forum Post/Edit results in empty page

### ISSUE THREAD

**Issue by meshuggahtas** [TASVideos/tasvideos#1134]
When double clicking on posting on forum (new thread, new post, edit post, etc), the visitor gets a fully white page.

1. Create a new forum post
2. Click twice on Save
3. The forum post is created, but you are seeing an empty page

This is only a visitor (frontend display) problem.

**Comment by Masterjun3** [comment]
This is the debouncer doing its work. By design.
If you have javascript enabled the button is disabled for a short time so you don't accidentally double click and cause two requests.

**Comment by meshuggahtas** [comment]
Ah, okay. Well I have javascript enabled and I accidentally clicked twice, resulting in an empty page. 

Very easy to reproduce, so I'm going to assume that the "disabled for short time" isn't working as intended and I think if there is a misdesign in place for accidentally making double posts, the visitor should be redirected to his latest post.

When this happens, going back with the browser back button lands you on the edit page, so you need to press back twice to get back to the original forum thread/post page.
