### ISSUE TITLE
Implement Word Warp in the Forum's Code Function.

### ISSUE THREAD

**Issue by Spikestuff** [TASVideos/tasvideos#1139]
Couldn't spot an issue request related to this (inb4 blind).
But just to display an immediate example of what I mean is [just load up this topic here](https://tasvideos.org/Forum/Topics/18914).

![image](https://user-images.githubusercontent.com/12412764/156708936-3b35c102-4eb3-47f1-8983-7fa819289345.png)

**Comment by nattthebear** [comment]
When code tags are being used to display actual source code, then word wrap is actively bad.  That post should not have used a code tag to hold intertwined prose and code.

**Comment by Masterjun3** [comment]
Yeah, word wrap would also be problematic on small widths. It would make posts with actual code have a lot of height.
I think it would make more sense to leave this as is, and if you want monospace you'd use [tt].

**Comment by meshuggahtas** [comment]
Word wrap: Good idea and the site already uses it.

Another relevant feature I saw on other websites is the ability to show/hide code.

**Comment by Spikestuff** [comment]
> Word wrap: Good idea and the site already uses it.

Good idea but it only works on actual code and not nothing.

**Comment by meshuggahtas** [comment]
This doesn't sounds like an obstacle.

**Comment by nattthebear** [comment]
This won't be changing because ability to display text with no extra wrapping is an essential requirement for viewing actual code.  For things that aren't code, please use the non-code formatting tools and feel free open a new issue if the non-code formatting tools are insufficient for formatting things that aren't code.

**Comment by TiKevin83** [comment]
I agree with natt here, the word wrap can happen already by ending and restarting the code blocks

**Comment by Invariel** [comment]
The correct way to display code in a code block is as the initial screenshot depicts it: with a horizontal slider.

While this may be inconvenient for people who actually care about the code, or for people who misuse the code tag, it is the intended result of that tag.  No wrapping, carriage returns (and newlines) only.
