### ISSUE TITLE
Google Search results include old revision wiki pages

### ISSUE THREAD

**Issue by Masterjun3** [TASVideos/tasvideos#1140]
When searching for example for `tasvideos m64 fix formatting` on google, for me it includes a result to https://tasvideos.org/EmulatorResources/Mupen/M64?revision=2
If we don't want this it might make sense to block these in robots.txt, with stuff like `Disallow: /*?revision=*` (or something like that).

**Comment by adelikat** [comment]
Another thought I had, is maybe it should be clear when you are looking at an old revision of a page, similar to how we do when you are viewing an obsolete movie
