### ISSUE TITLE
Older userfiles won't download - network and System Errors

### ISSUE THREAD

**Issue by coolkirby2000** [TASVideos/tasvideos#1142]
On [my userfiles list](https://tasvideos.org/UserFiles/ForUser/CoolKirby), I can only download files from the last 9 days without issue.

But a file from 10/19/21 ([A7800 Choplifter](https://tasvideos.org/UserFiles/Info/74969493952058015)) always fails to download. Desktop Chrome claims a network error, Android Chrome will be stuck at 0KB downloaded.

[Frogger 2](https://tasvideos.org/UserFiles/Info/74821290378450750) from 10/13/21 and [Kirby](https://tasvideos.org/UserFiles/Info/36222432332944819) from 1/8/17 redirect to a System Error page. Userfiles older than 2017 all give either the download error or the System Error page as well.

**Comment by Masterjun3** [comment]
This might be unrelated to the date itself, since I can download certain files from 2012 fine. But the error does happen for other files.

**Comment by meshuggahtas** [comment]
I also found an **unexpected error** while randomly downloading CoolKirby's files:
https://tasvideos.org/UserFiles/Info/6990072507030235?handler=Download

**Comment by nattthebear** [comment]
@adelikat For https://tasvideos.org/UserFiles/Info/74969493952058015, could you produce for me the data stored in the database for it?  This means the full file content as raw binary (pulled directly from the DB, not the app) and the exact values in all of the other columns of that table.

**Comment by CasualPokePlayer** [comment]
>     * PC Windows 10 Firefox works for original A7800 example movie file from OP
> 

This file also downloads fine for me on Firefox Mobile. Chrome Mobile also fails for me.

**Comment by nattthebear** [comment]
7b9d989319bcc22576436f1eacd7dc138024b28e
