### ISSUE TITLE
Scrolling to a forum post might not always works

### ISSUE THREAD

**Issue by meshuggahtas** [TASVideos/tasvideos#1147]
- Example post link: https://tasvideos.org/Forum/Posts/512742
- URL bar after visiting that link: https://tasvideos.org/Forum/Topics/8694?CurrentPage=10&Highlight=512742#512742

Expectations:
1 - The link of a forum post scrolls to that post
2 - Even if I refresh the page with F5
3 - Even if I press enter in the URL bar

Observations:
1 - OK, tested Windows 10 Chrome and Firefox, Android Chrome

2 - Windows 10 Chrome and Firefox and Android Chrome (pull down from top) **NO, scroll position stays where I pressed F5**

3 - Windows 10 Chrome OK,Windows 10 Firefox OK, Firefox even stays on the currently loaded page and scrolls down to the post.
**However, Android Chrome stays on previous scroll position.**

I'm not sure if this is by design.

**Comment by adelikat** [comment]
I don't think there is anything we can do about this one.  We did our job, which is to provide an anchor and put the value in the anchor fragment.  It's up to the browser to behave at that point.

**Comment by meshuggahtas** [comment]
I think there is a misunderstanding. The URL is not a simple # link like a static page where there are anchors to jump on. I didn't included the 4th scenario which makes this simple to observe:

4 - Even if I press enter in the URL bar after scrolling somewhere

This will won't work, because going to a forum post is not a static link.

But I'm okay if this stays closed.

**Comment by meshuggahtas** [comment]
- This bug is mostly Chrome's fault, not the developers of this repo! This can be confirmed with any page by selecting a text, right clicking and selecting "Copy link to highlight". Using this link in the 3 (+1) scenarios shows that Chrome incorrectly interprets the anchor depending on what special characters. I should have think about Chrome having bugs not just this repo, sorry!
- Deleted my previous comment which was mostly incorrect information.
- 4th scenario: Even if I press enter in the URL bar after scrolling somewhere: Windows Chrome BUG, Windows Firefox OK, Android Firefox OK.
