### ISSUE TITLE
API : give example in the documentation for basic requests

### ISSUE THREAD

**Issue by GB127** [TASVideos/tasvideos#1149]
Hello!

I'm currently trying to get the latest publications via the api.

So far I'm using this link for the requests : "https://tasvideos.org/api/v1/Publications".
However, as it turns out, it retrieves everything. I'm not sure to understand how to fix that as the documentation found there:
https://tasvideos.org/api/index.html

Doesn't give example. I suspect I need to use the field sort. But I'm not sure how to use it. What are the available fields? Etc.

Here are some example of apis that gives more than enough details if you need some reference or inspiration:

- https://db.ygoprodeck.com/api-guide/
- https://github.com/speedruncomorg/api/tree/master/version1
- https://github.com/racetimeGG/racetime-app/wiki/Public-API-endpoints

**Comment by meshuggahtas** [comment]
If you click on a desired request, you will see every details you need and even the ability to try it out from your own browser.

1. Go to https://tasvideos.org/api/index.html
2. Click on Publications]
 GET
 [​/api​/v1​/Publications​/{id}]()
 Returns a publication with the given id.
3. You will see you can now edit the parameter id which requires a digit. Fill in with a number higher than 0 less than ~4600.
4. You get the result of your request, ability to download it in different formats and everything else required to interact with the API.

Comparing TASVideos API with the official Swagger API example site https://petstore.swagger.io/ , I think the only thing might be a good feature request is filling in default values that results in a correct API request. For example a number for Publications/id

**Comment by GB127** [comment]
So Id are always ascending?

**Comment by GB127** [comment]
Thank you! I got what I wanted. Still encourage to improve the documentation and provide some examples. I was very confused when I tried your documentation.

**Comment by adelikat** [comment]
Honestly, I feel like what we have is good enough.  It follows standard RESTful design practices that are easily searchable on the internet for examples.  That isn't to say it can't be improved, but it can always be improved.  I don't want unlosable tickets here, so I'm closing this ticket as the supported needed was provided.
