### ISSUE TITLE
Profile Data - Location should have smaller size or break word

### ISSUE THREAD

**Issue by meshuggahtas** [TASVideos/tasvideos#1158]
Value without spaces will overflow behind other elements. edit: this results in a longer horizontal scroll bar than the page's size

Example at Profile:
![location](https://user-images.githubusercontent.com/31288337/158595217-1c17950e-4e9e-40a9-b9fa-61aa43d345b3.PNG)

Current size: 256

Unable to test it on forum because I get Access Denied when attempting to make a new thread on local server.
(edit: VSCode issue. forum post + location can be tested with VS2022)

edit: It looks like there are other fields where values without a single space will overflow behind/on top of other elements. Another example would be Forum Poll Description and Forum Poll Value.

**Comment by adelikat** [comment]
Closing this as "won't fix", it isn't worth the extra html complexity to deal with what would only be the result of a bad actor.  Note that if spaces were in there, it would wrap appropriately, no reasonable value would look like this.

Better would be a moderator to fix an intentionally malicious profile value if it comes up
