### ISSUE TITLE
VS Code + Relaunching without logging out permission problem

### ISSUE THREAD

**Issue by meshuggahtas** [TASVideos/tasvideos#1160]
Using VS Code + TASVideos, if you close it while logged in, the next time you start it, your permissions will be empty.

Tested: Windows 10 x64

Original text:
- I get Access Denied when attempting to create a new thread and there is no ability to comment on UserFiles.
- Using VS 2022 + Dev (Generate Sample Data) + Windows 10 x64 (and closing solution while logged in and starting Dev (Sample Data No Recreate) this problem doesn't happens.
- Tried uses: adelikat, MESHUGGAH

edit: reformatted, clarified issue and removed unnecessary info

**Comment by nattthebear** [comment]
Workaround:  After starting the site and logging in, you may need to log out and back in once or twice to get all of the permissions to register.  This is a problem with the permissions system and isn't particularly related to forums.

**Comment by Masterjun3** [comment]
This might have been the same issue as #1883 ? And then fixed by #1884 ?
Can someone test with VS Code and still reproduce this issue?

**Comment by Masterjun3** [comment]
There have been no other reports of this happening, and the relevant code sections have been changed in the meantime. So I'm going to close this.
