### ISSUE TITLE
Local Dev Setup .NET SDK Question

### ISSUE THREAD

**Issue by meshuggahtas** [TASVideos/tasvideos#1163]
Which .NET release required, **SDK** 6.0.201 or **ASP.NET Core Runtime** 6.0.3 ?

I want to clarify which version the developer should use in the Wiki for different platforms.

The Wiki currently refers to ,NET as ".NET Core 6.0 SDK" @ [Prerequisites](https://github.com/TASVideos/tasvideos/wiki/Local-Development-Setup#prerequisites). I've used .NET 6.0 SDK for writing the manual (the code for Ubuntu and MacOS).

**Comment by nattthebear** [comment]
> Which .NET release required, SDK 6.0.201 or ASP.NET Core Runtime 6.0.3 ?

The documentation says ".NET Core 6.0 SDK".  Which of those two has SDK in the name, and which doesn't?

**Comment by meshuggahtas** [comment]
One of them is named SDK 6.0.201 and the other one is named ASP.NET Core Runtime 6.0.3.

To your answer, the first one includes it and the second one isn't.

So your answer is... ?

**Comment by nattthebear** [comment]
Why would you think, when the documentation asks you to download the "SDK", that you would get the one that doesn't say "SDK"?

If you think the wording could somehow be somehow improved, go ahead and submit a PR, but I think you're the only one that was confused by that.

**Comment by Invariel** [comment]
First, @nattthebear, could you please be marginally less inflammatory with your comments and questions?
Second, a Google search for ".net 6.0 sdk" brings you to Microsoft's definitely-not-confusing https://dotnet.microsoft.com/en-us/download/dotnet/6.0, which lists the SDK on the left and a collection of Runtime downloads on the right.

While the SDK is (obviously) required to develop the website, it is feasible, particularly when presented with Microsoft's page, to wonder if a Runtime environment is required to deploy and test the site locally.  I don't know if the Runtime is required, since I had it installed on my machine before looking at website code; an answer to the actual question would be very useful.

**Comment by nattthebear** [comment]
The word "runtime" does not appear at all in our developer setup documentation.  Why would you think you need something that the documents don't ask you to have?  You need the SDK as the docs say you need the SDK.  You don't need any runtimes as the docs make no mention of it.  The documentation would be incredibly difficult to read if it tried to list all of the things that aren't needed and don't matter one way or the other in it.

Closing (again) as the question has been asked and the question has been answered.

**Comment by meshuggahtas** [comment]
The reason I ask this because I've made the documentation. I've wrote it based on a 2020 GitHub readme this repository had.

I guess @nattthebear didn't knew that. So I'm asking the developers to make sure that which version does it requires for local testing.

According to the Microsoft dotnet download link, the other one without the word SDK seems to be also enough to do local tests. 

Since we are talking about the Local Developer Setup page, I want to clarify which release to use.

I didn't got a definitive answer so far on which is required to develop, so I'm reopening this issue once again.

**Comment by adelikat** [comment]
Use SDK please.

**Comment by meshuggahtas** [comment]
Thanks!

**Comment by nattthebear** [comment]
> I guess @nattthebear didn't knew that.

No, I did not.  But the first thing I did when I read this issue was to verify the build setup and documentation against what Microsoft has available.  I gave the answer I did because it was the right answer; not to annoy you.

**Comment by meshuggahtas** [comment]
No problem. I never developed large C# applications so all I could do is rereading this repo's README before I combined it into a Wiki and trying to interpret Microsoft's description of "ASP.NET Core Runtime".
