### ISSUE TITLE
AddEditPoll too many options

### ISSUE THREAD

**Issue by meshuggahtas** [TASVideos/tasvideos#1167]
Adding too many options to a forum poll (value unknown at the moment, I've added more than 26 options with a string and 39 options without a string (empty fields)) results in an exception.

I don't know what it is because my VS Code hanged up for 10 minutes and then I closed the solution.

**Comment by adelikat** [comment]
I can't reproduce.  The only limit you should be hitting here is POST limitations, there's nothing in the code that would particularly break with the number of poll options mentioned here.  Any honest attempt at a poll will work, only a hacking attempt could fail, which we are happy to let fail.
