### ISSUE TITLE
Repo GitHub Action .NET Core

### ISSUE THREAD

**Issue by meshuggahtas** [TASVideos/tasvideos#1172]
The repo's .NET Core action configuration (.yml file) is outdated
- the branch is now called **main**
- .NET 6.0 instead of 5.X and 3.X
- Here is my workflow file for reference: https://github.com/meshuggahtas/tasvideos/blob/main/.github/workflows/dotnet-core.yml
- edit: here is the summary result of my workflow https://github.com/meshuggahtas/tasvideos/actions/runs/2008181407
- Here is the result of my workrunner Test log, which say build failed albeit 0 failure
```
 Test run for /home/runner/work/tasvideos/tasvideos/tests/TASVideos.Test/bin/Debug/net6.0/TASVideos.RazorPages.Tests.dll (.NETCoreApp,Version=v6.0)
Microsoft (R) Test Execution Command Line Tool Version 17.1.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.

Passed!  - Failed:     0, Passed:   254, Skipped:     0, Total:   254, Duration: 1 s - /home/runner/work/tasvideos/tasvideos/tests/TASVideos.Test/bin/Debug/net6.0/TASVideos.RazorPages.Tests.dll (net6.0)
    10>Done Building Project "/home/runner/work/tasvideos/tasvideos/tests/TASVideos.Test/TASVideos.RazorPages.Tests.csproj" (VSTest target(s)).
     1>Done Building Project "/home/runner/work/tasvideos/tasvideos/TASVideos.sln" (VSTest target(s)) -- FAILED.

Build FAILED.

       "/home/runner/work/tasvideos/tasvideos/TASVideos.sln" (VSTest target) (1) ->
       "/home/runner/work/tasvideos/tasvideos/tests/TASVideos.Data.Tests/TASVideos.Data.Tests.csproj" (VSTest target) (13) ->
       "/home/runner/work/tasvideos/tasvideos/tests/TASVideos.Data.Tests/TASVideos.Data.Tests.csproj" (default target) (13:2) ->
       "/home/runner/work/tasvideos/tasvideos/TASVideos.Core/TASVideos.Core.csproj" (default target) (9:4) ->
       "/home/runner/work/tasvideos/tasvideos/TASVideos.ForumEngine/TASVideos.ForumEngine.csproj" (default target) (6:5) ->
       (CoreCompile target) -> 
         /home/runner/work/tasvideos/tasvideos/TASVideos.ForumEngine/BbParser.cs(250,26): warning CS8524: The switch expression does not handle some values of its input type (it is not exhaustive) involving an unnamed enum value. For example, the pattern '(TASVideos.ForumEngine.BbParser.TagInfo.ChildrenAllowed)4' is not covered. [/home/runner/work/tasvideos/tasvideos/TASVideos.ForumEngine/TASVideos.ForumEngine.csproj]
         /home/runner/work/tasvideos/tasvideos/TASVideos.ForumEngine/BbParser.cs(345,8): warning SA1513: Closing brace should be followed by blank line [/home/runner/work/tasvideos/tasvideos/TASVideos.ForumEngine/TASVideos.ForumEngine.csproj]

    2 Warning(s)
    0 Error(s)

Time Elapsed 00:00:53.63
Error: Process completed with exit code 1.
```

Observation:
- I assume the build failed problem is because of .NET 6.0 (as in something in the .yml file needs to be updated to be compatible with it). 
- edit: Maybe I still need to use some earlier .NET versions like 5.X and 3.X as well?
- edit2: I've googled my issue and it says the tests might require different .NET versions. If this is true, I assume that's also requires an update.

I have also a question: How does the original tasvideos repo GitHub workrunner say the build is successful if it uses outdated configuration?

edit3: relevant links
- Setting up dotnet workflow https://github.com/actions/setup-dotnet
- Issue where I've got the idea of probably the tests require different .NET versions https://github.com/microsoft/vstest/issues/2570

**Comment by nattthebear** [comment]
The website proper should be built against .NET 6, if there's any older versions around, eliminate them.  Not sure about the tests; @adelikat is the main one maintaining and running those.

**Comment by adelikat** [comment]
It also isn't being built by anything right now

**Comment by meshuggahtas** [comment]
I've checked my personally used github repo integrations with my tasvideos fork, and I'm more sure that the problem is related to  Tests trying to use .NET 6.0 but not supported.

The following integrations all worked before Jan 7 branch deletion. Here are the errors from my integrations. Please assume my fork being exactly the same as this repo apart from addition of workflow files. Project and other .cs .HTML any files are the same.

1. snyk.io SNYK
- Found TASVideos/appsettings.Development.json [main] Unable to parse json file, check for valid syntax [More info](https://support.snyk.io/hc/en-us/articles/360001373118-Project-import-errors)
- Found TASVideos/appsettings.json [main] Unable to parse json file, check for valid syntax [More info](https://support.snyk.io/hc/en-us/articles/360001373118-Project-import-errors)
- Snyk Code [main] socket hang up [More info](https://support.snyk.io/hc/en-us/articles/360001373118-Project-import-errors)

According to my SNYK log, the Tests uses .NET 6.0 from https://github.com/TASVideos/tasvideos/blob/9c5b678bc63e2e3d1614aad5574e0d75b04b8a50/tests/TASVideos.Test/TASVideos.RazorPages.Tests.csproj#L3

2. codacy.com Codacy
- Sent email to support, waiting for answer, unable to add my own tasvideos fork

3. lgtm.com LGTM
- Unable to build original tasvideos (this) repo. Coincidentally the build is stalling, but the result will be on this link once it's succeeds/fails https://lgtm.com/logs/02111736bc2daf8b55788f153207ab1d6e50a612/lang:csharp

**Comment by adelikat** [comment]
I updated the .yml, but please do not report any more issues with it, if it doesn't work for you.  The .yml is not being used in the main repo, and it is unreasonable to request changes for your fork.  I suggest waiting until we are using it (which will be in the near future, want to be able to build and run unit tests against PRs), or working out changes to it on your own fork.  Until then, this is unnecessary noise for the issue tracker.

**Comment by meshuggahtas** [comment]
Change this line to 6.0.x for an existing .NET version, because 6.0.1 doesn't exist
https://github.com/TASVideos/tasvideos/blob/e47d4bbc67b56e0f4350f3793b5da85bacbfcdf0/.github/workflows/dotnet-core.yml#L19
