### ISSUE TITLE
Gmv and Wtf parsers use Stream.Length property that might be unsupported

### ISSUE THREAD

**Issue by Masterjun3** [TASVideos/tasvideos#1175]
The System.IO.Stream.Length property used in certain parsers can throw a NotSupportedException if the file doesn't support seeking and doesn't directly provide the length any other way. [Documentation here](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.length?view=net-6.0).
This has caused an issue and was reported [on the forum](https://tasvideos.org/Forum/Posts/512981).
This is the example file [PTMA.zip](https://github.com/TASVideos/tasvideos/files/8310640/PTMA.zip)

Our parser tests don't catch this issue because the embedding produces a Stream that supports seeking, and so no error is thrown.

Affected parsers:
https://github.com/TASVideos/tasvideos/blob/3af2d0d57682c2b519b0051e36e71d9b93758535/TASVideos.Parsers/Parsers/Gmv.cs#L41
https://github.com/TASVideos/tasvideos/blob/3af2d0d57682c2b519b0051e36e71d9b93758535/TASVideos.Parsers/Parsers/Wtf.cs#L16

**Comment by adelikat** [comment]
I don't understand what the fix is for this

**Comment by nattthebear** [comment]
It's unclear to me why the stream returned from `ZipArchiveEntry.Open()` does not have a valid `Length`.  That information is present in a zip archive's headers and so can be found without extracting the file.  We can hack around it though.

I think Rust did this better; there, whether a stream can be seeked, written to, read from, length known, etc is all encoded at the type level.  In C#, implementing `Stream` results in a massive amount of boilerplate, much of which is just throwing exceptions.
