### ISSUE TITLE
Inline Rating input value

### ISSUE THREAD

**Issue by meshuggahtas** [TASVideos/tasvideos#1182]
(edited description)
Adding more digits after the tenths part of selectable values will be temporarily shown to the page, should be identical to saved vote.

Repro:
1. Click Rate
2. Press up once to get 0.1 or 0,1 according to your locale settings
3. Insert extra numbers after 1 for example 987654
4. Shows Rated 0.1987654 / 10 but in reality it's saved as 0.2 or 0,2

Leaving the page will show the correct saved rating value.

**Comment by meshuggahtas** [comment]
The following problems persists after the fix:
- Less than step value (0.1): rating will be saved with rounding --> 0.05 becomes 0.1 and 10.049 becomes 10
- -0 and 11: "Rating Failed" popup message when trying to save it. But also when trying to remove it without saving the rating first
- Leading zero: Zero gets removed --> 01 becomes 1, 09 becomes 9
- OK (as in working as intended): -- and -.- and -e +e and other special invalid values--> nothing

**Comment by Invariel** [comment]
Less than the step value rounding to the nearest valid number sounds like things are working as intended.
Leading zero being removed sounds correct as well.

I would strongly recommend that instead of waiting for these issues to be fixed and then supplying more information two weeks later you more closely follow the topics, follow the pull requests, and apply your stress testing to the PRs using a local build of the site to catch issues while they are still in active development.

**Comment by meshuggahtas** [comment]
I also have recommendations for the developers, but thanks for the recommendation. I intend to fix most of the small bug tickets I created once I finished moving to a new flat from my previous house and started understanding the Blazor technology and the structure of the TASVideos code. Currently I don't feel qualified to do even little CSS tweaks. It's one thing I can fix a bug and another it is acceptable to the codebase and meets the standards of the team.

I supplied the information two weeks later because I just finished testing it.

What topics should I follow?

Follow pull requests: hmm. Why would I test a pull request if it gets accepted and be live next day?

Stress test local site: ahh, I'm going to order a 2nd monitor right now. Stupid power outage ruined it. Nevermind. I know what you mean, some things can be tested on local build and I should do that there instead of the live server. Sorry for voting ~30 times in 15 minutes as part of testing. 

It would be great if there would be a test server online, cause I'm having some performance issues (PC getting old, will upgrade it soon).

You can PM me on the forums if anyone wants to communicate with me 1 on 1.
