### ISSUE TITLE
Cannot add the same multicart ROM entry to multiple game pages

### ISSUE THREAD

**Issue by despoa** [TASVideos/tasvideos#1186]
There are TASes for games that only came in multicarts. The [Quattro Adventure series](https://tasvideos.org/GameGroups/170) is an example. All of those games should share the same ROM entry since they came from a multicart, but doing so leads to a `Unable to update Rom The resource cannot be deleted or updated` error message.

If this is a duplicate of an existing issue, you may close this.

**Comment by vadosnaprimer** [comment]
Related? #1030
