### ISSUE TITLE
User Registration - Support additional characters 

### ISSUE THREAD

**Issue by adelikat** [TASVideos/tasvideos#119]
support registering usernames such as adélikat 
But let's disallow usernames like [^_^]

This might be useful:
https://stackoverflow.com/questions/48929693/how-to-take-unicode-characters-as-username-in-asp-net-core-mvc

**Comment by TiKevin83** [comment]
is this still something we want to change? I know we changed a lot with username capabilities since this ticket was last updated

**Comment by adelikat** [comment]
YoshiRulz 🦅 — Today at 10:22 AM
It really depends on what you mean by complete. It's easy enough to allow any letter from any language.
Regex /[-._@+£\pL\pN]+/ matches 1 or more alphanumeric characters or any symbols in that list. Or you could pick exactly which subcategories are allowed. https://www.regular-expressions.info/unicode.html#category
Avoiding RegEx, you can loop over each character and check their Unicode properties: "username".EnumerateRunes().All(r => IsAllowedSymbol(r.Value) || Rune.IsLetterOrDigit(r)), where you could implement IsAllowedSymbol with a static bool array lookup.
adelikat — Today at 10:23 AM
I'm limited to the confines of what the microsoft library allows
and I think all I get is a list

adelikat — Today at 10:25 AM
could we? check out the code and how it interacts with teh library
I'm missing something obvious, or the api is lack luster
YoshiRulz 🦅 — Today at 10:32 AM
Internet says set the prop to null, implement IUserValidator, and use that with IdentityBuilder.AddUserValidator

Pasting this here for future reference
