### ISSUE TITLE
Allow shorter searches to only search in-game names

### ISSUE THREAD

**Issue by Spikestuff** [TASVideos/tasvideos#1190]
The search function currently has a flag for titles that have less than 5 characters cannot be searched.

So titles such as "Myst" can only be searched as "DS Myst" and even the site's lowest character count N+ can be searched as "DS N+" but it doesn't allow finding all movies of said game, or threads of each platform (for example there's a SNES DOOM thread).

I don't know how to explain it other than how I've presented it here.

![image](https://user-images.githubusercontent.com/12412764/159846874-414865c2-3417-4075-8dbf-ad379f9327ea.png)

![image](https://user-images.githubusercontent.com/12412764/159846899-b39b503f-8f84-4a5f-a332-722d82778045.png)

**Comment by meshuggahtas** [comment]
Relevant issue which includes other problematic scenarios https://github.com/TASVideos/tasvideos/issues/420
