### ISSUE TITLE
Searching for only exact phrase

### ISSUE THREAD

**Issue by meshuggahtas** [TASVideos/tasvideos#1192]
Currently it doesn't seems to be possible to search for only an exact phrase consisting of multiple words. I believe there is a bug, but I don't know where.

Here is a list with the phrase, 
- link within double quotes with spaces, 
- link with + instead of spaces,
- link with % instead of spaces,
- link with & instead of spaces, 
- link within double % with spaces

Example 1: **Out of bounds**
- https://tasvideos.org/Search?SearchTerms=%22Out+of+bounds%22 - Not okay, shows multiple results where the exact phrase is not present
- https://tasvideos.org/Search?SearchTerms=Out%2Bof%2Bbounds - Same
- https://tasvideos.org/Search?SearchTerms=Out%25of%25bounds - Same
- https://tasvideos.org/Search?SearchTerms=Out%26of%26bounds - Same
- https://tasvideos.org/Search?SearchTerms=%25out+of+bounds%25 - Same

Example 2: **orange bouncing** (a random, unique phrase to figure out where should be the bug)
- https://tasvideos.org/Search?SearchTerms=%22orange+bouncing%22 - OK, shows the only 1 result
- https://tasvideos.org/Search?SearchTerms=orange%2Bbouncing - OK, same
- https://tasvideos.org/Search?SearchTerms=orange%25bouncing - OK, same
- https://tasvideos.org/Search?SearchTerms=orange%26bouncing - Not okay, shows multiple results where one of the words appear
- https://tasvideos.org/Search?SearchTerms=%25orange+bouncing%25 - Not okay, same as above

Here is the postgres text documentation linked on the Search page https://www.postgresql.org/docs/current/textsearch-controls.html#TEXTSEARCH-PARSING-QUERIES

**Comment by vadosnaprimer** [comment]
This issue is basically derived from #1193 which I closed to keep tasks separated.

My guess is that the search algo is meant to entirely ignore certain types of words, like articles and prepositions (maybe more?), which looks undocumented and contradicts explicit expectations from a quoted query.

**Comment by meshuggahtas** [comment]
I've added another example, a two word, more than 5 letter example. The following formats for searching exact phrase should work if the search results would be correct:
"example string with multiple words"
example+string+with+multiple+words
example%string%with%multiple%words

So I assume the problem lies in the short number of letters in the "out of bound" phrase.

**Comment by vadosnaprimer** [comment]
I searched for `over the top` and it only searched for `top` so it's not because individual words are too short.

**Comment by meshuggahtas** [comment]
But that's what I'm saying. Out of bounds and Over the top are 3,2,6 and 4,3,3 letters. If you search for longer letter words like Forest Definitive 5,10, it gets so good results https://tasvideos.org/Search?SearchTerms=%22forest+definitive%22

**Comment by vadosnaprimer** [comment]
I mean `over` has more letters than `top` but gets skipped in favor of `top`.

**Comment by meshuggahtas** [comment]
I think I've found it. If the word consists fewer than 4 letters, the exact phrase search won't work.
Another working example with 3 words https://tasvideos.org/Search?SearchTerms=%22magic+discussion+thread%22

**Comment by Masterjun3** [comment]
Wrong. This is all wrong. Everyone, it's right there on the page:
![image](https://user-images.githubusercontent.com/22375320/159993590-f19be0c7-e8ba-4ce3-8d79-1c4d4745cd29.png)
You should read the documentation instead of making random claims about bugs.

**Comment by meshuggahtas** [comment]
Looks like you didn't read this post nor the original issue.

**Comment by Masterjun3** [comment]
The way our search works is by using the postgres tsvector and tsquery's. The ts stands for text search and is optimized for these kinds of text searches. Unlike exact matches like in Ctrl+F or regex or so, this takes the english language into account. So for example the text search 'The Fat Rats' gets reduced down to 'fat' and 'rat', removing the often used 'The' and turning the plural into singular [[doc](https://www.postgresql.org/docs/current/datatype-textsearch.html)].

This is how our search works, but this doesn't mean we can't add different types of searches.
This isn't a bug. This is how it works. *And all this is already linked right above the search field.*

But hey, apparently I'm the one who didn't read something.

**Comment by meshuggahtas** [comment]
According to Masterjun's comment, if the search works like that, **this issue which you have read is not a random claim**, which can be considered as a bug for the user or an enhancement request to let allow users do exact searches, depending on the point of view.

Here is a single word search example which shows the problem for trying to look exact phrases:
- Example: The search term "bounds"
- Observation: Will show results for bound, bounded and other bound variation, despite trying to search for only exact phrases.
- Link: https://tasvideos.org/Search?searchterms=%22bounds%22&pagenumber=2
- Result: On the 2nd page, you can see that **Mario Kart 64 | bound to that player and then it doesn't matter what place they are in - the shell** doesn't contains the term "bounds"
- Link of the wrong post result https://tasvideos.org/Forum/Topics/2970?CurrentPage=14&Highlight=173181#173181

**Comment by Masterjun3** [comment]
Closing in favor of #1197 which is more concise and has less bloat.
