### ISSUE TITLE
Support subtitles in userfiles

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#1200]
We often have to extract author's subtitles from the movie and to tweak it to be more readable, and then we use that in encodes. For posterity, to avoid having to extract them from encodes any time you want to reuse them, it would make a lot of sense to upload them to userfiles.

We need to support 3 subtitle formats:
- `srt` (doesn't allow formatting, but it's the only thing that works with mp4)
- `ass` (allows fancy styles but requires mkv)
- `ytt` (youtube's solution for fancy styles)

Not making a separate issue for each extension because hopefully it's just a matter of whitelisting those extensions, there's nothing to actually parse.

**Comment by adelikat** [comment]
Yes, currently file extensions are simply a whitelist, all 3 can be added easily

**Comment by Invariel** [comment]
Can we please pivot to allowlist or permitlist?

**Comment by adelikat** [comment]
I don't know what that means

**Comment by adelikat** [comment]
Decision: to make this list be read from a new system page: System/SupplamentalUserFileExtensions similar to how languages are done.  That way staff can control this list

**Comment by Invariel** [comment]
Supplemental.

**Comment by nattthebear** [comment]
> Not making a separate issue for each extension because hopefully it's just a matter of whitelisting those extensions, there's nothing to actually parse.

Don't userfiles have a temporal length?  Why aren't we parsing that?

**Comment by adelikat** [comment]
https://tasvideos.org/System/SupplementalUserFileExtensions created and the extensions requested here added, closing.
