### ISSUE TITLE
Allow referencing posts in quotes

### ISSUE THREAD

**Issue by scrimpeh** [TASVideos/tasvideos#1207]
Very minor thing but it'd be neat.

I would like it if quotes can optionally embed a link to the post they're from. If you hit the "Quote Post" button, it automatically inserts a reference to the post in the BBCode.

This could involve allowing quotes to refer to post IDs like `[quote=12345]` (will cause trouble since there exist users with purely numeric usernames), or creating a new BBCode tag for the purpose.

As for presentation of the quote, you can already get something pretty close to what I have in mind by doing this beautiful hack:
`[quote="[post=12345]user[/post]"]` which highlights the author name in the "user wrote" text and makes it link to the post. Maybe it'd be confusing if clicking that doesn't send you to their profile but the post though. Perhaps a small icon next to it could be used instead.

**Comment by nattthebear** [comment]
I'm not sure how the details would all work out, but I like this idea.

**Comment by Randomno** [comment]
The hacky way is very straightforward. Not sure about the proper way. I think the syntax `[quote="author" post="12345"] text [/quote]` would make the most sense, but it seems to be unlike any other forum syntax, so might not be very easy to implement (as least for me).

**Comment by vadosnaprimer** [comment]
I don't see a problem with making the Quote button simply do
```
[quote="[post=12345]user[/post]"]
text
[/quote]
```
instead of just
```
[quote="user"]
text
[/quote]
```

**Comment by Randomno** [comment]
For the same reason scrimpeh mentioned

> Maybe it'd be confusing if clicking that doesn't send you to their profile but the post though. Perhaps a small icon next to it could be used instead.

![image](https://github.com/TASVideos/tasvideos/assets/17330834/ced2d7d4-3cd3-4bac-b8a9-e062a45b24c8)

However, this would probably be fine:

![image](https://github.com/TASVideos/tasvideos/assets/17330834/62a4e963-bd33-409a-aa06-3bcef5b04d73)
