### ISSUE TITLE
Wiki engine: Embed .webp links as images

### ISSUE THREAD

**Issue by Masterjun3** [TASVideos/tasvideos#1210]
This is somewhat of a personal request. The .webp format does have at least one feature our currently supported image formats don't have.
(We also already use the format for some of our images, so it wouldn't be too far-fetched to allow it for wiki users as well.)

This may be the domain of @nattthebear . Is it as simple as just adding it to the array in MakeBracketed.cs?

**Comment by nattthebear** [comment]
I support this change.  Yes, it's as simple as adding an entry to `ImageSuffixes`.
