### ISSUE TITLE
April Fools text not appear on https://tasvideos.org/Profile/UserFiles

### ISSUE THREAD

**Issue by meshuggahtas** [TASVideos/tasvideos#1212]
Literally broken

edit: and sometimes I don't get it on Mobile Firefox. Tested main page and Search. It supposed to be under the menu, but for whatever reason it doesn't appears.

**Comment by SamsaraTAS** [comment]
Is there such a thing as negative priority?

**Comment by Masterjun3** [comment]
Duplicate of #1212.

**Comment by Masterjun3** [comment]
April Fools Day and the joke is over.
