### ISSUE TITLE
TimeZone problem on dates with hover-on text

### ISSUE THREAD

**Issue by meshuggahtas** [TASVideos/tasvideos#1220]
My profile timezone settings is UTC+1 but some dates shows me UTC+2 instead
- https://tasvideos.org/ UTC+2 on all Dates
- https://tasvideos.org/Profile UTC+2 on Wiki Last Edit, Wiki First Edit, otherwise UTC+1
- https://tasvideos.org/UserFiles UTC+2 on all Dates

**Comment by Masterjun3** [comment]
Your timezone setting is a location that is currently observing UTC+2.

**Comment by meshuggahtas** [comment]
And why do I get UTC+1 and UTC+2 dates depending on what page I'm seeing? There's definitely a bug.

**Comment by Masterjun3** [comment]
Because it was UTC+1 when the timestamp was made. Due to Daylight Savings Time it can switch between observing UTC+1 and UTC+2. We show dates with offsets as they happened. This is exactly working as intended.

**Comment by meshuggahtas** [comment]
Checked and Masterjun is right, working as intended. Educated myself on DST. Sorry!
