### ISSUE TITLE
TimeZone hover text for Submissions and Publications

### ISSUE THREAD

**Issue by meshuggahtas** [TASVideos/tasvideos#1221]
Feature Request: Adding same TimeZone hover on text to Submissions and Publications just like dates on other pages like the frontpage.

Currently, they don't give time zone information.

Examples:
- https://tasvideos.org/7233S Submitted by and bottom of the page Last edited by
- https://tasvideos.org/3358M Published on

**Comment by adelikat** [comment]
Are you saying there are places where hovering shows the timezone info? I'm not seeing that behavior

**Comment by Masterjun3** [comment]
The hover feature is part of the timezone taghelper. It's just the "title" of the span, and can be seen for example on the front page.
![image](https://user-images.githubusercontent.com/22375320/167306398-63a0d023-96f3-427a-bad9-a99ebfc30750.png)

The places where this hover doesn't work are probably those where the taghelper isn't used.
