### ISSUE TITLE
YouTube sync breaks if < or > are in the title and/or description

### ISSUE THREAD

**Issue by fsvgm777** [TASVideos/tasvideos#1222]
As it is, the YouTube sync breaks if either character is part of the title and/or description. This, however, is due to YouTube not allowing the characters at all. A workaround is to contextualise the usage of the character and re-write it (or replace with a different character while retaining the same meaning).

A proper fix would be to catch such a character and replace it with the full-width variant (so ＜ or ＞, compare to < or >) on the fly, as YouTube accepts those characters without issue.

**Comment by fsvgm777** [comment]
It should be noted that escaped versions of the characters (as in \< and \>) don't work and &gt; and &lt; just get rendered as-is, in text.

**Comment by nattthebear** [comment]
> escaped versions of the characters (as in \< and \>) don't work and > and < just get rendered as-is, in text.
Why do you think `\<` would serve as an escaped form of `<`?  Do you have documentation from Youtube about this?  I've never found anything concrete.

**Comment by fsvgm777** [comment]
I was told to try \\< and \\> out on Discord.

AFAIK, there's no documentation about the issue at hand on YouTube, except if you try it out yourself:

![image](https://user-images.githubusercontent.com/14264196/161816972-3b7eba4a-90df-47c0-bb97-cde769f85f80.png)

**Comment by Invariel** [comment]
She checked because I asked her over Discord if it would work, since escaping problematic characters is how we solve our problems in other situations.
