### ISSUE TITLE
Timezone differences appear to be calculated incorrectly

### ISSUE THREAD

**Issue by Noxxaa** [TASVideos/tasvideos#1225]
When displaying timestamps of e.g. forum posts, it is converted to the user's local time following the timezone set in their profile settings. However, this seems to be done incorrectly.

For example, [this post](https://tasvideos.org/Forum/Posts/511754) was made on 10:22 UTC:

![image](https://user-images.githubusercontent.com/5488449/162568347-e09d43f0-1fb2-443a-99f2-1793533e7b69.png)

And if I'm logged in and my local time is set to Asia/Kathmandu (UTC+05:45), it should display as 17:37, but it displays as 21:52 instead:

![image](https://user-images.githubusercontent.com/5488449/162568349-9974a287-e7e6-4fdc-a1ad-c94c8504ada0.png)

I went through various timezone settings to see what times I would get, and here's what I got:

* UTC: 10:22
* America/New York (UTC-05:00 + DST): 00:22
* America/Bogota (UTC-05:00): 00:22
* Europe/London (UTC+00:00 + DST): 10:22
* Europe/Amsterdam (UTC+01:00 + DST): 12:22
* Europe/Helsinki (UTC+02:00 + DST): 14:22
* Europe/Moscow (UTC+03:00): 16:22
* Asia/Baku (UTC+04:00): 18:22
* Asia/Karachi (UTC+05:00): 20:22
* Asia/Kolkata (UTC+05:30): 21:22
* Asia/Kathmandu (UTC+05:45): 21:52
* Asia/Almaty (UTC+06:00): 22:22
* Asia/Bangkok (UTC+07:00): 00:22 of the next day

Based on these tests, it seems that the UTC time difference is applied twice, and DST is not applied. This means that reported dates/times are incorrect for every timezone except UTC (and UTC+1 timezones during DST, if they observe it).

This was tested on forum post timestamps but it seems to apply to any case where a timestamp is posted.

**Comment by meshuggahtas** [comment]
Yes it looks like there is no handling of DST in the code @ https://github.com/TASVideos/tasvideos/blob/0a0f01854d92fdb914c43af679acdfecae20d456/TASVideos/TagHelpers/TimeZoneConvert.cs

Time zone overview at MS docs https://docs.microsoft.com/en-us/dotnet/standard/datetime/time-zone-overview

**Comment by Invariel** [comment]
The code should never explicitly handle DST.  The timezone library that is being used handles it, and we should all be thankful that it does.

The issue is more likely that somewhere in the pipeline we're converting a UTC time to a local time, and then elsewhere in the code we're taking that local time, treating it as if that were a UTC time, and converting it again to a local time.
