### ISSUE TITLE
MovieStatistics module does not have encode statistics built

### ISSUE THREAD

**Issue by MemoryTAS** [TASVideos/tasvideos#1226]
[The MovieStatistics page](https://tasvideos.org/MovieStatistics#FileData) has a section for encode related statistics. This section is currently filled will error messages since Noxxa was previously unable to build this prior to going live. If building this is considered unfeasible and/or undesirable, close this and let me know to remove all existing references to these parameters.

**Comment by adelikat** [comment]
Yeah, I think we need to remove all those.  We don't track that information in the database.  I wonder how many of them relied on the torrent as well.  Either way, we can live without them.

**Comment by MemoryTAS** [comment]
Good enough for me!
