### ISSUE TITLE
"Edit" buttons on /Addresses-List point to the wrong game

### ISSUE THREAD

**Issue by SandTAS** [TASVideos/tasvideos#1234]
At https://tasvideos.org/Addresses-List there are "View" and "Edit" links for each game. The "View" link works like I expect: it shows all the known addresses for the game. But "Edit" goes to a page for a *different* game—and it only displays *one* of that other game's addresses.

For example,

|Game|System||
|---|---|---|
|Barnstorming|A2600|[View](https://tasvideos.org/Addresses-1877) [Edit](https://tasvideos.org/RamAddresses/Edit/1877)|

The "View" link https://tasvideos.org/Addresses-1877 goes to ***Viewing RAM Addresses for A2600 Barnstorming***.

The "Edit" link https://tasvideos.org/RamAddresses/Edit/1877 goes to ***Editing RAM Addresses for FFAF53 (Genesis Chiki Chiki Boys)***.

Side note, I'm not sure what the "Edit" button is for. The "View" button takes me to a page where I can add, delete, and edit address entries, which covers all the editing operations I needed.

**Comment by meshuggahtas** [comment]
Address system is supposed to be obsoleted once https://github.com/TASVideos/tasvideos/issues/975 gets resolved which will also closes https://github.com/TASVideos/tasvideos/issues/544 which is the reason of this issue

**Comment by adelikat** [comment]
Fixed this by deleting the whole page, lol

Ram address feature is gone
