### ISSUE TITLE
Changing email address sets account to not be email confirmed but never sends new email

### ISSUE THREAD

**Issue by MemoryTAS** [TASVideos/tasvideos#1235]
locked out of my own account for changing my email lol

**Comment by adelikat** [comment]
We need to rework the email workflow to send a verification email, and only upon verification do we actually change it.  Should be a separate tab in the profile tab.  the userManager.ChangeEmail() method should be used

**Comment by adelikat** [comment]
This work was done, but I forgot to close the ticket
