### ISSUE TITLE
Playground: List playground movies for associated game on game pages

### ISSUE THREAD

**Issue by MemoryTAS** [TASVideos/tasvideos#1239]
Preferably should be listed below publications.

**Comment by vadosnaprimer** [comment]
Here's how I imagined this:

Below movies/branches we'd have another tab view, titled **Playground**, with tabs being branch labels of all PG submissions for that game. And inside each tab we would list all PG submissions belonging to that branch, sorted from shortest to longest.

That way it would resemble SRC leaderboards, which is kinda inspiration for this concept.
