### ISSUE TITLE
`sh` syntax is not recognized by prism.js

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#1246]
https://tasvideos.org/Forum/Posts/508418

The download button is there, but syntax is not highlighted, because prism expects `bash` instead of `sh`. So if we work around it by editing old code samples with download functionality, they will become `file.bash` which may not be desired.

**Comment by Masterjun3** [comment]
You probably want `shell` then.
While prism does just alias it to `bash` it's still closer to `sh`.
Of course the download would then be `file.shell`. If that's still undesirable we might need to look into custom prism aliases for these kinds of changes.

**Comment by vadosnaprimer** [comment]
Maybe they will merge a PR just like they did for avisynth https://github.com/PrismJS/prism/pull/3071

**Comment by nattthebear** [comment]
Our forum syntax expects the file extension to be the same as the prism alias.  Are there other situations where this is _not_ the case?

**Comment by vadosnaprimer** [comment]
Theoretically .py but it's nontrivial to find where it was used with the download option. For example I only found one without it https://tasvideos.org/Forum/Posts/475041

**Comment by vadosnaprimer** [comment]
`c++` has to be `cpp` to work.
