### ISSUE TITLE
Add "starts with letter" dropdown to https://tasvideos.org/Games/List

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#1249]
Currently showing the whole platform (paginated) is the narrowest it can go unless you just use the search. If we want the search to not be the only real option, we need to allow narrowing down the displayed list further.

I think if you can pick which letter the games should start with, most of the time you won't need to paginate the results, and paginating them makes navigation harder because you don't known where each letter is.

So I'm requesting a second dropdown with letters. Or maybe turn page numbers into letters? Probably harder to do.

With that change (and a couple more refinements) maybe that page will obsolete https://tasvideos.org/Games (and be moved there why not).

**Comment by adelikat** [comment]
I was thinking of an auto-complete box similar to Users/List

**Comment by vadosnaprimer** [comment]
It'd be fine but typing things should not be the only method of navigation IMO.

**Comment by adelikat** [comment]
Now that we have a search box, do we still want this?

**Comment by vadosnaprimer** [comment]
> typing things should not be the only method of navigation IMO.
