### ISSUE TITLE
Numeric System IDs are not listed anywhere on the site, yet are used in some modules

### ISSUE THREAD

**Issue by MemoryTAS** [TASVideos/tasvideos#1251]
There are numeric ids for the platforms the site supports but they are no longer listed anywhere on the wiki. Either a list (preferably a module) should be created that documents them, or all places that use them should be replaced with their written out equivalents.

**Comment by adelikat** [comment]
I'm working on some Game System crud pages that will resolve this

**Comment by adelikat** [comment]
/Systems is implemented which gives you this info
