### ISSUE TITLE
Forum Display Issue with BBCode Lists

### ISSUE THREAD

**Issue by scrimpeh** [TASVideos/tasvideos#1257]
[Post #421066](https://tasvideos.org/Forum/Topics/9624?CurrentPage=26&Highlight=421066#421066) doesn't display right. The original message posted contains the sequence `[*] [*] [*] [*] [*]` which is turned into a bullet point list, evne though there's no surrounding `[list]` tags.

On Firefox, these bullet points bleed into the user box. See attached image.

![image](https://user-images.githubusercontent.com/10942815/165810275-73bba589-18b2-4fe7-bfa5-72a63dc00631.png)

**Comment by vadosnaprimer** [comment]
![изображение](https://user-images.githubusercontent.com/7092625/165965535-c583fba2-1b29-46e6-acfb-d17b4c245f3f.png)

**Comment by nattthebear** [comment]
#1259

**Comment by adelikat** [comment]
Rolled back the fix that would fix this due to an NRE

**Comment by vadosnaprimer** [comment]
Still not fully fixed I guess https://tasvideos.org/Forum/Posts/513941

![изображение](https://user-images.githubusercontent.com/7092625/166141080-f95fe8f8-718d-4bb5-9167-371d7dfa6a94.png)

**Comment by nattthebear** [comment]
Uggg.  Yeah, we need a full testing suite for this.  Well, at least this bug is more subtle than the last one, I don't feel like a complete idiot.

**Comment by nattthebear** [comment]
#1268
