### ISSUE TITLE
Tell the streaming site on the publication page

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#1258]
https://tasvideos.org/1740M

One "Watch" button is for youtube, another is for nicovideo.

If we add an alt title, the latter will read "Watch nicovideo" which would look confusing, since the correct spelling is probably "Watch at nicovideo" or "Watch (nicovideo)".

But then the first button won't tell what we're about to watch at, and adding an alt title to that would put `[youtube]` in the video title on YT, which is not what we want.

As a result, we can't use alt title to tell the streaming site. What about adding the site in parenthesis at the end? Maybe only if there's more than one streaming site?

**Comment by adelikat** [comment]
This was done yesterday, didn't notice this ticket
