### ISSUE TITLE
Provide logs of changes to game pages

### ISSUE THREAD

**Issue by MemoryTAS** [TASVideos/tasvideos#1262]
Currently there isn't really a place to view a log of changes for a specific game entry. There are three different things that should be logged: description, details, and Game Versions lists. This should probably be done after #1188 is closed since I'd imagine that could break logs. Feel free to not include changes prior to the existence of said history pages if that would be too difficult (probably would).

**Comment by adelikat** [comment]
We now have history on game and game group tables, and a logs page that can filter by table and by individual row, for example:
https://tasvideos.org/Logs/Games/1786
