### ISSUE TITLE
Separate update feeds to Discord for wiki edits/posts/submissions

### ISSUE THREAD

**Issue by Noxxaa** [TASVideos/tasvideos#1267]
Currently all sorts of (public) updates are sent to one `#updates` channel in Discord. This can cause clogging issues with certain types of updates (see #1266)

It would be nicer if these were split into different channels, to make it easier to follow different types of updates. I can imagine many people would be interested in, say, new submissions, but not wiki edits or other such news.

I suggest the following category divisions:

* Forum updates (new posts, new topics, post edits)
* Submission updates (new submissions, submission status updates, new publications)
* Wiki/site updates (wiki edits, publication updates, catalog updates, everything else that's not one of the above)

(contact me on Discord if/when I need to create new channels for this)

**Comment by vadosnaprimer** [comment]
Duplicate? https://github.com/TASVideos/tasvideos/issues/731

**Comment by GMPranav** [comment]
Yeah those categories make sense, except maybe Publication updates as its own category? New publications, publication updates would go there.
