### ISSUE TITLE
GameGroup create attempt gives System Error

### ISSUE THREAD

**Issue by coolkirby2000** [TASVideos/tasvideos#1269]
GMP and I have both [tried](https://tasvideos.org/Forum/Posts/513851) to add a new GameGroup using [this page](https://tasvideos.org/GameGroups/List)'s Create button, but it redirects to a System Error page.

Can Editors be allowed to create Game groups? Alternatively, we could just ask staff to add them for us when needed, as so far we haven't needed new groups often.

**Comment by adelikat** [comment]
Fixed and deployed.
You have permissions to edit game groups, there was just a bug, you should be able to maintain these now
