### ISSUE TITLE
Allow Catalogging userfiles

### ISSUE THREAD

**Issue by coolkirby2000** [TASVideos/tasvideos#1270]
The [current plan](https://tasvideos.org/Forum/Topics/23255) is to link as many publications, submissions, and Userfiles to a Game as possible (with exceptions down the road for things like [general-purpose scripts](https://tasvideos.org/Forum/Posts/513960) and [nonexistent games](https://tasvideos.org/Forum/Posts/513944)).

To that end, staff and Editors should be able to Catalog userfiles, much like we Catalog submissions. This will make them much easier to find after they leave the Newest User Files/WIPs list, as userfiles don't turn up in search results (which could be a separate issue).

**Comment by meshuggahtas** [comment]
- Feature request ticket for searching userfiles https://github.com/TASVideos/tasvideos/issues/509
- Link to list userfiles without Game https://tasvideos.org/UserFiles/Game/-1 unfortunately doesn't works. https://tasvideos.org/-1G should have all those files without a game being catalogged
