### ISSUE TITLE
Review workflow

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#1272]
After some discussion I think that letting reviewers set submission status will result in a mess. We want reviews to happen regardless of whether a judge has claimed the submission or not, right? But if it's been claimed, do we want the reviewer to override that and set "under review"? After the review is done, do we want the reviewer to set it back to "judging underway" or "reviewed"? We kinda want both. And there should be no problem if several people review the same submission. Now that's when using the same status thing for everything can get really crazy. And I haven't even mentioned that judges can set several interim statuses!

To me it feels like we need review status to be independent from submission status. If something has been claimed, regardless of how many people are reviewing that movie, and how many people have already reviewed it, they won't mess with the primary judge claim.

What if they have an option to mark their post as a review underway/review completed, and then the submission page would parse and link those directly?

Mockup:

![изображение](https://user-images.githubusercontent.com/7092625/166986156-a4f9786f-2770-466c-958a-6c695a610e67.png)

And if someone has announced making a review but hasn't completed it, their name would be a text but not a link.

And for stats, we'd have a page of reviewers activity of some kind.

**Comment by MemoryTAS** [comment]
None of this seems really necessary to me at this time

**Comment by Invariel** [comment]
Publications are already reviewed.  That's how they become publications.  Why would we need/have/want a system that goes over existing publications to retroactively reject them?

**Comment by vadosnaprimer** [comment]
> Publications are already reviewed. That's how they become publications. Why would we need/have/want a system that goes over existing publications to retroactively reject them?

For publication, I didn't mean reviews as a part of (re)judging, but as an addition to user ratings. Like reviews of real-world movies.

**Comment by MemoryTAS** [comment]
That's a different kind of review and out of scope for the moment.

**Comment by vadosnaprimer** [comment]
> None of this seems really necessary to me at this time

As in "not yet", or as in "no we won't ever want tracking reviews to be automated"?
