### ISSUE TITLE
UI for replacing primary movie file

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#1273]
https://creativecommons.org/licenses/by/2.0/legalcode

> If You create a Collective Work, upon notice from any Licensor You must, to the extent practicable, _remove from the Collective Work any reference to such Licensor or the Original Author, as requested_. If You create a Derivative Work, upon notice from any Licensor You must, to the extent practicable, _remove from the Derivative Work any reference to such Licensor or the Original Author, as requested_.

If a user asks for their credit to be removed from our files, under CC-BY we need to erase it. Which includes filenames of movie files we host directly. Not a problem with encodes since we can replace them freely.

Also often people just change their usernames and we have the infrastructure to support it, aside from movie filenames. Sounds fitting too.

**Comment by adelikat** [comment]
We have a database column, that controls the name of the zip file.  However, that does not control the name of the file itself inside the zip.  Also what about the header inside the movie file? And each file type we support is different.  How much of this needs to be UI controlled?

**Comment by vadosnaprimer** [comment]
Looks like we need to be able to just replace the file itself, like for submissions, by uploading a replacement.

**Comment by adelikat** [comment]
After discord discussion it was concluded that all of this needed to be ui controlled. It isn't as simple as renaming the column in the database because it is baked into the binary.  A proper ui would allow replacing the binary and filename.
