### ISSUE TITLE
Feature Request: Ban information on user profile

### ISSUE THREAD

**Issue by Noxxaa** [TASVideos/tasvideos#1286]
Requesting for a field in an user's profile where moderators can place information about an user's ban status (reason, duration, etc). Should be just a simple text field.

This field should only be visible if an user has the Banned User role. If no information is placed, it should have a generic "no ban information available" line instead.

This is so moderators can give explanations about bans or durations (both for private and public purposes), without having to maintain a list or otherwise giving banned users undue attention.

Ideally this information is also made visible in some way to the banned user themself if they try to access the site. Currently banned users have no clear way on the site to know why they are banned or how long, if applicable.

**Comment by meshuggahtas** [comment]
Relevant issue suggestion: Please make an issue for disabling sending emails (forum notification for example) to permanently banned users to preserve resources.

**Comment by adelikat** [comment]
Implemented by https://github.com/TASVideos/tasvideos/pull/1369
