### ISSUE TITLE
Benchmark Pre-rendering forum posts

### ISSUE THREAD

**Issue by adelikat** [TASVideos/tasvideos#129]
Right now we store the markup and then render posts on the fly.  The renderer isn't slow but that time does add up.  Instead we could render on post save, to an additional db column and read from there when displaying them.

In theory this is a big speedup to forum pages.

**Comment by adelikat** [comment]
It's unclear if this is a necessity to support production level usage, or just a nice to have.  For now, putting in the 2.0 release milestone just in case. We should at least evaluate the necessity of it by then.

**Comment by vadosnaprimer** [comment]
Posts ever change almost never so it's a great idea.

**Comment by nattthebear** [comment]
Do we have any profiling mechanism for the production site?  I'd be surprised if something as simple as bbcode parsing took that much effort.

**Comment by adelikat** [comment]
Kicking the can on this more.  It is worth profiling and then seeing if this idea has any meaningful benefit, at some point.  But the forum is performant enough.

**Comment by adelikat** [comment]
Updating title to better reflect next steps.  We need to do some benchmark tests and assess the potential performance boost for doing this approach.  Depending on results it may or may not be worth the extra code complexity.

**Comment by adelikat** [comment]
I think this no longer makes sense, because there is dynamic data now, originally all markup could be statically rendered.  Also, we have had no performance issues with the current design

Closing
