### ISSUE TITLE
First indentation inside the code tag is ignored

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#1290]
https://tasvideos.org/Forum/Posts/457013

The first line has a space at the beginning but it's not displayed by the code embed module. In that particular example it's harmless, but with actual code it can be annoying especially when a whitespace is meant to be there.

**Comment by nattthebear** [comment]
Hmm, people write tags like that?  I figured they'd do this instead, which does work:
```
[quote="feos"]
[code]
 Warepire	People ask me for my help all the time.
 Warepire	Some days I don't work on my own things at all
 Nach		 Warepire: then you're a lead 
 Warepire	Nope, because I don't do any of the lead programmer roles, like govern the issue tracker, decide what people work on, status summaries of projects to the manager etc
 Nach		 Warepire: okay then, you're a partial lead 
 Nach		 sometimes certain roles are split or combined
 Warepire	That I can agree on
 feos		 a partial lead. the one who partially leads.
 Warepire	50% lead, 50% other metals
 Warepire	Like heavy metal, speed metal, thrash metal, power metal, prog metal, death metal
 feos		 lol
[/code]
[/quote]
```

**Comment by vadosnaprimer** [comment]
Yeah when you have a block of text, you select it starting right before the first char **at** the first line, then you hit the UI button to add the code tag, so there's no linebreak before the first line. It would have to be added manually every time.
