### ISSUE TITLE
"Branch override" for game pages

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#1297]
Since each branch within the same game is shown in a tab, there are cases when different game versions were published but they have the same branch label (or none). Best examples

https://tasvideos.org/294G

![изображение](https://user-images.githubusercontent.com/7092625/170520009-6fb3d2f1-ea80-476a-8bf9-8cb6b4d03672.png)

https://tasvideos.org/1466G (my favorite game, it's always a good example of some missing feature)

![изображение](https://user-images.githubusercontent.com/7092625/170520156-bd0fc3e6-33c6-4ff1-97e5-f4e84a4fa6cb.png)

We have "title override" but it won't appear in those tab names, and it shouldn't, since it's a different entity with a different purpose. So instead we need "branch override" to be able to tell that some movies are there not because they have different goals, but because they showcase different versions of the same game.

I don't know if overridden branch should replace `(baseline)` or get appended to it.

Also I don't think we can automatically use game version for that, since game version is a complex entity, and may consist of region, numeric release version, and maybe a different game title altogether, and any of those can co-exist as a separate branch.

**Comment by YoshiRulz** [comment]
Discussed further in #1318, and then fixed by https://github.com/TASVideos/tasvideos/commit/d91a7cfe473db01fa789c9d0ad9e13ef65a223ad.
