### ISSUE TITLE
Game Relations info

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#1298]
The old site kept lots of Relations info. Was it dropped upon migration or is it still kept hidden?

![изображение](https://user-images.githubusercontent.com/7092625/170522743-89e93cac-e546-4eff-9737-11bd3baa92e7.png)

![изображение](https://user-images.githubusercontent.com/7092625/170522908-68ce36ba-912b-4836-bd95-fdde3f2bc582.png)

**Comment by adelikat** [comment]
We didn't keep any of that, sorry

**Comment by vadosnaprimer** [comment]
Okay so at the very least a way to connect hacks to their base game will need to be reimplemented.

**Comment by adelikat** [comment]
I'd like to think of the ideal design here, that accounts not just for hacks

**Comment by adelikat** [comment]
Closing in favor of ticket: https://github.com/TASVideos/tasvideos/issues/1310
We need a broader discussion how we want to group games, and I do not want to be hampered by what we had before
