### ISSUE TITLE
Forum tag buttons color in light mode

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#1299]
At some point a cyan color was introduced for some elements on the site, and it looks cool in the dark mode

![изображение](https://user-images.githubusercontent.com/7092625/170568912-c6a3a9d6-7f77-4d13-af44-54540d0e69b1.png)

But in the light mode the text on cyan buttons is black, which makes it VERY hard to read for me, because button BG is much darker than the rest of the site, and the text is also black. Maybe if the entire BG was cyan, it would have been easier to read the text. But it's even more confusing for the eye right nearby the white text buttons where everything is ideally readable.

![изображение](https://user-images.githubusercontent.com/7092625/170569490-4e1fe372-69b4-4c4a-aa9f-dce9484b15d3.png)

Same issue is with these cyan buttons

![изображение](https://user-images.githubusercontent.com/7092625/170569778-f556341f-305c-4ac3-a271-0e8cb9977837.png)

IMO text on those buttons should be made white.

**Comment by nattthebear** [comment]
Contrast in light mode https://webaim.org/resources/contrastchecker/?fcolor=212529&bcolor=0AA3C2
Contrast in dark mode https://webaim.org/resources/contrastchecker/?fcolor=F8F9FA&bcolor=0AA3C2

It seems to be a hard color to contrast with :shrug:

**Comment by vadosnaprimer** [comment]
Is there a way to check it considering page BG? It makes most of the difference imo.

**Comment by TiKevin83** [comment]
not really, the wcag AA standards go off element foreground/background. Would probably be best to make the shade of blue darker in light mode to enable flipping the foreground color to light. As is the contrast is worse with light text.
