### ISSUE TITLE
Wiki links: ignore spaces for chapters/headers

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#1312]
`[Movie Rules #GameChoiceInGeneral]` showcases the issue.

You can have a space in the link to a wiki page, and it's ignored when composing the actual link, so it remains valid. But if you add a space a header link, it will be kept and will not be able to link to the actual header because working header links don't have spaces.

So the desired effect is `[Movie Rules # Game Choice In General]` being a working link too.

**Comment by MemoryTAS** [comment]
I dunno if this exactly matters. Linking to a specific chapter/header without providing an alternate name through a pipe looks really ugly and sorta confusing to a reader who isn't familiar with the formatting already. What does # mean to a viewer who doesn't know the syntax? One should always use `[Page#Header|title of link]` anyway I feel.
