### ISSUE TITLE
No way to distinguish between publications with the same branch name but different versions on game page

### ISSUE THREAD

**Issue by MemoryTAS** [TASVideos/tasvideos#1318]
Example is https://tasvideos.org/294G
![image](https://user-images.githubusercontent.com/6119096/171388017-44b1a75c-bb7c-45ca-952a-44970a24edf6.png)

**Comment by adelikat** [comment]
I could put the version name there when branch is empty but it would have to be filled out...
![image](https://user-images.githubusercontent.com/1679846/177198063-67c3083c-0641-4395-ab0d-900124d8de78.png)

**Comment by Masterjun3** [comment]
What I planned for this was this:
Show only branches.
If two branches are the same, show game title with branch (or just game title if branch is empty). And the game title is of course just the game name or the override from the version.

**Comment by vadosnaprimer** [comment]
For https://tasvideos.org/1466G how will it look?

`Tenchu: Stealth Assassins (USA) | Tenchu: Stealth Assassins (Japan)` or just `(USA) |  (Japan)`?

**Comment by Masterjun3** [comment]
The first one. It will look good for most cases.
Making it more concise is a lower priority issue that can be done in the future, it requires a lot more work because you need an additional Publication column in the db.
