### ISSUE TITLE
Move Games out of Admin tab on navbar

### ISSUE THREAD

**Issue by MemoryTAS** [TASVideos/tasvideos#1320]
Games should be prominently next to or before "Movies". "Staff" can be moved under "About".

**Comment by vadosnaprimer** [comment]
I vote for "before movies".

**Comment by adelikat** [comment]
So, did we settle on "before movies" ? this is super easy, just need to know which one to do

**Comment by MemoryTAS** [comment]
Before. Also change any associated privileges that cause the admin tab to appear to editors.
