### ISSUE TITLE
Move Papers, Please from Unsupported Games to Working Games

### ISSUE THREAD

**Issue by LukeSaward1** [TASVideos/tasvideos#1325]
Recent commits in libTAS have allowed for Papers, Please to work in it. Thus, it should be moved from Unsupported to Working on the [Game Compatibility](https://tasvideos.org/EmulatorResources/LibTAS/GameCompatibility) page.

**Comment by CasualPokePlayer** [comment]
This issue tracker is for the actual site code, not wiki pages which may be editted by anyone with the proper perms (Editors I believe have perms here?)
