### ISSUE TITLE
Add PC-98 system

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#1326]
https://tasvideos.org/7475S uses Hourglass to TAS an emulator - [Neko Project 21](http://nenecchi.kirara.st/#PC-98). We're also looking into supporting its Linux version in libTAS.

Exact framerate is `1000000000 / 17723226`, but Hourglass doesn't support that, and the above movie just uses 60. Manual override is an option, since automatically detecting what application Hourglass was running from the movie is not always reliable. So it's kinda okay to rely on the fps value in the movie, .wtf or .ltm.

Setting the platform for Hourglass movies is going to remain manual I suppose.

**Comment by adelikat** [comment]
Closing this ticket in favor of #993 which will actually allow an admin to do this work without a code ticket

**Comment by Masterjun3** [comment]
In addition to framerate, we also need to manually adjust the parsers and the [hardcoded system code list](https://github.com/TASVideos/tasvideos/blob/a3c57c260d70367a1c42d815de71b8f88d9afb18/TASVideos.Parsers/SystemCodes.cs) the parsers use.
Reopening, since the fps ticket wouldn't be enough.

**Comment by vadosnaprimer** [comment]
Note: libTAS is the only movie format where we can specify framerate as well as the platform, so its parser is what we need to update. HG one wouldn't help.

**Comment by CasualPokePlayer** [comment]
Resolved by https://github.com/TASVideos/tasvideos/commit/0252daa764e376af18f8caf85ec8e2eea7dbdc14
