### ISSUE TITLE
Remove Search Key from Game Entries

### ISSUE THREAD

**Issue by MemoryTAS** [TASVideos/tasvideos#1332]
Does this even do anything anymore? It used to determine the url but that was on old site. It's annoying to fill out for something that has no apparent effect.

**Comment by adelikat** [comment]
Currently the SearchKey field values are added as tags in youtube during a youtube sync.  I'd be happy to get rid of that, especially since I don't think tagging helps too much with the youtube algorithm these days.

**Comment by vadosnaprimer** [comment]
Added alongside the actual youtube tags field? I think having only 1 is okay.

![изображение](https://user-images.githubusercontent.com/7092625/173178260-58cc0e32-d22d-4580-89fb-6c77465cd2e0.png)

**Comment by adelikat** [comment]
Yeah, believe it or not Search Key is used and youtube tags is not...
At the very least we should fix that and use the youtube tags field.  But I'd also suggest maybe we remove both.

**Comment by vadosnaprimer** [comment]
>At the very least we should fix that and use the youtube tags field. But I'd also suggest maybe we remove both.

I'd prefer repurposing it a but, but it would be a different issues.

**Comment by adelikat** [comment]
You would prefer repurposing the Youtube tags field? That's a very specific field

**Comment by adelikat** [comment]
So, as of right now we do not use the youtube for search key fields.  But what do we want to decide to do?
I need to know for 
SearchKeys -> use in urls like before, or delete
YoutubeTags -> rename and use in game searches, or delete

**Comment by vadosnaprimer** [comment]
IIRC search key simply repeats the game name, while yt tags are filled with partial matches in mind and have more useful into. I'd drop search keys and repurpose yt tags.

**Comment by adelikat** [comment]
Done
