### ISSUE TITLE
Youtube descriptions now have broken links

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#1334]
When we have a wiki link in the pub description, it gets posted on yt as `text (URL)`. Some time ago yt started including `)` into the URL itself, so all those links are broken now.

Example: https://www.youtube.com/watch?v=I2WCEUu7Ilo links to `https://tasvideos.org/7498S)` instead of `https://tasvideos.org/7498S` (github explicitly ignores the `)` so I can't even create such a broken link here lol).

**Comment by nattthebear** [comment]
In the example you gave, why does the author link work?

**Comment by vadosnaprimer** [comment]
Maybe yt shortens the link in that case without including the `)`.

**Comment by Masterjun3** [comment]
I copied the entire description into one of my videos and I couldn't replicate the issue, on my video the links for fine.

However, it would probably make sense to change the code to avoid putting symbols after links, and instead put a space, so like
`author's notes ( https://tasvideos.org/7498S ).`

**Comment by despoa** [comment]
Just want to point out that even YouTube viewers are noticing this bug now, as shown this video's comments section.

https://www.youtube.com/watch?v=O2cN7jshryY
