### ISSUE TITLE
I can't edit a submission even though I'm a judge

### ISSUE THREAD

**Issue by ThunderAxe31** [TASVideos/tasvideos#1342]
I tried applying a minor edit to a submission, accepted by another judge, that's currently Publication Underway, and I got this:

![image](https://user-images.githubusercontent.com/36802254/174274043-504c1925-c366-499d-a4b5-a820b12f6ad6.png)

The edit consists only in changing some characters in the submission text, without touching the other forms.

**Comment by Masterjun3** [comment]
The issue might be here in the code:
https://github.com/TASVideos/tasvideos/blob/232ed2ee95fe6acd943eed53130e36bf6bf42400/TASVideos/Pages/Submissions/Edit.cshtml.cs#L162-L167

I'm not quite sure about the purpose of that code, but it nulls the publication class when a non-judge is editing a submission. Which means once a judge edits a submission afterwards, they get an error about a missing field.

**Comment by SamsaraTAS** [comment]
Pretty sure #1073 is the same issue
