### ISSUE TITLE
Whole discussion thread marked as edited when submission status is changed

### ISSUE THREAD

**Issue by brunovalads** [TASVideos/tasvideos#1343]
I noticed that when @MemoryTAS claimed [5335S](https://tasvideos.org/5335S) to rejudge it all the posts in its [thread](https://tasvideos.org/Forum/Topics/18679) were marked as "Edited:", with the same timestamp as the claiming. Is this intentional?

**Comment by adelikat** [comment]
This is NOT intentional, no

**Comment by brunovalads** [comment]
I noticed not only changing "Rejudged" but to "Published" as well affect previous posts, so I assume any submission status change has this bug.

**Comment by adelikat** [comment]
Note that this was fixed for future submissions, but there is no easy way to back-fix effected submissions except through manual intervention.
