### ISSUE TITLE
[TAStudio] Rerecords do not count if working with analog controls

### ISSUE THREAD

**Issue by EZGames69** [TASVideos/tasvideos#1344]
So I was working with the recent bizhawk dolphin build forked by CasualPokePlayer and noticed my re-record count was low, it turns out this is because the rerecord counts only work when changes to inputs happen, but not changes to Analog controls, when working in TAStudio

**Comment by CasualPokePlayer** [comment]
Wrong issue tracker.

**Comment by EZGames69** [comment]
oops
