### ISSUE TITLE
Button to view referrers for generated non-wiki pages

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#1350]
Example https://tasvideos.org/Wiki/SiteMap has no way to view referrers from UI unless you hack around it by editing the URL to go to https://tasvideos.org/Wiki/Referrers?path=Wiki/SiteMap which happens to work fine, just like with #1250

So the info is there, and we need it every once in a while when unorphaning (adopting?) some new page that needs to be advertised.

**Comment by vadosnaprimer** [comment]
I mean it would be ideal to now show the button twice for actual wiki pages

![изображение](https://user-images.githubusercontent.com/7092625/177042759-6f3e835c-54bd-4a6c-b550-d5eb9c5e8a3c.png)

**Comment by adelikat** [comment]
What page is that? there is code to not show it twice, and if you notice things like the homepage it does not

**Comment by vadosnaprimer** [comment]
https://tasvideos.org/7532S
