### ISSUE TITLE
Link to latest diff in IRC/Discord bot posts

### ISSUE THREAD

**Issue by Randomno** [TASVideos/tasvideos#1353]
When I see in #updates that a page has been edited I'm most interested to know what has changed since the last revision.

Example, but could look nicer:
![image](https://user-images.githubusercontent.com/17330834/177057910-50c0b79d-939f-4b77-acfe-d90d0f6bca36.png)

**Comment by adelikat** [comment]
To be fair, it's only 1 more click to get to that diff

**Comment by vadosnaprimer** [comment]
If you're not quick enough, latest edit may not be what you want anymore. For example if there are several edits or of a few minor ones were slapped on top (no notifications, also usually some useless tweak).

**Comment by adelikat** [comment]
Closing this for reasons brought up.  I think the convenience is minimal since it only saves 1 click (latest diff is on the page it links to), but can be problematic, especially for IRC and can even not be the link you were looking for.

I think the complexity increase isn't worth the gain for this one

**Comment by Randomno** [comment]
Now Discord supports Markdown links, this could be done more succintly:

> Page SandBox edited by Randomno https://tasvideos.org/SandBox ([diff](https://tasvideos.org/Wiki/PageHistory?path=SandBox&fromRevision=38&toRevision=39))

Or even

> Page [SandBox](https://tasvideos.org/SandBox) edited by [Randomno](http://tasvideos.org/Users/Profile/Randomno)  ([diff](https://tasvideos.org/Wiki/PageHistory?path=SandBox&fromRevision=38&toRevision=39))

Though the latter would more be a new issue for updating our bot posts for Markdown links. Obviously this wouldn't work with IRC either.

**Comment by vadosnaprimer** [comment]
Linking the user is overkill since it's already there on the diff page.
