### ISSUE TITLE
Accidentally hitting enter while writing wiki edit description submits the changes

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#1376]
`'` is right near Enter for me, and there's no way to redo the edit description, so I think it would be a good idea not to have a hidden feature of submitting the edit when certain keys are hit (barring cases when someone has a certain button selected via keyboard maybe).

**Comment by nattthebear** [comment]
>I think it would be a good idea not to have a hidden feature of submitting the edit when certain keys are hit

FYI this is a standard browser feature, and has been the way all browsers worked for all standard `<form>`s forever.  Vanilla JS example that will likely work in every browser back to IE 4 or something:  https://jsfiddle.net/ucaxsg9n/
