### ISSUE TITLE
[user:x] for non-existent users

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#1388]
https://tasvideos.org/TextFormattingRules/ListOfModules#User

This module is used all over the movies and submissions, for editors self-referencing, as well as 3rd person references to TASers. It was used so broadly because simply writing `[username]` would only be a valid link if that user had a homepage and they haven't yet had a username change. So unless there is such a user homepage, `[user:username]` would not turn into a wiki link, to avoid having a broken one (broken links were shown in red color previously).

Specifically for 1st person references, it was strongly advised to use the module (which I'm guilty of ignoring because it's too much repetitive hand-writing for how much I have to add it), because if the editor's name does change in the future, having to go back and manually fix all the broken homepage links would have been a crime to cause, especially for those who put it on hundreds of pages.

For TASers, we used it also in case someone without a homepage will eventually create one, and the link will start working.

So on the new site, if the user link leads to 404, it's still parsed and visually it's the same as other links, so the user clicking on it is not aware it's broken.

This issue is for discussing what can be done about this.

One solution is showing all broken links in a different color (red?) and so non-existent users would appear as red links. Another is not parsing links non-existent users as links at all. Maybe there's something else, but I don't know how feasible it would be.

**Comment by MemoryTAS** [comment]
Just don't use [user:username] if a user doesn't exist. Go back and add it later if it matters imo.

**Comment by adelikat** [comment]
I agree with @MemoryTAS here

**Comment by vadosnaprimer** [comment]
That doesn't help with people changing their nicknames, especially for self links by staff, that can appear in hundreds of submissions. As I said, the problem is

> if the user link leads to 404, it's still parsed and visually it's the same as other links, so the user clicking on it is not aware it's broken

broken links looking like working links. If I stop using the module for non-existent users, none of that gets fixed by itself. Even if we have a script that fixes all of those at some point.

**Comment by adelikat** [comment]
I also want to point out that there is no way to know if the link will work without doing a database lookup, is the performance cost worth it?

**Comment by vadosnaprimer** [comment]
I don't think we have any wiki pages with hundreds of internal links on them, and specifically for user module, there would only be a few on a human written wiki page.

**Comment by adelikat** [comment]
It doesn't take hundreds to cause a performance issue.  Trips to the database are expensive, and there is no sane way to make one trip for any users, it would have to be one at a time for each link on the page.

**Comment by adelikat** [comment]
I'm not seeing much support for this, and I don't think it is worth the extra processing necessary to pre-determine if a profile name is valid. Closing.
