### ISSUE TITLE
Selecting game in userfiles

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#1391]
When picking a game for a userfile, if one has already selected the system, game choice should become limited to just that system. Since system is not displayed in that dropdown (yet), if there are several games with the same name but on different systems, it becomes very annoying to figure out which is the one you need (they are not ordered by system either).

**Comment by Masterjun3** [comment]
Can't reproduce the problem. For me, it works fine as expected.

![image](https://user-images.githubusercontent.com/22375320/183101023-3a69c415-a2eb-4490-8c0a-f4195b0c1c74.png)

In what situation in particular does this problem occur to you? Maybe there is a missing javascript call somewhere.

**Comment by vadosnaprimer** [comment]
I think it's only limiting them to a system right after you've just changed it. If you simply open a userfile with a system already set, it will show all games.
