### ISSUE TITLE
Add wiki helper buttons for post and topic

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#1397]
If we don't want absolute internal links, and there will be no bot replacing them with short internal links upon edit (like on the old site), we need buttons for those short links, because after you copypaste the post link you have to manually shorten it every time, and there's no way to only copy the needed part from anywhere (topic link can be copied partially from any thread URL but it'd still be very nice to just have a button).

**Comment by adelikat** [comment]
Did the old site automatically fix your absolute links to relative??

**Comment by Masterjun3** [comment]
I mean look at all those "Fixed links"! https://tasvideos.org/Wiki/EditHistory/TASVideoAgent
![image](https://user-images.githubusercontent.com/22375320/183707966-47d82485-edde-4a4f-a785-aee30baec9ae.png)
