### ISSUE TITLE
Nynashock GunCom with mouse is still buggy.

### ISSUE THREAD

**Issue by ThunderAxe31** [TASVideos/tasvideos#1402]
1) Set GunCom as controller for PSX
2) Set the mouse movement as input for analog
3) Move the aim close to the center of screen. The crosshair will move funny and tend to lock on the center. It makes it impossible to play normally.

**Comment by adelikat** [comment]
@ThunderAxe31 : I believe you meant to report this in the BizHawk repo

**Comment by YoshiRulz** [comment]
I believe this is the same as TASEmulators/BizHawk#3359.
