### ISSUE TITLE
IRC bot is silent since aug 25

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#1406]
Its last words were

```
[08:55:54] <TASVideoAgent> New Post by dekutony (SNES: Super Punch-Out!!) https://tasvideos.org/Forum/Posts/516243
[08:58:01] <-- Umbire (~UmbireThe@user/umbire) has quit (Ping timeout: 255 seconds)
[09:00:16] <-- TASVideoAgent (~TASVideoA@69-63-32-35.ded.execulink.com) has quit (Ping timeout: 255 seconds)
[09:00:48] --> TASVideoAgent (~TASVideoA@69.63.32.36) has joined #tasvideos
```

Note that it rejoined from an IP that belongs to the legacy site.

**Comment by adelikat** [comment]
Here is the exception that is happening: 


"ex": "System.IO.IOException: Unable to write data to the transport connection: Connection timed out.\n ---> System.Net.Sockets.SocketException (110): Connection timed out\n   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)\n   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.SendAsyncForNetworkStream(Socket socket, CancellationToken cancellationToken)\n   at System.Net.Sockets.NetworkStream.WriteAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)\n   at System.IO.StreamWriter.<FlushAsyncInternal>g__Core|76_0(Boolean flushStream, Boolean flushEncoder, CancellationToken cancellationToken)\n   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)\n   at System.IO.StreamWriter.FlushAsync()\n   at TASVideos.Core.Services.ExternalMediaPublisher.Distributors.IrcDistributor.IrcBot.ConnectToServer() in /home/tasvideos/tasvideos/TASVideos.Core/Services/ExternalMediaPublisher/Distributors/IrcDistributor.cs:line 129\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)\n   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)\n   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)\n   at System.Threading.Tasks.Task.DelayPromise.CompleteTimedOut()\n   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)\n   at System.Threading.TimerQueue.FireNextTimers()\n   at System.Threading.UnmanagedThreadPoolWorkItem.ExecuteUnmanagedThreadPoolWorkItem(IntPtr callback, IntPtr state)\n   at System.Threading.UnmanagedThreadPoolWorkItem.ExecuteUnmanagedThreadPoolWorkItem(IntPtr callback, IntPtr state)\n   at System.Threading.UnmanagedThreadPoolWorkItem.System.Threading.IThreadPoolWorkItem.Execute()\n   at System.Threading.ThreadPoolWorkQueue.Dispatch()\n   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()\n--- End of stack trace from previous location ---\n\n   --- End of inner exception stack trace ---\n   at System.IO.StreamWriter.<FlushAsyncInternal>g__Core|76_0(Boolean flushStream, Boolean flushEncoder, CancellationToken cancellationToken)\n   at TASVideos.Core.Services.ExternalMediaPublisher.Distributors.IrcDistributor.IrcBot.ConnectToServer() in /home/tasvideos/tasvideos/TASVideos.Core/Services/ExternalMediaPublisher/Distributors/IrcDistributor.cs:line 129\n   at TASVideos.Core.Services.ExternalMediaPublisher.Distributors.IrcDistributor.IrcBot.ConnectToServer() in /home/tasvideos/tasvideos/TASVideos.Core/Services/ExternalMediaPublisher/Distributors/IrcDistributor.cs:line 94\n   at TASVideos.Core.Services.ExternalMediaPublisher.Distributors.IrcDistributor.IrcBot.ConnectToServer() in /home/tasvideos/tasvideos/TASVideos.Core/Services/ExternalMediaPublisher/Distributors/IrcDistributor.cs:line 94\n   at TASVideos.Core.Services.ExternalMediaPublisher.Distributors.IrcDistributor.IrcBot.Loop() in /home/tasvideos/tasvideos/TASVideos.Core/Services/ExternalMediaPublisher/Distributors/IrcDistributor.cs:line 152",

**Comment by adelikat** [comment]
This was resolved.  The issue was that the old version was unintentionally running on an old server
