### ISSUE TITLE
Forums - Unread post icons should navigate to the unread post

### ISSUE THREAD

**Issue by adelikat** [TASVideos/tasvideos#1429]
This was a behavior in standard phpbb2 forums that is not present in our current forums.  And this was a feature that has been requested but no issue was made.

(Currently it isn't very feasible but we need to document the request)

**Comment by Masterjun3** [comment]
Note, it needs to be considered that with multiple unread posts, it needs to take you to the *first* unread post, which could potentially be on a different page than the latest post.
