### ISSUE TITLE
Replace http archive.org links with https

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#1432]
Example: `A/V file via Mirror` links in https://tasvideos.org/3124M

Sometimes the browser will refuse to download from such a link, saying it's a potential threat, and you will have to allow the download manually. I don't know what makes it happen again after you've allowed it once, and it works for some time, but then resets again.

After archive.org has moved to https, its links work both ways, so most new publications have https mirror links, but I was unable to determine when it started.

Of course it's not hardcoded, and there's probably no code to change here, but it'd still be more convenient if it was https at all times.

**Comment by adelikat** [comment]
Done, update all publication urls to be https
