### ISSUE TITLE
Specific Transparent PNG and GIF are distorted

### ISSUE THREAD

**Issue by meshuggahtas** [TASVideos/tasvideos#1434]
I saw some specific transparent PNGs and GIFs are displayed on the site with seemingly heavy outline, distorting the image to nearly unrecognizable. I don't know the reason behind the problem, because I also saw correctly displayed transparent PNGs and GIFs.

Windows 10, Firefox, no visual plugins (DarkReader) activated.

# 1
- https://tasvideos.org/Forum/Topics/2820?CurrentPage=127&Highlight=509473#509473
- Screenshot:
![1tas](https://user-images.githubusercontent.com/31288337/193789611-a089a775-d17a-4b2d-a058-6068de8fd813.PNG)
- GIF: https://latex.codecogs.com/gif.latex?%5Cfrac%7B1%7D%7B%5Cphi%7D%5Cint_0%5E%5Cinfty%20%5Cfrac%7Bu%5E%7B%5Cphi-2%7D%7D%7B%281&plus;u%29%5E%5Cphi%7D
- Same image screenshotted while 
only displaying it on a new page:
![1](https://user-images.githubusercontent.com/31288337/193789313-9d3feb45-2e00-407f-a3c8-5f6831193dca.PNG)

# 2
- https://tasvideos.org/GameResources/NES/MetalForce?revision=7
- Screenshot: 
![2tas](https://user-images.githubusercontent.com/31288337/193789671-426c45d8-c268-4ce5-befa-22800dc9fc8d.PNG)
- PNG: http://upload.wikimedia.org/math/0/f/3/0f36df929ac9d711a8ba8c5658c3bfee.png
- Same image screenshotted while only displaying it on a new page:
![2](https://user-images.githubusercontent.com/31288337/193789364-1870febc-e457-4b6d-981e-e534b1ed3c33.PNG)

**Comment by vadosnaprimer** [comment]
Only looks like a problem in dark mode. I guess it's just how latex makes those images, we can't change that.

**Comment by YoshiRulz** [comment]
Workaround:
```csharp
img[src^="https://latex.codecogs.com/gif.latex"] {
    filter: invert();
}
```

**Comment by TiKevin83** [comment]
or to integrate with the dark mode `bg{black}`
https://latex.codecogs.com/gif.latex?\bg{black}%5Cfrac%7B1%7D%7B%5Cphi%7D%5Cint_0%5E%5Cinfty%20%5Cfrac%7Bu%5E%7B%5Cphi-2%7D%7D%7B%281&plus;u%29%5E%5Cphi%7D
