### ISSUE TITLE
Forgot your password does not deliver email to me

### ISSUE THREAD

**Issue by rodamaral** [TASVideos/tasvideos#1445]
Hello! After the new site was released, I tried to change my email but then wasn't able to login.
I tried to use [ForgotPassword](https://tasvideos.org/Account/ForgotPassword), which always returns the message:
```
Forgot password confirmation
Please check your email to reset your password.
```

The email, however, never arrives.
Profile: https://tasvideos.org/Users/Profile/Amaraticando

Possibly related to #759

**Comment by Masterjun3** [comment]
With an unconfirmed email there are quite a lot of restrictions to any account. This one was a leftover behavior from before #1237 and #1241 .
This specific case was handled manually and shouldn't happen in the future.
