### ISSUE TITLE
Editing a Publication description does not update its YouTube description

### ISSUE THREAD

**Issue by despoa** [TASVideos/tasvideos#1455]
Whenever you edit a publication's description, it's YouTube video description is not edited accordingly to reflect the change. This appears to be a recent bug as this did not happen before.

**Comment by fsvgm777** [comment]
Only editing the publication's description is affected by this. Recently published movies went public as they should, and movies that get obsoleted do get the [Obsoleted] tag.

**Comment by Masterjun3** [comment]
For now, a workaround that *should* work is just repeating the Edit->Update process to make it sync.

<hr>

The current problem is that it doesn't update the WikiPage variable even if the Markup has changed.
The `existingWikiPage` passed to the sync is from before the Markup Update.
https://github.com/TASVideos/tasvideos/blob/93cbe2325810007dfd3b6b55cbe813121dc78cb1/TASVideos/Pages/Publications/Edit.cshtml.cs#L261-L270
