### ISSUE TITLE
Registered users should not be able to register with a space at the end of their alias.

### ISSUE THREAD

**Issue by Spikestuff** [TASVideos/tasvideos#1461]
Multiple times we've had people register where they have a space after their alias.

Anywhere? Fine. At the end tho? That shouldn't be allowed.

**Comment by SamsaraTAS** [comment]
I should add that this breaks user search if someone registers with a space and then re-registers the same name without the space, or vice versa. Both names in the dropdown will lead to the account without the space.

**Comment by adelikat** [comment]
I went ahead and removed the ability to have spaces ANYWHERE in the name, been wanting to do that for awhile.  Existing usernames are still allowed to have it, though I would love to get everyone renamed eventually, so much code we have to write to support this.
