### ISSUE TITLE
Aliases that register with a space anywhere should be marked with an %20.

### ISSUE THREAD

**Issue by Spikestuff** [TASVideos/tasvideos#1462]
We've had registered users which break the updates by not properly linking to the alias, due to the space within their alias.

A space is represented by a %20 in a url link.

**Comment by adelikat** [comment]
Or we force them all to have a name change

**Comment by nattthebear** [comment]
This sounds like a bug in our code, but there's not enough information here for me to find it.  What's "the updates"?  Can you be more specific?

**Comment by vadosnaprimer** [comment]
IRC and Discord bot reports, related to user registration and activity.

**Comment by adelikat** [comment]
We technically have a bug, but I just disallowed usernames with spaces, so you should never see this now
