### ISSUE TITLE
Embeded youtube videos will not play if it’s from the user’s own channel.

### ISSUE THREAD

**Issue by EZGames69** [TASVideos/tasvideos#1487]
Whenever I’m on my own submissions, when I try to play the embeded video from my own channel, it refuses to play.  This doesn’t seem to happen for videos on other channels that are not mine.

I’m not sure if it’s because my browser knows it’s my channel (firefox), and conflicts with something with the site, but that’s the only explanation I can come up with.

**Comment by Spikestuff** [comment]
Able to replicate on Firefox 107.0 (64-bit):
![image](https://user-images.githubusercontent.com/12412764/206503534-31622099-0f68-42a1-a950-d991c018f2bc.png)

Not being signed in on that account allows playback:
![image](https://user-images.githubusercontent.com/12412764/206503832-f890138f-2734-40db-96b8-6a95d6aca064.png)

**Comment by adelikat** [comment]
Unable to reproduce, on firefox, signed in as me, I can play my own embeds, can someone open their browser console and see if there are any errors?

**Comment by EZGames69** [comment]
are the embedded videos you're testing unlisted?

**Comment by adelikat** [comment]
They are not, are yours? can you try listing them to see if it stops happening?

**Comment by CasualPokePlayer** [comment]
I can reproduce this, Firefox, signed in as myself (the videos are not unlisted btw), I see this in the browser console:
![image](https://user-images.githubusercontent.com/50538166/212476049-479ae573-e2fa-4a79-a916-6f2bdcc472d9.png)

**Comment by CasualPokePlayer** [comment]
I can reproduce this, Firefox, signed in as myself (the videos are not unlisted btw), I see this in the browser console:
![image](https://user-images.githubusercontent.com/50538166/212476556-1f28a41c-d6c0-4587-8345-252309070107.png)

**Comment by Masterjun3** [comment]
I can confirm this happens with Firefox if Enhanced Tracking Protection is enabled.
![image](https://user-images.githubusercontent.com/22375320/232058868-59665182-4a73-4a9f-99a3-769bb1adfd77.png)
The embeds play fine if this is disabled.

**Comment by Masterjun3** [comment]
I can't replicate this issue anymore. It seems Firefox fixed whatever issue I was having above.
