### ISSUE TITLE
Forum thread title is no longer in browser tab name

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#1488]
https://tasvideos.org/Forum/Topics/23615

I kept that tab open for a week and it still appears as

![изображение](https://user-images.githubusercontent.com/7092625/206678410-b10dcb00-b4f0-4155-af0e-b4ebf7816710.png)

But I opened it in another tab just now and it's just

![изображение](https://user-images.githubusercontent.com/7092625/206678510-b643d21a-7a89-4022-9841-3f10fcbd7a3d.png)

**Comment by Masterjun3** [comment]
Looks like it was accidentally removed in 5baf4ea8d4f39fe395531695cb474b3bcb507665 .
