### ISSUE TITLE
Game title doesn't appear in discord embeds

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#1489]
![изображение](https://user-images.githubusercontent.com/7092625/206679729-a3e6ee0c-6471-4016-9db4-4378ab831462.png)

**Comment by adelikat** [comment]
What did it used to look like? what context is this? just when you past a link?

**Comment by vadosnaprimer** [comment]
I don't think it's ever been there, just wasn't implemented. But yeah simply posting a game link needs to embed what game it is, like it works when posting a forum link for example

![изображение](https://user-images.githubusercontent.com/7092625/206728031-b84a7390-179b-42f3-bd1b-8ab09829a764.png)
