### ISSUE TITLE
On profile page, hide or use redlink for nonexistent homepage

### ISSUE THREAD

**Issue by YoshiRulz** [TASVideos/tasvideos#1494]

**Comment by Masterjun3** [comment]
I meed more info.
Do you mean on the /Profile page, or on the /Users/Profile/<username> page?

**Comment by YoshiRulz** [comment]
I was looking at another user's profile, but do it for the user's own profile too because the edit page is linked in the sidebar in that case.

**Comment by Masterjun3** [comment]
So you want only the link above the "Joined On" to be changed?

**Comment by YoshiRulz** [comment]
Yes
