### ISSUE TITLE
Make subforum description optional

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#1502]
Some game subforums don't have descriptions, because there's nothing meaningful to say there.

![изображение](https://user-images.githubusercontent.com/7092625/212369844-c29b3607-991d-4c2d-87ce-414cb008ff06.png)

Ones with descriptions list eligible systems or mention the difference. But I don't want to come up with a filler wording just to make the code happy, because that would mean we need those filler words where they are applicable, which means copypasting them in every other game subforum. Which doesn't feel like there's demand for it.

**Comment by Masterjun3** [comment]
The change wanted here is implemented by removing this line:
https://github.com/TASVideos/tasvideos/blob/20cfcbbfb3f77188fb3eb8ce2b056b8ef2d212d6/TASVideos/Pages/Forum/Subforum/Models/ForumEditModel.cs#L16
