### ISSUE TITLE
Forum: add thread title to thread URL

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#1511]
When we link to threads in a discussion, it's impossible to know what the thread is about until you open the link. And when writing a post, it's impossible to check if you got the link right unless you click the link in the preview (or in the actual post you made). When many threads need to be linked, it becomes a tiring process to verify the links you've just posted, and there's also a danger of accidentally opening them in the same tab you're editing in.

**Comment by adelikat** [comment]
Can you please provide a url of a page that has an example of this link?

**Comment by vadosnaprimer** [comment]
Looks like I requested the wrong thing initially. The hover thing depends on what we transform the URL into, and for things like `movie` or `wiki` it's transformed into a page title of some kind. And that appears on hover if there's replacement text.

So I should just request that for `thread` links, it would transform them into `"Thread #NNNNNNN: Thread title here"` instead of simply `"Thread #NNNNNNN"`.

https://github.com/TASVideos/tasvideos/blob/b04cbe6a1b8cab2d786aace65e65581417948bbf/TASVideos.ForumEngine/Node.cs#L293

Here's an example post:
https://tasvideos.org/Forum/Posts/521864

**Comment by adelikat** [comment]
@vadosnaprimer : thanks!
