### ISSUE TITLE
Restrict signatures completely until an amount of posts.

### ISSUE THREAD

**Issue by Spikestuff** [TASVideos/tasvideos#1517]
Making it easier to go after bot accounts as there's some that commonly have their signatures display the spam material without ever posting.
Possibly only needs at least 4 (Newbie) posts...

**Comment by CasualPokePlayer** [comment]
We already have role for this kind of thing (`Experienced Forum User`), all that needs to be done here is making a perm changing the signature, should be applicable here: https://github.com/TASVideos/tasvideos/blob/6476c07c04eff6e7d6c34fc51da9f7af68d60a87/TASVideos/Pages/Profile/Settings.cshtml.cs#L113

**Comment by adelikat** [comment]
This work was done
