### ISSUE TITLE
Adjusting robots.txt, maybe allow Forum indexing for search engines?

### ISSUE THREAD

**Issue by Masterjun3** [TASVideos/tasvideos#1518]
Our [current](https://github.com/TASVideos/tasvideos/blob/68f147740cd141efab4c0a917f33a7e8c11a2e80/TASVideos/Middleware/RobotHandlingMiddleware.cs#L25-L40) robots.txt looks like this:
```
User-agent: *
Disallow: /forum/
Disallow: /movies/
Disallow: /submissions/
Disallow: /media/
Disallow: /MovieMaintenanceLog
Disallow: /UserMaintenanceLog
Disallow: /InternalSystem/
Disallow: /*?revision=*
Disallow: /Wiki/PageHistory

User-agent: Mediapartners-Google
Allow: /forum/

User-agent: Fasterfox
Disallow: /
```

(I think) it was mostly taken as-is from the old site. Maybe it's time to revisit it again and see if there are some things we don't need to disallow.

Especially the Forum, since that prevents any topics and posts from showing up on Google and other search engines. Except maybe they do because apparently it's case-sensitive and our URLs are now `Forum` not `forum`. Which also begs the question why /movies/ and /submissions/ is disallowed.

**Comment by adelikat** [comment]
yeah, I don't understand why we only allow google for forum, feel free to make a PR to adjust some of these things, I mostly just copied what we had, and haven't put the brain power in to have an expert opinion on the subject
