### ISSUE TITLE
Add Permission to Edit Forum Posts for Users

### ISSUE THREAD

**Issue by Masterjun3** [TASVideos/tasvideos#1526]
Currently every user who can post can also edit their posts. According to staff we want to add a separate permission for this.

Important to note, we already have a Moderation Edit Permission, allowing someone to edit everyone's posts. So this feature needs to work together with the existing permission.

**Comment by adelikat** [comment]
Do we still want this? And what about post deletions? should that be a new permission? or use the new edit permission? or keep using the create permission?

**Comment by adelikat** [comment]
At the same time, if someone makes a typo on their first post, they can't do anything about it? seems weird.

Based on that need I think deleting a post MUST be on the create post permissions.  Because worst case you can delete and start over

**Comment by adelikat** [comment]
This has been done and deployed!
