### ISSUE TITLE
Benchmark Pre-rendering wiki posts

### ISSUE THREAD

**Issue by nattthebear** [TASVideos/tasvideos#153]
Similar to https://github.com/adelikat/tasvideos/issues/129

Not sure what perf gain would be

Unlike forum posts, much more complex to implement because you can't just cache the final rendered HTML; some sort of serialization of the node tree or a baked form of the writing would be needed...

**Comment by adelikat** [comment]
Interesting.  This may not be as beneficial though.  One downside to forum posts is that while faster overall, you have so many to do per page of forum posts.

But this should be considered

**Comment by nattthebear** [comment]
The quantities clearly aren't the same, with forum posts being more numerous but shorter, but my expectation is that for any particular amount of content, the wiki parser probably takes longer to parse it

**Comment by vadosnaprimer** [comment]
What if it's modular in some way, with certain heavy elements being static/cached/pre-rendered, while the main thing remains dynamic for lightweight stuff and composing?

**Comment by adelikat** [comment]
Kicking the can on this.  Wiki pages are performing fine.  It would be worth it to one day do some profiling and see if this has enough benefit to be worth it.

**Comment by adelikat** [comment]
I think this no longer makes sense, with wiki modules, there is dynamic data, so what would we statistically pre-render and store? Also what we have is plenty fast enough and has held up well

Closing
