### ISSUE TITLE
Make Genres page link to lists of games with that genre

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#1532]
https://tasvideos.org/Genres

We split `Unofficial game` into individual tags, and I only found a way to see [which movies belong to games with that genre](https://tasvideos.org/Movies-Unofficial%20game). I removed that genre tag from all games that appear in those movies, but [the genre itself](https://tasvideos.org/Genres) still says 98 games have it, and I can't see what those games are.

So we need a way to show a list of those games, regardless of whether they have movies or not.

**Comment by ThunderAxe31** [comment]
Now it says there are [56](https://tasvideos.org/Genres). I wonder if it's bugged?
