### ISSUE TITLE
Unable to filter publications by genre "Pre-Release"

### ISSUE THREAD

**Issue by despoa** [TASVideos/tasvideos#1534]
On [this page](https://tasvideos.org/Publications/Filter), I am unable to filter publications so that I only get pre-release entries. In fact, it redirects me to the main Movies page. I'm not sure if this is a feature of there not being any "pre-release" games catalogued or a bug.

**Comment by coolkirby2000** [comment]
This is working now for me. From the page you linked, clicking Genres>prerelease, then Filter gives me https://tasvideos.org/Movies-prerelease which has 8 movies, starting with A2600 Heart Like a Wheel, which are designated Prerelease.

If it's fixed for you, too, you may close the issue.

**Comment by adelikat** [comment]
yeah, it was the dash that caused the issue and it no longer has it, closing
