### ISSUE TITLE
Inconsistent movie length displayed

### ISSUE THREAD

**Issue by ThunderAxe31** [TASVideos/tasvideos#1535]
The very same movie file si displayed to have two different movie lengths, depending if it's uploaded in userfiles or as submission. See this example:
00:55.16 https://tasvideos.org/UserFiles/Info/638153314364640163
00:55.17 https://tasvideos.org/8100S
Note that both have no catalog info set, so there is clearly something inconsistent in how timing is handled by default.

**Comment by Masterjun3** [comment]
It seems the problem here is that the userfile code doesn't use our ITimeable interface.
https://github.com/TASVideos/tasvideos/blob/1ff373b53f92a03df8fbb177ae2ed6ac620c05fa/TASVideos.Common/ITimeable.cs
It's where we do the rounding for all the other places.
