### ISSUE TITLE
Prioritize the Catalogue title of a game over the submitted Game Name in Submission List.

### ISSUE THREAD

**Issue by Spikestuff** [TASVideos/tasvideos#1546]
Title.

Saw it with the [now published Tetris TAS](https://tasvideos.org/5222M) where the Game Name provided by the author was placed and not the Catalogue that was provided/updated by the Judge.
![image](https://user-images.githubusercontent.com/12412764/231963960-ba5c7ec6-f72c-4cf4-8ed7-e7e2cad6a0f5.png)
![image](https://user-images.githubusercontent.com/12412764/231963970-b149289b-774b-46fb-9a46-3f9c66ce8511.png)

**Comment by Masterjun3** [comment]
Note that not only do you have to prioritize the catalogued game title, you also have to then prioritize the game version Title Override if it's catalogued and set. Those are the 3 possibilities.

Basically the 3 paths like the submission title generation handles it (line 126, 129, and 134):
https://github.com/TASVideos/tasvideos/blob/37bf1c2edde226f4157bb4aaff168300f690ba5d/TASVideos.Data/Entity/Submission.cs#L126-L135
