### ISSUE TITLE
When Publishing "Select movie to be obsoleted" do not retain Available Flags

### ISSUE THREAD

**Issue by Spikestuff** [TASVideos/tasvideos#1551]
Only retain Available Tags instead.

**Comment by adelikat** [comment]
What's wrong with regaining the flags too?

**Comment by vadosnaprimer** [comment]
Flags are too case-by-case specific. For example, you can't assume the new movie will also have author's commentary or console verification.

**Comment by Spikestuff** [comment]
The only flag that should be retained when a movie is obsoleted is Fastest Completion.
Other than that what feos wrote would be case-by-case for everything else.
