### ISSUE TITLE
Certain usernames aren't handled properly by the site

### ISSUE THREAD

**Issue by RetroEdit** [TASVideos/tasvideos#1565]
I was just randomly browsing old submissions, and found this one: https://tasvideos.org/Forum/Topics/3425

It's by a user with the username `/*-` (or `slash_star_dash` in the submission post's topic name), but the links to the user's profile in the forum posts return 404 not found: https://tasvideos.org/Users/Profile/%2F*-

The site does seem to have a workaround if you're searching for the user: it will provide https://tasvideos.org/Users/Profile?name=%2F*- which does work

Related: #119

**Comment by adelikat** [comment]
The solution here is to rename users that have a slash.  While #119 intends to support additional characters, slash will not be one of them

**Comment by RetroEdit** [comment]
I guess this has been discussed before: #1133

I found another such issue with usernames with spaces, but it's a bit more convoluted, so I don't feel like taking the time to explain currently. It might not even be a real issue, anyway.

Maybe this issue should be closed if it's not supposed to be a site issue, but an administrative issue. It might be good to come up with a concrete plan for that though (probably in other venues), since based on the previous issue, it hasn't been addressed in almost a year.
