### ISSUE TITLE
Font Awesome Upgrade broke some icons

### ISSUE THREAD

**Issue by Masterjun3** [TASVideos/tasvideos#1566]
For example the icons for selecting the theme used to look like this:

![image](https://github.com/TASVideos/tasvideos/assets/22375320/b04330fe-6919-4ea1-a2e2-69eee2eeee6f)

But are now broken:

![image](https://github.com/TASVideos/tasvideos/assets/22375320/d2ce0628-c09b-4590-8788-0b15cfcbf6c9)

We may need to check all icons to see if they are broken, or find some sort of list of ones that were deprecated.
Relevant commit: b2231ee2cd6d5b2e97df864e55a408c9e2d7c817

**Comment by Masterjun3** [comment]
On movie pages, Discuss and Rating icons are missing as well.

At this point I'd almost suggest completely reverting the commit. We're clearly not ready to upgrade yet.

**Comment by adelikat** [comment]
Reverting for now, I don't see what icons need to be reverted as well, so I"ll leave this open for now

**Comment by Masterjun3** [comment]
This commit needs to be reverted as well 5b3133d6f68b9213082000c95574fee594575846

**Comment by adelikat** [comment]
Thanks for looking for all the ones that need reverting. I reverted 5b3133d and deployed.  Closing this issue
