### ISSUE TITLE
[F.Rq] Markup for game group description pages

### ISSUE THREAD

**Issue by GMPranav** [TASVideos/tasvideos#1577]
Currently the game group description seems to be plain text. Neither the wiki nor the forum markup syntax seems to be applied. Would be nice to have markup for styling.
Example - https://tasvideos.org/GameGroups/78

On a sidenote there doesn't seem to be discord alerts when someone edits this page either.

**Comment by vadosnaprimer** [comment]
Please make a new issue for the sidenote.
