### ISSUE TITLE
Searching for a user in the submission text is case sensitive.

### ISSUE THREAD

**Issue by Spikestuff** [TASVideos/tasvideos#1581]
Yes, I'm aware that it has autofill to prevent a case like this, **but sometimes users are in a rush in writing an alias** and don't have time making sure the case is correct, or to use autofill especially if your alias is short like "nymx".
![image](https://github.com/TASVideos/tasvideos/assets/12412764/fdcdbf41-15f3-4186-83cc-8d40e731b1f3)
![image](https://github.com/TASVideos/tasvideos/assets/12412764/eddd1d34-796d-47ff-908d-3b85300717ca)

Imagine if we had aliases with alternating cases like Fz-Last for instance or nEilfox.

But also on the topic of autofill, it doesn't show up when you complete the alias in the wrong case.

**Comment by Masterjun3** [comment]
> But also on the topic of autofill, it doesn't show up when you complete the alias in the wrong case.

It does for me.
