### ISSUE TITLE
Redirect to Sign in And Back to Original Page When Attempting to View Unauthorized page

### ISSUE THREAD

**Issue by TiKevin83** [TASVideos/tasvideos#1583]
Right now if you attempt to navigate to a page that requires authorization and you are not signed in, you just get the 404 not found page. Out of the box dotnet core sites have some functionality to redirect to the sign in page in that instance, save redirectUri into a query param and restore the url to the one from params after sign-in if it's there. It looks like that functionality is missing in our current setup and it'd be helpful to reimplement it. One of the answers here has some of the basic boilerplate.

https://learn.microsoft.com/en-us/answers/questions/1031147/how-to-redirect-to-a-page-after-logged-in

**Comment by Masterjun3** [comment]
Relevant to #1580 , maybe duplicate.

**Comment by TiKevin83** [comment]
closing as duplicate of #1580
