### ISSUE TITLE
A shortcut button for handling spam posts

### ISSUE THREAD

**Issue by moozooh** [TASVideos/tasvideos#1585]
The workflow for isolating spam posts and banning the poster right now consists of these steps:

1. Splitting the post(s) out into a separate thread in the staff forum, assigning some temporary name to the thread in question.
2. Navigating to the thread and merging it with the [designated spam collection thread](https://tasvideos.org/Forum/Topics/13101) in the staff forum.
3. Going to the spammer's profile, removing the existing roles (e.g. _default user_), adding the _banned user_ role, and adding a moderator comment (e.g. "spam account").

Quite a few repetitive actions, when you think of it. The first step is thankfully skipped when the post is made in its own separate thread (in which case you go straight to merging), but you still have to do the rest, which requires clicking over a dozen times in different places on different pages, and also some typing. Takes _significantly_ longer to do on a mobile, easily over a minute I'd say.

All of this could potentially be rolled into a single button specifically for spam posts because the whole process is identical every time and doesn't require making any situational decisions. This button would be next to the post delete button and pressing it would move the post directly to the spam collection thread while banning the poster (with the corresponding moderation comment added) without extra navigation, clicks, or typing.

The spam collection thread itself could just be hardcoded for now because it's not expected to change—possibly ever. This can be reconsidered if there's a need for a more comprehensive forum admin panel where it could be one of the settings tucked somewhere it will never be changed unwittingly. I won't debate the need for the thread itself; as far as I'm concerned, it has a potential use in case we need evidence to do some forensics or deal with hijacked accounts.

**Comment by adelikat** [comment]
I think we need to discuss the most efficient solution first.  Why not just delete spam posts?

UI-wise, I'm thinking a permission locked "spam" button on posts, that will do whatever to it, including auto-banning the author

**Comment by moozooh** [comment]
I mean, sure, it's always been an option. I actually find the established practice of keeping a catalogue of spam posts valuable for the same reason we don't normally delete user posts. I can't say off the top of my head why or when _exactly_ we might need to revisit them—we probably won't know until we do—but it doesn't cost much to keep them around just in case. If we're making a button, I think it's not that much of a stretch to have it move the post as opposed to deleting it.

UI-wise, yes, a button somewhere next to the post deletion button, available to the moderator role and above.
