### ISSUE TITLE
System detection for openMSX movie files (.omr) post-18.0 is broken

### ISSUE THREAD

**Issue by Randomno** [TASVideos/tasvideos#1586]
The format was changed so the system is now under snapshots>item>config>config>msxconfig>info>type. As far as I could tell, nothing else has changed, though I'm not sure why it throws an error trying to parse 18.0 files instead of defaulting to MSX system.

18.0 example movie (renamed to .gz):

[openmsx0038.gz](https://github.com/TASVideos/tasvideos/files/11909612/openmsx0038.gz)

Relevant page: https://tasvideos.org/EmulatorResources/OpenMsx/OMR

**Comment by MBilderbeek** [comment]
In the meantime, openMSX 19.1 has been released. So an update would be helpful. 

If someone tells me how I could test it, I can try to implement it myself.
