### ISSUE TITLE
Link to API

### ISSUE THREAD

**Issue by adelikat** [TASVideos/tasvideos#160]
/api is the swagger page for the api.

We want to link this somewhere

**Comment by meshuggahtas** [comment]
Apart from mentioning in the Wiki @ https://github.com/TASVideos/tasvideos/wiki/Project-Structure#other , maybe put the API link after the bottom footer for example:
© 2021 - TASVideos v2.1.464 - Swagger API

**Comment by adelikat** [comment]
hmm, that's not a bad idea
