### ISSUE TITLE
Allow spaces in page names

### ISSUE THREAD

**Issue by Randomno** [TASVideos/tasvideos#1611]
I'm sure this has come up before but couldn't find an existing issue. I believe any serious wiki system should allow this instead of forcing CamelCase. In conjunction with redirects (#1593), we can make substantial updates to the wiki.

URLs should use underscores. We already support underscores in URLs but these need to be converted to/from spaces in links and page titles.

Spaces in pages are also somewhat supported because of usernames with spaces, e.g. https://tasvideos.org/HomePages/negative%20seven/SpecializedTASTools (see #1462).

As an aside, lowercase names are also somewhat supported due to this. MediaWiki doesn't support lowercase names and instead has a template to change the displayed title (e.g. https://en.wikipedia.org/wiki/MacOS). I don't see why we can't support this though.

In general, I'm not familiar with any technical issues this change might have.

**Comment by vadosnaprimer** [comment]
What are the benefits of having spaces in wiki pages?

**Comment by Masterjun3** [comment]
Oh I'd like to quickly throw in that if we're changing how URLs work, we should absolutely avoid spaces and parentheses in them.
I know this wasn't suggested, but it's important to keep in mind. (Spaces cut off url parsing, and parentheses have a hard time working with the currently popular markdown.)

**Comment by Randomno** [comment]
To match what the article is about rather than needing CamelCase workarounds, like the current [regex code](https://github.com/TASVideos/tasvideos/blob/main/TASVideos.Common/Extensions/StringExtensions.cs#L153), and it's overall more intuitive. I can't really come up with a full list of pros and cons, only refer to the abundance of Wiki systems that support this.

**Comment by vadosnaprimer** [comment]
So just the visual feel? I'd say we need some more pros for such an undertaking.

**Comment by adelikat** [comment]
I do not want to allow spaces in page names

**Comment by nattthebear** [comment]
I don't particularly feel like running through another round of bugfixes in page name canonicalization code.  If we were building something brand new from scratch, sure, but we were bound by the existing wiki syntax and existing page naming conventions when we started.
