### ISSUE TITLE
[F.Rq.] Preview button for user file descriptions

### ISSUE THREAD

**Issue by RetroEdit** [TASVideos/tasvideos#1617]
Someone on Discord pointed out this was missing, and I also have occasionally wanted this feature. Wiki editing already has a preview button and user files use the same syntax.

**Comment by warmCabin** [comment]
No. Fucking. Way. You are not gonna believe this, but I happen to have a screenshot from 2018 that inadvertently captured the userfiles UI, and guess what's there?

![Screenshot 2018-10-13 16 45 27 - cropped](https://github.com/TASVideos/tasvideos/assets/35278529/069e491b-27b3-472f-815a-6fde9c44ffeb)
