### ISSUE TITLE
Roles and Permissions pages and anchor links contain spaces

### ISSUE THREAD

**Issue by Randomno** [TASVideos/tasvideos#1627]
https://tasvideos.org/Roles/Site%20Admin
https://tasvideos.org/Roles/List#Published%20Author
https://tasvideos.org/Permissions#See%20Diagnostics

This could be changed with `id="@entry.Name.Replace(" ","")"` for example, but [we split the permission name beforehand](https://github.com/TASVideos/tasvideos/blob/main/TASVideos/Pages/Permissions/Index.cshtml.cs#L23), so it seems a bit redundant.

**Comment by adelikat** [comment]
Why is this a problem?

**Comment by nattthebear** [comment]
In HTML, an id is not permitted to contain the space character.  Practically speaking, browsers allow it, but it will still break in certain attributes such as `aria-controls` which expect space-separated lists of ids.

Additionally, we seem to have some garbage implementation on our side that is confusing URL escaping here.  Loading that third page I see this in the console:

```
Uncaught DOMException: Document.querySelector: '#See%20Diagnostics.collapse' is not a valid selector
```

It probably needs to be reworked something like this:

```javascript
document.querySelector(decodeURIComponent(location.hash).replaceAll(" ", "\\ "))
```

But that won't handle all scenarios either.
