### ISSUE TITLE
Look into oEmbed to replace hand-written embed implementations

### ISSUE THREAD

**Issue by YoshiRulz** [TASVideos/tasvideos#1633]
oEmbed is a simple protocol over HTTP where you send a service, such as YouTube, a URI to a "post" or equivalent from their site, and they return the HTML code for embedding it. I only just learned of it, but it's supported by some big names so there must be something to it.

[spec](https://oembed.com/), [an ASP.NET implementation](https://github.com/hey-red/OEmbed)

Benefits:
- Smaller codebase
- Support for new services can be added very easily
- If, for example, YouTube changes their embed player overnight and breaks the old one, no code change or redeploy will be needed

Drawbacks:
- Obviously services that don't support the protocol will need to be specially handled
- Adds extra requests—I believe with the package linked above these are done server-side with configurable caching, but I'm sure they could be done client-side
- Increases reliance on the service to not inject malicious code (you *could* parse the markup that's returned, but anything beyond a simple tag allowlist would be about as much maintenance as hand-written embeds)

**Comment by nattthebear** [comment]
I don't like it.  Some of these reasons you mentioned already.

* Extra request and possible caching layer means extra complexity.
* XSS - The spec recommends throwing the content in an iframe to avoid XSS.  But as most of these players are just iframes, you'd need a second layer of iframe which would add cost on the client side.
* I find the breaking changes argument unconvincing.  Practically speaking, Youtube and other major players will never break existing embeds, as too many sites would break from it.  What could they gain from breaking embeds, anyway?  In the end, the embed code is always going to be an iframe to a URL.  Desired dimensions might change, but the player can easily account for that.  With a bit of smart routing, you can keep old URLs valid forever (unless you're TASVideos).

**Comment by adelikat** [comment]
Closing for reasons mentioned above
