### ISSUE TITLE
[F.Rq] Turn links to missing pages red

### ISSUE THREAD

**Issue by RetroEdit** [TASVideos/tasvideos#1652]
Wikipedia's wiki rendering engine efficiently communicates whether linked pages exist by turning links to nonexistent pages red. Doing this on the TASVideos wiki would be a nice enhancement.

**Comment by adelikat** [comment]
If there's 15 links on a page, that's 15 additional hits to the database.  Wikipedia may have the server resources for that, but I'm not inclined to push our resources that hard, for a minor benefit.

We have a page to monitor broken links: https://tasvideos.org/WikiOrphans 
The intent is for for editors to regularly monitor this page and correct issues

**Comment by YoshiRulz** [comment]
I'd hope you'd be able to batch the calls... Anyway, making those calls would be required for #1349, so implementing that would give you this for free.

**Comment by YoshiRulz** [comment]
Did #1750 make this feasible?
