### ISSUE TITLE
External link appearance is broken

### ISSUE THREAD

**Issue by bigbass1997** [TASVideos/tasvideos#1659]
The icon placed next to all external links has a huge empty space around it.

![image](https://github.com/TASVideos/tasvideos/assets/790116/34344a26-9f8e-406d-a578-00aed4f44440)
(image from https://tasvideos.org/5510M)

I verified with TiKevin83 that he also sees this on his computer.

**Comment by RetroEdit** [comment]
(I also noticed this yesterday: https://github.com/TASVideos/tasvideos/issues/1550#issuecomment-1686602462 -- the screenshot is helpful, though)

**Comment by Randomno** [comment]
Not really broken, just has a lot of padding. I think 0,25rem either side looks good.

**Comment by bigbass1997** [comment]
I meant broken in the sense that the appearance is not how it should be, or how normally looks. The icon itself is too large, and the spacing issue (not sure if it's padding or margin.)
