### ISSUE TITLE
module:youtube video iFrame in UserFiles has forced 4:3 aspect ratio

### ISSUE THREAD

**Issue by MoskovchenkoD** [TASVideos/tasvideos#1660]
Here is how it looks in UserFiles, using `[module:youtube|v=]` tag. The thumbnail has black bars up and down and the image is cut on the sides. 
Reference: https://tasvideos.org/UserFiles/Info/638285927691796474

![image](https://github.com/TASVideos/tasvideos/assets/12684111/b3fbe737-8172-48ee-96fd-8674b0975545)

Here is how it looks in a Topic post, using `[video]` tag. The thumbnail looks alright.
Reference: https://tasvideos.org/Forum/Topics/15145?CurrentPage=2&Highlight=524918#524918

![image](https://github.com/TASVideos/tasvideos/assets/12684111/dfeb6c1c-e8af-40d2-9a33-5054649cdfaf)

**Comment by Masterjun3** [comment]
In both Forum formatting and Wiki formatting you can specify the width and height yourself.
Forum: `[video=480x270]https://www.youtube.com/watch?v=dQw4w9WgXcQ[/video]`
Wiki: `[module:youtube|v=dQw4w9WgXcQ|w=480|h=270]`

But as you noticed, it is true that the defaults for embedding differ:
Forum (all videos):
https://github.com/TASVideos/tasvideos/blob/50777c43090559791e19781791a5877084a4b1f5/TASVideos.ForumEngine/Video/WriteVideo.cs#L97-L98
Wiki (only YouTube):
https://github.com/TASVideos/tasvideos/blob/50777c43090559791e19781791a5877084a4b1f5/TASVideos/ViewComponents/Models/YoutubeModel.cs#L6-L7
