### ISSUE TITLE
thread splitting issue

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#1668]
I'm trying to split the last few posts from https://tasvideos.org/Forum/Topics/13505 but I'm getting a blank page with [the same URL](https://tasvideos.org/Forum/Topics/Split/13505) when I hit the split button, regardless of how I pick the posts to split (radiobutton or checkboxes).

Splitting from this thread worked tho https://tasvideos.org/Forum/Topics/23197

**Comment by adelikat** [comment]
![image](https://github.com/TASVideos/tasvideos/assets/1679846/a7fc17e1-eb9d-44f4-b317-4a9eb52e6fb7)
This is why.  There's simply too many posts for the request to handle it.  Not sure what to do about that
