### ISSUE TITLE
Subs-List - show vote counts

### ISSUE THREAD

**Issue by adelikat** [TASVideos/tasvideos#167]
We need to show the vote breakdown, or at least the vote totals.  The legacy "confidence" calculation isn't necessary.

**Comment by meshuggahtas** [comment]
Should be inserted between Submitted and Status columns

**Comment by adelikat** [comment]
So, we have been live for over 7 months and I haven't heard anyone request this be added.  Do we still care about this? @MemoryTAS  @vadosnaprimer

**Comment by vadosnaprimer** [comment]
The old site only ever displayed the ratio on that page so it was needed for that.  Lately we're not that much into raw numbers, and if needed the ratio can be displayed on the submission itself. On the sub list tho... having this data to maybe compare it to other submissions for some reason... feels super artificial and weird.

**Comment by adelikat** [comment]
After some discord discussion, everyone agrees this isn't very needed anymore, clsoing
