### ISSUE TITLE
Lock post edits in locked threads

### ISSUE THREAD

**Issue by ThunderAxe31** [TASVideos/tasvideos#1673]
The point of locking a thread is to prevent any further evolution of a discussion deemed by the moderation as disruptive. However, until now users were still able to edit their already existing posts, despite a thread being locked. This is a problem, because users may use edits to keep a conversation going, or even worse, delete evidences of their wrongdoings.

TL;DR: if a thread is locked, make the users unable to edit posts belonging to that thread. This of course shouldn't apply for anyone who has moderator privileges.

**Comment by Invariel** [comment]
Should probably prevent post deletions in locked threads as well, since the code change is going to be in the same neighbourhood.
