### ISSUE TITLE
Page slugs seem to be missing from the (wiki) search index

### ISSUE THREAD

**Issue by YoshiRulz** [TASVideos/tasvideos#1674]
For example, a search for `taseditor` doesn't include https://tasvideos.org/EmulatorResources/TASEditor.

**Comment by adelikat** [comment]
I stumbled upon the idea of putting keywords in an [if:0] tag, and I added taseditor.  It didn't show up though, but I think that's a separate issue, we rely on postgres full text search, there should be a way to coax it higher on the search results.

However, this ticket was about having slugs, which we have, via this method
