### ISSUE TITLE
discord notifications: put URL inside the message text

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#1681]
Current notification for wiki edit:
> Page InternalSystem/PublicationContent/M5436 edited by adelikat (use relative link) https://tasvideos.org/InternalSystem/PublicationContent/M5436

Discord allows markdown links now, so we can do this instead:
> Page [InternalSystem/PublicationContent/M5436](https://tasvideos.org/InternalSystem/PublicationContent/M5436) edited by adelikat (use relative link)

For forum:
> [New Post](https://tasvideos.org/Forum/Posts/525070) by feos (WorkB: #8578: Mizumaririn's NES Super Mario Bros. 3Mix "all 300 star coins" in 2:07:17.64)

Catalog:
> [8519S](https://tasvideos.org/8519S) Catalog edited by feos (Game changed from "" to Sonic 1: Return to the Origin, Game Version changed from "" to Sonic 1: Return to the Origin | #8519: CyanTheGamerhog01's Genesis Sonic 1: Return to the Origin "glitchless" in 19:23.82)

etc

This would make the log less cluttered and reduce copypaste.

**Comment by YoshiRulz** [comment]
see also https://github.com/TASVideos/tasvideos/issues/1353#issuecomment-1664454147
