### ISSUE TITLE
Site map doesn't show Permissions link or subpages

### ISSUE THREAD

**Issue by Randomno** [TASVideos/tasvideos#1685]
https://tasvideos.org/Wiki/SiteMap
![image](https://github.com/TASVideos/tasvideos/assets/17330834/93f6e6b1-eab2-47a1-a487-dd5c79c33b36)

Doesn't show https://tasvideos.org/Permissions/Index or https://tasvideos.org/Privileges, or link to any of them.

I think this is a result of messy structure of pages like this, but I don't understand it enough.

**Comment by adelikat** [comment]
it doesn't show Privileges because that page doesn't exist, it is a redirect to Permissions
Permissions should be a link, it's an edge case where there is only 1 page in that group, the only developed page that is alone. That's the real bug here, and legit.
