### ISSUE TITLE
Role editing grants unexpected privileges

### ISSUE THREAD

**Issue by moozooh** [TASVideos/tasvideos#1690]
As a Senior Moderator, I'm able to remove _any_ existing role, including the Site Admin role, by either unchecking it or pressing the "x" next to it. Doesn't matter if I don't have permissions to _set_ it in the first place.

![example](https://github.com/TASVideos/tasvideos/assets/11360582/dd4d2128-1117-469c-82f4-9357299a7458)

**Comment by Masterjun3** [comment]
Important to note that **this is purely a visual bug**!
The server properly checks it again, and throws away changes that are not authorized.
