### ISSUE TITLE
Spam Button Doesn't Appear To Fully Work

### ISSUE THREAD

**Issue by CasualPokePlayer** [TASVideos/tasvideos#1694]
1. Deleting a post for spam, assuming that's the only post in the topic, doesn't appear to delete the topic as it should, resulting in a topic with no posts and no directly apparent way to delete it.
2. The user which has the spam post does not actually get banned (despite that being stated in the UI that would happen).
3. There is no staff alert given for a post being marked as spam.
4. The spam button appears for posts that the moderator probably shouldn't be able to mark as spam, such as equal ranked moderators, themself, and higher ranked staff members (i.e. moderators can mark admin posts as spam).

**Comment by adelikat** [comment]
Note that it won't be smart with showing.  I can make it not show for your own posts, but that's about it.  We can't go querying every user's permission list that is on a page of posts, that would be too expensive
