### ISSUE TITLE
Game entry left/right buttons can 404

### ISSUE THREAD

**Issue by RetroEdit** [TASVideos/tasvideos#1695]
Just now, I noticed game entries have left and right arrows that link to the previous game entry and next game entry. I guess I never noticed it before (or maybe it's more recent?)

Anyway, if a game entry is deleted, then the left/right arrows lead to a 404 page, meaning it doesn't really work for casual browsing

An example is: clicking `<-` on https://tasvideos.org/3922G

I consider this a bug, since it probably should skip over those entries if the buttons are going to be that prominent in the UI.

**Comment by YoshiRulz** [comment]
It is new: https://github.com/TASVideos/tasvideos/commit/a9bf6069d402f5e8d4b2888030aca2e8a6d5f913
It's intentionally dumb, hence it's only shown to editors.

**Comment by RetroEdit** [comment]
If we're going down the route of not skipping entries, that could at least also show the buttons for missing games for cleaner navigation as another part of #1693

**Comment by vadosnaprimer** [comment]
I might be intentionally dumb, but I don't think the idea of skipping non-existent entries is worse than giving 404. The goal of the feature is quick iteration between entries, and 404 makes it slower, because you have to manually edit the URL to go to the next entry.

**Comment by adelikat** [comment]
We do not want this functionality. The point of the arrows was convenience for rare cases when you want to browse through subs and games looking for issues.  To add a link to the next id requires no querying of the database.  To know it exists, requires 2 extra hits to the database per request.  Plus the extra code complexity? This isn't worth it for a niche feature.
