### ISSUE TITLE
"Return to top" button appears below code lines in dark mode

### ISSUE THREAD

**Issue by Masterjun3** [TASVideos/tasvideos#1699]
E.g. on https://tasvideos.org/LuaScripting/Display but happens in both wiki and forums.
![image](https://github.com/TASVideos/tasvideos/assets/22375320/6681b1f0-a20f-4a32-91f1-999524e4f42d)

It is also hard to click it in this situation.

**Comment by nattthebear** [comment]
I'm not able to reproduce this:

![image](https://github.com/TASVideos/tasvideos/assets/1824709/d412669d-1d39-432b-bb04-5767d8a9f044)

Might it be only on a specific browser?

**Comment by Masterjun3** [comment]
Only in Dark Mode!

**Comment by nattthebear** [comment]
Here's the culprit:

https://github.com/TASVideos/tasvideos/blob/main/TASVideos/wwwroot/css/partials/_prism-dark.scss#L268

I'm not sure why we're changing z-index in dark mode.  Shouldn't the only difference between dark and light modes be the actual colors used?

**Comment by Masterjun3** [comment]
Maybe for the line highlight? But I'm actually not seeing where we even use line-highlight. (Our diff uses different classes for the green and red lines)
Maybe @TiKevin83 can explain the z-index or line-highlight?

**Comment by TiKevin83** [comment]
I don't remember why those lines are there, I agree the z-index in theory shouldn't need to change between light and dark mode but maybe the behavior it's for is broken in light mode and it should just be in the base template? Also isn't `.line-highlight.line-highlight` redundant and the same as `.line-highlight`?

**Comment by adelikat** [comment]
Delete it and see what breaks?  It's objectively wrong to be there

**Comment by Masterjun3** [comment]
Oh looks like our dark theme is just copied from a preset theme: https://github.com/PrismJS/prism-themes/blob/447479fc7b2be2051fe27e561aceed7cc87a589f/themes/prism-vsc-dark-plus.css .
Since we don't use line highlighting, at least not yet, we can just remove that block.

**Comment by vadosnaprimer** [comment]
I removed

https://github.com/TASVideos/tasvideos/blob/19077cbce60ac7d4f94b4323792ebe91b8b79174/TASVideos/wwwroot/css/partials/_prism-dark.scss#L263-L275

and it didn't help.

![изображение](https://github.com/TASVideos/tasvideos/assets/7092625/c7de1623-f471-45e5-a448-bb84b842a128)

**Comment by Masterjun3** [comment]
Have you used Ctrl+F5? Removing exactly those lines seems to work for me.

**Comment by vadosnaprimer** [comment]
Of course!
