### ISSUE TITLE
Unit tests for bbcode parser

### ISSUE THREAD

**Issue by adelikat** [TASVideos/tasvideos#170]
We need some at least

**Comment by nattthebear** [comment]
Can't (easily) do something like what we did with the wiki because some posts are in private forums, etc

**Comment by nattthebear** [comment]
We might consider using snapshot tests with a framework such as https://github.com/VerifyTests/Verify

**Comment by adelikat** [comment]
I added a test project and some unit tests, I think this fulfills the spirit of this ticket.  We have some tests, and more importantly, a place to add tests as part of fixing various issues
