### ISSUE TITLE
"Experienced forum user" is redundant in user credentials on forum

### ISSUE THREAD

**Issue by moozooh** [TASVideos/tasvideos#1702]
![2023-09-18 23 38 53 tasvideos org 26482e8a0e48](https://github.com/TASVideos/tasvideos/assets/11360582/859fcfd7-4e51-45ab-948e-f6c28866f159)

When everyone and their mom become "experienced" forum users almost immediately, what you _really_ mean by this is that they are _regular_ forum users that shouldn't warrant any particular credentials. Not to mention it's a mouthful and precedes more important roles such as Site Admin:

![2023-09-18 23 43 49 tasvideos org 38a3eab6c65d](https://github.com/TASVideos/tasvideos/assets/11360582/a41af9a3-fb3a-45ba-9884-cbb7f449d38e)

I don't think this information needs to be visible there at all. It serves no meaningful purpose at best, and is misguiding at worst.

It would be a lot more logical to mark users without the EFU role as "Newcomer" instead until they fulfill the requirement for EFU. If only because _those_ aren't regular, and that may be relevant for others to know—at least in theory.

**Comment by vadosnaprimer** [comment]
Makes sense.
