### ISSUE TITLE
Add Sharp X1 & Philips CD-i to .ltm parser

### ISSUE THREAD

**Issue by Spikestuff** [TASVideos/tasvideos#1706]
Recognizing `Platform: Sharp X1` or `Platform: SX1` and `Platform: CDi` in `annotations.txt`.

**Comment by vadosnaprimer** [comment]
Any info on resolutions/framerates?

**Comment by Spikestuff** [comment]
libTAS movies doesn't require specific framerates.

**Comment by vadosnaprimer** [comment]
> libTAS movies doesn't require specific framerates.

The site needs those.

**Comment by Spikestuff** [comment]
> The site needs those.

Was quoting you:
"actually I remembered that libtas movies don't need specific framerates on the site"

![image](https://github.com/TASVideos/tasvideos/assets/12412764/fbc45b10-b476-488a-b6ad-f86f046e66c9)
