### ISSUE TITLE
Implement system for rate-limiting submissions

### ISSUE THREAD

**Issue by Noxxaa** [TASVideos/tasvideos#1709]
Due to the increased submission backlog over the recent years, and the pressure it puts on the judging staff, it would be wise to implement a per-user rate limit on submissions. Meaning, if a submitter has submitted _x_ runs within the past _y_ hours, they are blocked from submitting movies until enough time has passed.

Based on a discussion we've recently had, a generally agreed on rate would be permitting up to 3 submissions within 1 week (168 hours). It might be good to make those numbers configurable by an admin somewhere.

A general idea of the implementation would be: upon going to the submission form page, check if the user has any submitted movies from between now and 168 hours ago. If the number of submitted movies is 3 or greater, then grey out or cut out the submission form, and replace it with a message that the user has to wait until (time of first submission within the range period + 168 hours) until they can submit again.

Also note: it may or may not be worthwhile to add an exemption to this limit for April Fools. It's still possible to get by if the restriction is 3 per week, but if the goal is to keep April Fools' Day uninhibited, that might require a special case.

**Comment by SamsaraTAS** [comment]
I'd like to gather some opinions from the Judges before any work is done on this.

**Comment by vadosnaprimer** [comment]
I'm fine with 3 per week (without special clauses for april fools).
