### ISSUE TITLE
Broken scrolling when clicking a table of content in the forums

### ISSUE THREAD

**Issue by g0goTAS** [TASVideos/tasvideos#1715]
Clicking on a table of contents in a forum topic for a movie submission allows you to scroll through the submission text, which normally cannot be scrolled through.

Here's a video showing it in action: https://youtu.be/cKDdoK5HNHU
Here's the page used for the demonstration: https://tasvideos.org/Forum/Topics/24897

A suggestion on how to fix it would be to expand the submission text if an option in a table of contents is clicked.

**Comment by YoshiRulz** [comment]
Video is private, but the idea is that jumping to anchors within the `<article/>` scrolls the view without triggering the "Show More" behaviour.

**Comment by g0goTAS** [comment]
Allright, the video should be unlisted now. Thanks for letting me know.
