### ISSUE TITLE
GameSubPages module creates broken links

### ISSUE THREAD

**Issue by RetroEdit** [TASVideos/tasvideos#1717]
If you look at https://tasvideos.org/GameResources/ and click for example the NES link, it will bring you to `https://tasvideos.org/GameResources/GameResources/NES` instead of what is intended, `https://tasvideos.org/GameResources/NES`. Essentially, it's inserting the parent page component to the link twice.

**Comment by Masterjun3** [comment]
Note that this only happens on
https://tasvideos.org/GameResources/ and not on
https://tasvideos.org/GameResources (without the slash at the end, which is how the site usually links to pages).
