### ISSUE TITLE
If possible provide support for .p2m2 files (PCSX2) for userfiles.

### ISSUE THREAD

**Issue by Spikestuff** [TASVideos/tasvideos#1721]
As of PCSX2 v1.7.5259 the emulator now has more sustainable syncing as long as it meets certain _known_ requirements.

As long as we know what Bios is being used (in my test case I used v2.30 [USA]), that Fast boot is Disabled. that the **memory cards are disabled** and the Emulation tab looks like this it should be fine:
![Emulation Settings in PCSX2](https://github.com/TASVideos/tasvideos/assets/12412764/c5cacaa3-b864-4b44-acb7-cb80757bafa6)

Myself and KAGE-008 have been able to validate in a single file a sustainable sync, at least on games with virtually no RNG.
So we should be able to at least see if we can provide some support in at least being able to upload that format to that site.

The only information that PCSX2 provides in the header is the Version (not to the detail I highlighted) the Author information and the Game Title.

After all we do have basic support for MAME's inp files, so why not have that same basic support and be able to host PCSX2's .p2m2 files?

**Comment by adelikat** [comment]
Do you have any docs you can link on the spec for the file format?

**Comment by vadosnaprimer** [comment]
Note: MAME .inp files are only supported as a file extension, the site does not parse its contents. Now while the request is about simply allowing by extension, I don's see the harm in adding the parser even before it's been fully approved.

**Comment by vadosnaprimer** [comment]
> Do you have any docs you can link on the spec for the file format?

@xTVaser hi, could you point us at the right file please?

**Comment by vadosnaprimer** [comment]
https://github.com/PCSX2/pcsx2/blob/master/pcsx2/Recording/InputRecordingFile.h

**Comment by vadosnaprimer** [comment]
Added to supplementary extensions so it can be uploaded, and it doesn't seem to make sense to parse them properly because movie format may change by the time rerecording is stable.
