### ISSUE TITLE
Show character length or difference in Wiki revision list

### ISSUE THREAD

**Issue by Masterjun3** [TASVideos/tasvideos#1739]
On wikipedia, e.g. https://en.wikipedia.org/w/index.php?title=Tool-assisted_speedrun&action=history it is possible to see for each revision something like `(45,010 bytes) (+689‎)`. This shows the revision length and the difference to the previous length.

One or both values would be nice to have for our Page History, e.g. https://tasvideos.org/Wiki/PageHistory?path=MovieRules because it allows you to find big edits faster.

**Comment by vadosnaprimer** [comment]
https://github.com/TASVideos/tasvideos/issues/1650?
