### ISSUE TITLE
Submission table on narrow screen

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#1741]
Unless my browser window is about 1000 pixels wide, the submission list https://tasvideos.org/Subs-List hides one or more columns on the right, and to see them I need to use the Right arrow, or drag the mouse to the right, or scroll to the very bottom of the page to move the scrollbar and then back to see the row I need.

I think it would be much better if the table went beyond the borders like game version tables do https://tasvideos.org/Games/2584/Versions/List That way there would be much more room for the table since bootstrap borders (don't remember the actual name) snap to a few fixed widths instead of being flexible, and not everyone may be aware of arrow and mouse functionality with scrolling.

**Comment by adelikat** [comment]
This was fixed, or at least, they all behave the same now, and it is the most correct behavior we can do. If we need a better global solution to tables and scrolling, let's create a different ticket
