### ISSUE TITLE
Implement Word Warp in the Submission Annotation Field

### ISSUE THREAD

**Issue by Spikestuff** [TASVideos/tasvideos#1744]
#1139 - "please use the non-code formatting tools and feel free open a new issue if the non-code formatting tools are insufficient for formatting things that aren't code"

The [Submission Annotations](https://tasvideos.org/6954S) should probably have word warping considering its small dimensions:
![image](https://github.com/TASVideos/tasvideos/assets/12412764/80340acc-05cc-4ffb-b1df-50c2e28e8eb2)

Compared to libTAS (since that's what the movie was made on) which actually has word warping this seems like a bit of an oversight on the site end.

**Comment by YoshiRulz** [comment]
`white-space: pre-wrap;` seems to work.

**Comment by vadosnaprimer** [comment]
I agree, I initially requested it to just be a code block, but forgot we don't automatically wrap lines. maybe we should in all code blocks...?
