### ISSUE TITLE
Wiki Links are not converted into text (e.g. for YouTube descriptions)

### ISSUE THREAD

**Issue by Masterjun3** [TASVideos/tasvideos#1760]
The recent PR #1750 fixing issue #1349 implemented movie titles for wiki links like `[1234S]`.

This was done by not parsing it as a simple link anymore, but as a module. Which in turn has the effect that it's now more complicated to convert into text.
In fact, for most modules we simply skip it when converting into text, which is the case here.

So it needs to be implemented.

It seems our way of converting modules to text is by adding the `[TextModule]` attribute to the module class (in this case `ViewComponents/WikiLink.cs`) and adding a `RenderTextAsync` method, which I suppose would look like
`public async Task<string> RenderTextAsync(IWikiPage? pageData, string href, string? displayText)`.

**Comment by nattthebear** [comment]
Seems reasonable.  I forget; is the textrenderer used anywhere outside of Youtube?  I'm trying to understand what all needs to be regression tested.

**Comment by adelikat** [comment]
It is just Youtube currently
