### ISSUE TITLE
Character limits on userfiles, submission game & forum topic/subject titles.

### ISSUE THREAD

**Issue by Spikestuff** [TASVideos/tasvideos#1770]
I had to know, and I now know.
![image](https://github.com/TASVideos/tasvideos/assets/12412764/4e780c9e-1859-4cb7-b04c-02f5bcc63420)

Probably a 255-character limit or something to titles?

**Comment by adelikat** [comment]
So what is a good limit for submission texts? We have some very long ones that are not abusive

Same for forum posts

**Comment by vadosnaprimer** [comment]
I think the request is only about titles/subjects?

**Comment by adelikat** [comment]
checks added to user files title, and forum post subjects
For submission game, it looks like the request is to require it? I don't agree with that.  That is a user field, and I don't feel like they should have to provide that, since it will be properly cataloged anyway, regardless of what they type

**Comment by vadosnaprimer** [comment]
It will be cataloged, but outright removing it is a very bad practice that some people do because they think we don't need it for archival purposes, and it it hasn't been cataloged by then it's annoying to try to reverse engineer the game by looking at the input file.
