### ISSUE TITLE
Server side image compression

### ISSUE THREAD

**Issue by adelikat** [TASVideos/tasvideos#182]
For screenshots, we want to run png optimization and other things on the server.

Details TBD.

**Comment by vadosnaprimer** [comment]
Pingo is the best compressor I know, crazy fast too
https://css-ig.net/

`pingo -s9 -strip path/to/file`

**Comment by TiKevin83** [comment]
I would suggest implementing imgmagick.net, that should also allow us to not have to manually create the files for additional sizes of the tierIcons

**Comment by meshuggahtas** [comment]
Pingo is Windows only and closed source.
imgmagick is cross-platform (supports Linux and Windows and runs on macOS too) and open source, so I support this software choice.

From the benchmark feos posted, Efficient-Compression-Tool would be the third suggestion based on performance results, however it isn't famous and well known as imgmagick.

**Comment by adelikat** [comment]
Coming back to this idea, better is to keep such an expensive process off the server.  Alternatives could easily be built instead, such as a process that could pull all the image files from the server, run them locally, and then upload any that decreased in size.

However, I don't know how important this is, for a few bytes saved.  Going to close this ticket, maybe we rethink this one day
