### ISSUE TITLE
Search Pager is easily missed

### ISSUE THREAD

**Issue by Masterjun3** [TASVideos/tasvideos#1820]
If you search, there is a sudden "Next" button appearing. There have been many reports that this button has been missed by users, and so they thought there was only 1 result page when there were many more.

Ideally we should use the pager we use everywhere else. If that's not possible, we should make sure users know there are more pages if there are more.

Current layout:
![image](https://github.com/TASVideos/tasvideos/assets/22375320/1920cd14-5989-4a90-80ab-779fdfa59d38)

**Comment by vadosnaprimer** [comment]
Agreed. I looked at it at some point and noticed that pagination works with URL, and it may be too complicated to make it resolve several paginations at once that way (because the search pages output several different entities).

**Comment by YoshiRulz** [comment]
It's also not clear that the prev/next buttons "turn" every category's page.

**Comment by YoshiRulz** [comment]
It's still not clear that the prev/next buttons affect every heading, but it's *less unclear* I suppose.

**Comment by Masterjun3** [comment]
I tried to do this by removing the hr's and adding a `...` to the results that still have entries.
If you have more UI suggestions you can post them.
