### ISSUE TITLE
Prevent users from making new topics in certain subforums

### ISSUE THREAD

**Issue by YoshiRulz** [TASVideos/tasvideos#1826]
Users aren't meant to manually create topics in subforums like Workbench or Gruefood. Maybe we should prevent this.

The impetus for this was a user posting in the automated pubs subforum.

**Comment by SamsaraTAS** [comment]
How about we actually have a discussion about this?

**Comment by adelikat** [comment]
My proposal is a flag on the subforum that would prevent users to creat topics in that subforum, we would set this flag on the "Completed Movies" subforum.

Other than creating topics, is there anything special it needs to prevent?

**Comment by Masterjun3** [comment]
I think yes, it would be enough to only prevent topic posting, (and hiding the "+ New Topic" button).
And then I think it's meant to be set on all of the currently 4 subforums in the "Completed movies" section.
