### ISSUE TITLE
Blank Screen on login/logout shenanigans

### ISSUE THREAD

**Issue by nattthebear** [TASVideos/tasvideos#183]
1.  Log in as user C in tab A
2. Open tab B.
3. Log out of User C in tab B.
4. Log into user D in tab B.
5. Click the logout link in tab A.

Expected:  You are either logged out, or nothing happens and you reload the page with the right user shown.
Actual:  You get an HTTP 400 and an empty document.

**Comment by adelikat** [comment]
Looks like this scenario is hitting an error with the AntiForgeryToken.

This might be the "fix": https://stackoverflow.com/questions/34468340/httpantiforgeryexception-occurs-with-multiple-login-tabs

**Comment by adelikat** [comment]
Unfortunately this is a controller based fix.

[IgnoreAntiforgeryToken] "fixes" the issue, but I don't know if that's a kosher thing to do on a logout action.

Looking around I did find a possible alternative: https://github.com/aspnet/AspNetCore/issues/3616
Specifically this:
services.AddAntiforgery(options =>
{
    options.ValidationFailedResultHandler = ctx =>
    {
        ctx.Response.Redirect("/anti-forgery-error");
        return Task.CompletedTask;
    };
});

Ideally there's a way to see the original request path and if logout, redirect to log in, otherwise do the default behavior.

**Comment by nattthebear** [comment]
> but I don't know if that's a kosher thing to do on a logout action.
I don't think it is.  Just redirecting home would probably be fine here, maybe for all cases of antiforgery failure

**Comment by adelikat** [comment]
I don't think I agree with this being critical or 2.3, it's not a typical behavior, and the consequences are somewhat confusing but can be remedied by the user pretty easily

**Comment by adelikat** [comment]
Dropping the criticality of this bug, it involves logging in with multiple accounts (which a normal behaving user wouldn't be doing anyway) and some shenanigans with different tabs to recreate.

**Comment by meshuggahtas** [comment]
Observation: double logging out what causes a one time problem after logging in.

Repro:
1. Tab 1 - Login https://tasvideos.org/Account/Login
2. Open another tab (Tab 2) and logout
3. Tab 1 - Logout
4. Tab 1 - Login

After this you are presented with an empty or HTTP 400 error page. After this everything will work fine.

**Comment by Masterjun3** [comment]
We disabled the AntiForgeryToken for the Logout Button to allow the browser to cache pages (the Logout button is on *every* page if you're logged in, so it prevented all caching, making for a bad browsing experience).

Incidentally the change fixed this issue.
