### ISSUE TITLE
Turn stars from class into a movie flag

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#1877]
Obviously I can create a new flag with an icon, but assigning that flag to all movies currently in the Stars class would be a nightmare. Also that class is coded to increase rating weight, might be cool if the flag was able to do it. Actually moving current star runs to proper classes might take a while too.

**Comment by adelikat** [comment]
snagging this one, I know what to do

**Comment by adelikat** [comment]
DONE!
