### ISSUE TITLE
Ability to open site search page from middle-click

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#1878]
Search is a button that brings you to the search page, and if you've entered anything when hitting it, it will show results. But sometimes search needs to be done in a separate tab, and there's no way to open it as a new tab by middle-clicking the search button.

**Comment by Randomno** [comment]
https://github.com/Randomno/tasvideos/tree/middleclick

Don't want to PR this but it works

**Comment by adelikat** [comment]
Doing this via javascript is the wrong way to go.  I'm not sure the right way though, it's a form button due to the text box, you can't middle click that into a new tab, it isn't how HTML works
