### ISSUE TITLE
Prevent forum embeds linking out to a YouTube short (when it occours).

### ISSUE THREAD

**Issue by Spikestuff** [TASVideos/tasvideos#1879]
Honestly don't know if it's possible, [but I noticed it here](https://tasvideos.org/Forum/Posts/511171).

**Comment by nattthebear** [comment]
The forum markup was:

```
[video=384x540]https://youtu.be/WjkUz31hwms[/video]
```

The generated HTML was:

```html
<iframe width=384 height=540
src="https://www.youtube.com/embed/WjkUz31hwms"
frameborder=0
allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
allowfullscreen
class="mw-100"></iframe>
<a href="https://youtu.be/WjkUz31hwms" rel="noopener external">Link to video</a>
```

Everything seems to be working correctly, and the video loads fine on my browser.  What's the problem here?

**Comment by adelikat** [comment]
Is this request to stop the ability to embed? why? If someone wants to link it, we would want that functionality to work, which it seems to do

**Comment by YoshiRulz** [comment]
The links in question are in third-party code.

**Comment by nmain** [comment]
It's iframed in the same way that all other youtube videos and other video embeds are.  If we'd like to create a `frame-src` CSP, it will need to include youtube.com and our other video embed sources.
