### ISSUE TITLE
Star icon doesn't appear on obsoleted movie in pub history

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#1901]
https://tasvideos.org/Games/PublicationHistory/29?highlight=317

`NES Rygar "no warp glitch" by Walker_Boh in 20:26.70 (05.04.2005)` has a star but it doesn't appear. Current star does appear on SMB tho:

https://tasvideos.org/Games/PublicationHistory/1?highlight=3728

**Comment by adelikat** [comment]
I can't put stars on the history page specifically but I can put _all_ flags.  Does this work?

**Comment by vadosnaprimer** [comment]
Yes!
