### ISSUE TITLE
Unable to upload any libTAS movie files

### ISSUE THREAD

**Issue by bigbass1997** [TASVideos/tasvideos#1909]
When uploading seemingly any .ltm file, either to a submission or userfile, the site returns a generic error message:
> A general error occured while processing the movie file.

I've tested using a couple previously published movies ([6021M](https://tasvideos.org/6021M), [4742M](https://tasvideos.org/4742M)) and Randomno has also tested others. I did successfully check to ensure uploads are still working in general, using an FM2 movie.

**Comment by adelikat** [comment]
this has been fixed, according to reports, the remedy was to simply redeploy the same code, so we aren't sure what exactly happened
