### ISSUE TITLE
Automate the per-platform movie table

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#1910]
https://tasvideos.org/Movies

First tab. We have to add the links manually every time a new platform appears.

Per-class links are not always there, but I think it makes sense to show them as long as they're not empty.

Stars are a flag now, but I'm not sure if it's worth removing it from that table yet. They work as a good way to promote cooler movies right away.

**Comment by adelikat** [comment]
For anyone looking to pick this up, we simply need a wiki module

**Comment by YoshiRulz** [comment]
> Per-class links are not always there, but I think it makes sense to show them as long as they're not empty.

Are you suggesting the module should include those unconditionally, or that it should do extra checks?

**Comment by vadosnaprimer** [comment]
> Are you suggesting the module should include those unconditionally, or that it should do extra checks?

If the sub-list is not empty, link to it.

**Comment by YoshiRulz** [comment]
This was implemented and is ready to be used on `/Movies`:
![after](https://github.com/user-attachments/assets/f0023a64-8eff-4c9a-8f5a-ec7baae554db)
Compare to the existing, manual table:
![before](https://github.com/user-attachments/assets/aed13ffc-4615-41ce-8ad4-c5d930a6cb9f)

Checking for empty categories and omitting those links was *not* implemented.

As I posted under the PR, the existing groupings become:
```
[module:PublicationsByPlatform|groupings=A2600-A7800,Jaguar-JaguarCD,GB-SGB-GBC,DOS-DOOM-Windows-Linux,MSX-SVI3x8,NES-FDS,N64-N64DD,DS-DSi,Genesis-32X-SegaCD,SMS-GG-SG1000,SNES-BSX,PCE-PCECD-SGX]
```
