### ISSUE TITLE
If a Publication has No Rating display "No Rating" or "Unrated" instead of a 0/10 score.

### ISSUE THREAD

**Issue by Spikestuff** [TASVideos/tasvideos#1933]
Basically avoiding an accidental misconception about the rating to a Publication:
![norating](https://github.com/user-attachments/assets/55a63ab2-53ce-4ac2-86fa-2e131961d175)

**Comment by YoshiRulz** [comment]
Easy enough:
```diff
-<i class="fa-regular fa-star"></i> <span id="overallRating-@(Model.Id)">@((Model.OverallRating ?? 0).ToOverallRatingString())</span> / 10
+<i class="fa-regular fa-star"></i>
+@if (Model.RatingCount > 0)
+{
+	@:<span id="overallRating-@(Model.Id)">@((Model.OverallRating ?? 0).ToOverallRatingString())</span> / 10
+}
+else
+{
+	@:&mdash;
+}
```
But why are these even 2 separate buttons? They're hardcoded to go to the same page.

**Comment by Masterjun3** [comment]
First button only shows when logged in, shows your rating when you have already rated, and for scripters it allows inline rating.
