### ISSUE TITLE
Cannot Receive SSL Certificate Validation

### ISSUE THREAD

**Issue by Invariel** [TASVideos/tasvideos#1949]
Three months ago, there was an issue with updating the site's certificate -- our domain registrar made a change to their policies about who could access their APIs: customers with 20+? 50+? -- it was three months ago, I forget the exact number -- registered domains.  Needless to say, we aren't going to purchase a bunch of domains just to regain API access.  We were able to find a workaround: writing a file to .well-known/acme-challenge/some_elsewhere_determined_filename.  This worked.

adelikat and I set up a reminder for the 15th to check that things were working smoothly and that our certificate was re-issued correctly.  This failed.

Our wiki engine is rejecting the URL for the certificate challenge.  My initial testing shows that writing a file to `.well-known/acme-challenge/1234567890.txt` results in the file being returned, but writing a file to `.well-known/acme-challenge/1234567890` results in a wiki error and a failure page.

We cannot change the file that the remote service uses to validate our website.  The remote service needs to be able to verify that the file is there in order to issue us a new certificate.

Our certificate expires at some point on August 27th.  This issue needs to be resolved by then.

**Comment by YoshiRulz** [comment]
Was this fixed by https://github.com/TASVideos/tasvideos/commit/f33b1ad30d9dbf243a5943eb33353f8b5505eed4 through https://github.com/TASVideos/tasvideos/commit/0a4861b4e9a5628d7fd52b7b201430407bcc81a9?
