### ISSUE TITLE
Goal editing may be somewhat broken

### ISSUE THREAD

**Issue by RetroEdit** [TASVideos/tasvideos#1956]
I updated the goal for https://tasvideos.org/6313S to "no training levels" for further clarity on the rejected submission, but it's still displaying the goal as baseline. But if you click into it, you can see that the text field has the text `no training levels` that I entered.

**Comment by CasualPokePlayer** [comment]
This is because the goal cataloged was baseline.

Editing the submission does not change the goal cataloged, you have to explicitly use the Catalog button.

**Comment by adelikat** [comment]
the text field is for submitters to put whatever they want, and does not constitute catalogging

**Comment by RetroEdit** [comment]
There are two places with goal information: the top of the page and the gridded table.

The grid table still shows up as `baseline` even if the submitted field is changed, which I think is a bug. Unless the submitted text is not intended to be displayed at all in a public-facing way, which makes very little sense to me.

**Comment by adelikat** [comment]
Submitted goal is supposed to show, if there is not a catalogged goal.  Once someone has catalogged it, thats' the goal we want to show, not what the author submitted

**Comment by adelikat** [comment]
would it help if the labeling consistently said "Submitted Goal"?

**Comment by RetroEdit** [comment]
Two-ish questions: 1) is the value in the table supposed to always reflect the submitted goal, or is it supposed to be overridden once cataloged? 1a) (Presumably the value in quotes at the top of a submission is supposed to reflect the cataloged goal.) 2) If it is supposed to override were basically all submissions cataloged as baseline at some point?

If the labeling said `Submitted Goal` that would seem to be inaccurate with the current state where cataloging overrides submission fields.

**Comment by RetroEdit** [comment]
Here's my revised thoughts: currently if the game name changes, it will list the submitted name underneath in a parenthetical.

https://github.com/TASVideos/tasvideos/blob/59225ec7029475ddb5399d1dbba3b7ff91bb5f84/TASVideos/Pages/Submissions/View.cshtml#L105

I think the same should be done for Goal.

**Comment by vadosnaprimer** [comment]
> If it is supposed to override were basically all submissions cataloged as baseline at some point?

When goals were implemented, they are automatically created from existing branch labels.

> I think the same should be done for Goal.

Possibly.
