### ISSUE TITLE
Reviewers can no longer edit submissions

### ISSUE THREAD

**Issue by RetroEdit** [TASVideos/tasvideos#1977]
I have the ~~Editor~~ Reviewer role, and I noticed with recent site changes I'm no longer able to edit submissions where I was able to prior. Presumably this is a result of some recent site change, possibly related to sync verification.

I can still edit publications.

Looking at a Wayback Machine snapshot of the site from 2024-05-20: https://web.archive.org/web/20240520153242/https://tasvideos.org/Roles/List you can see Reviewer had the `Edit Submissions` permission, but now it seems to have been replaced with `Catalog Movies`, maybe intentionally?

Based on when my last submission edit was, I think the change would have to be somewhere in here, but I couldn't pinpoint it: https://github.com/TASVideos/tasvideos/compare/dd7060e44d60...237d2e3f4ef3

**Comment by YoshiRulz** [comment]
Roles' permissions are data, not code.

(adelikat said this particular permission removal was intentional.)
