### ISSUE TITLE
Page View Count Statistics?

### ISSUE THREAD

**Issue by Masterjun3** [TASVideos/tasvideos#1981]
Do we want this? I kind of want this.

We removed the view counts from topics, because they didn't fit in the table for mobile devices. And so we also removed the functionality altogether.

But now, I kind of want to see how many people visit what pages over the entire site. Personally, I do like improving pages that are visited often. Maybe we'd even see some surprisingly popular pages? I don't know exactly what this would help with. But I like it when numbers go up.

In terms of possible implementation, adelikat would throw me out the window if I added a DB call to every single page visit. But caches are fine. So basically an idea is, we cache the counts for a while, and then only occasionally do we write them to the DB.

But again, the first question, do we want this?

**Comment by vadosnaprimer** [comment]
I feel it's cool to have, but I don't have a clear idea what it helps with.

**Comment by Masterjun3** [comment]
By adelikat:
> if there is some kind of telemetry data I wouldn't hate it.  But if we start rolling our own that goes to the database, I strongly oppose
