### ISSUE TITLE
Have a way to hide wiki diff while editing

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#1993]
When you do a lot of edits and you need to see how they will look, you'll need to scroll back and forth between source and preview, and the diff view is in-between and takes extra time to scroll every time. Depending on how heavy the edits are, it may get huge, and it's not often needed. When it is, it's better to show it explicitly upon request. A simple down arrow folding thing would be fine IMO (like the one that shows subpages, except hidden by default (like news).

In theory this could be useful in forum editing too, but it's much less frequent to reformat a forum post, while in wiki it's regular activity.

**Comment by YoshiRulz** [comment]
see also #1876
