### ISSUE TITLE
[F.Rq.] Warn when necro-posting

### ISSUE THREAD

**Issue by YoshiRulz** [TASVideos/tasvideos#1996]
Edit by @Masterjun3 : 
> **necropost**: To post to a long, inactive discussion thread on a forum.
<hr>

Game tech discussion tends to be *very* asynchronous, so maybe limit this to certain subfora.

I think having a modal appear when clicking the "New Post" button would be ideal, but it would also work as plain text beside the button, and using either approach on the editor page would also work.

see also #1460, #1596

**Comment by vadosnaprimer** [comment]
I don't understand this request. First of all, necro-posting is encouraged, to keep everything in one place. Second, what does "game tech" mean, and how to we detect it? Third, I don't know what a modal text should be saying.

**Comment by YoshiRulz** [comment]
re: 1) and 2), I appreciate that necro'ing is encouraged for topics about individual games, hence my suggestion to conditionally show the warning based on the subforum.

The text could be as simple as "The last post in this topic was X years ago, are you sure you want to post? [Cancel] [Post]"
or maybe with three options "[Cancel] [Post in new topic] [Post here]"

**Comment by bigbass1997** [comment]
Can you give some examples of subforums thus would apply to, and why necro-ing threads would be bad in them?

**Comment by vadosnaprimer** [comment]
Sorry I still don't know what this request is meant to accomplish. Creating a new topic for something that already has one is **bad**, we've been merging similar threads at mass in the past.

**Comment by YoshiRulz** [comment]
Anywhere topics are typically in a question-and-answer format, but locking the topic feels too heavy-handed (or is too much moderation work): The Newbie Corner and all the emulator subfora, maybe Encoders' corner and Site.

I don't mind being overruled here since my forum usage patterns involve having most notifications off.

**Comment by vadosnaprimer** [comment]
> Once the problem/inquiry has been resolved, the participants would probably expect no further notifications from the topic.

Doesn't feel like a common problem. Some threads are for basic questions, but if someone finds a 5 year old thread with a basic question and makes a post in it, I've never seen that post contain an entirely different unrelated question. Usually it's either a new thread for a new question, or reusing an old thread for asking for further details.

**Comment by Masterjun3** [comment]
It seems staff does not want this feature, or even considers a feature like this counterproductive. So I'm closing this as not planned.
