### ISSUE TITLE
Issue with DSM movies parsing. Parser assumes run starts from savestate even though it doesn't

### ISSUE THREAD

**Issue by McBobX-1** [TASVideos/tasvideos#2006]
So I just submitted my DS TAS to the site couple minutes ago, and the submission says that it starts from savestate, which is not. Input file also indicates that it doesn't (savestate 0).
Link to submission: https://tasvideos.org/9336S

**Comment by CasualPokePlayer** [comment]
The exact issue at least appears to be between 0.9.11 and 0.9.13 savestate anchored movies changed. The savestate key previously was meant for the actual savestate, embbed into the movie file (and so if the key is present, a savestate is present). With 0.9.13, the savestate is a separate file, and the savestate key is just for indicating if a savestate is present or not (so the key will be present regardless of whether a savestate is present or not)

**Comment by adelikat** [comment]
Wow! That's a terrible regression for the .dsm format, I'd recommend we not even accept savestate anchored movies after 9.11
