### ISSUE TITLE
Allow the site to parse GBAL systems as GBA

### ISSUE THREAD

**Issue by gabraltar** [TASVideos/tasvideos#2053]
TASVideos normally parses GBL as GB as shown here (https://github.com/TASVideos/tasvideos/blob/6d5a46b9e8eb6b6d5be6c65292c7673c62df31cc/TASVideos.Parsers/Parsers/Bk2.cs#L276-L279). However, such support doesn't exist for GBAL yet and thus, movies using GBAL cannot be submitted.

**Comment by Masterjun3** [comment]
Resolved by #2055 .
