### ISSUE TITLE
Wiki Markup:  How to make a text link to an image

### ISSUE THREAD

**Issue by nattthebear** [TASVideos/tasvideos#218]
The goal is simple: make a link whose `href` points to an image (and so ends with `.png` or another well known image extension), and whose body is plain text:

```
<a href=http://example.com/foo.jpg>Link To Foo</a>
```

Neither the old nor the new wiki directly support this.  The logic looks something like this:

Split the contents of the `"[...]"` by `"|"` into `pp[0]`, `pp[1]`, ...

* `pp[0]` looks like a link and `pp[1]` looks like an image => Make a link to `pp[0]` with `pp[1]` as the link body
* `pp[0]` looks like an image => make an image
* `pp[0]` looks like a link => make a link
* (Other lower priority cases that won't help follow...)
 

None of those give the desired result.  The essential problem is that if the first thing in the [] looks like an image, it will be an image unless the second thing also looks like an image, but then you can't have a text link.

In both cases, old and new, you can trick "looks like an image" by putting a space at the end of the link.  Example page: /SiteHistory/EncoderLogos

Can we do something better about this?

**Comment by nattthebear** [comment]
Since #217 has been closed and we won't be supporting it, we could resolve this by using something like `[=http://example.com/foo.jpg|Link To Foo]`.  If we did, we wouldn't be able to do that until post release, since until then, people might still be using it to mean the old thing on the old site.

Forgetting this entirely until #219 seems better though.

**Comment by nattthebear** [comment]
As was pointed out by others, you can do this in the current site with the space trick:

```
[http://example.com/foo.jpg |Link To Foo]
```

Leaving open as something we might consider doing better for #219

**Comment by vadosnaprimer** [comment]
Missed this somehow. I think proper approach to this is disabling image embedding entirely if it's a _text that links_ to the image. If the user wants an image, they just embed it right away. If it's _some other kind of text_, images have `alt` and `title` arguments, so nothing breaks.

**Comment by adelikat** [comment]
@nattthebear : what do you think of @vadosnaprimer 's suggestion?

**Comment by nattthebear** [comment]
Are we saying that we don't want to link to images ever?  That seems surprising.

**Comment by vadosnaprimer** [comment]
> I think proper approach to this is **disabling image embedding** entirely **if it's a text** that links to the image.

**Comment by nattthebear** [comment]
I'm still having a lot of trouble understanding what you're proposing.  What's "if it's a text that links to the image"?  There is no such thing in the live site as text that links to the image, that's the entire question being asked here.  If we want to define something as that then we have to undefine something else.  `[https://cool-site.com/image.png|here's the link]` is an embedded image in the live site and it's not clear to me how we could change that without some backwards compatibility failure.

**Comment by vadosnaprimer** [comment]
If an image link has a replacement text, don't embed the image. Is that an impossible check in the current code?

**Comment by adelikat** [comment]
I think what is being asked is:
[foo.png] = show image
[foo.png|title=bar"] = show image with tooltip bar
[foo.png|right] = show image (right aligned
[foo.png|Some description] = show a link to image with description as text, ie: <a href=foo.png>Some Description</a>

**Comment by vadosnaprimer** [comment]
Yes.

**Comment by nattthebear** [comment]
Got it.  So by "replacement text", I think we mean anything that's not one of the six case outlined here:  https://github.com/TASVideos/tasvideos/blob/f5630b89c8bbad3d4d305d48549e651b7f4a399e/TASVideos.WikiEngine/MakeBracketed.cs#L271

That makes sense.  Such a text fragment would be meaningless to an image embed, so there'd be no reason to use it for that.

I'll put together a PR.
