### ISSUE TITLE
HTML in forum signatures discussion

### ISSUE THREAD

**Issue by nattthebear** [TASVideos/tasvideos#237]
The raw text of Bisq's signature in the 1.x database is exactly this:

```
<a href="http://glc.us.com/"><img src="http://media.tasvideos.org/h6425081281317.png"></a>
```

Attempting to put that in a post in the 1.x forum causes the 1.x post rendering code to emit the following to the browser (as raw HTML):

```
&lt;a&gt;&lt;img&gt;&lt;/a&gt;
```

IE, when interpreted as HTML, the following plain text with no actual HTML markup in it:

```
<a><img></a>
```

So it isn't supported at all in 1.x.  The 1.x forum HTML parser does do... something to it, because the attributes are stripped from the tags.  But then the tags are output escaped to raw text, so clearly it didn't work.  To further confuzzilate things, in 1.x at the moment HTML is hardcoded to _off_ when editing a forum sig.  It's not clear if this was always the case.  The 1.x forum db storage for posts stores them in a partially prebaked form, where some parsing and escaping has already happened, so we can't be 100% sure what the original markup entry was always.  Using `[url]` tags and `[img]` tags, you can recreate what Bisq wrote without HTML, and that seems to work fine in the 2.x forums.

What, if anything, do we do about this?  Probably nothing until we see a survey of signatures and what's actually in them and how many are broken.  But with the prebake, and the fact that this does not work right now on the 1.x site, it's hard to figure out what the right thing to do would even be.

**Comment by nattthebear** [comment]
There's some evidence that Bisq may have directly poked raw HTML to the forum DB table, bypassing some of the parsing and escaping layers of phpbb and allowing, effectively, for "self-html injection", as there are a few posts authored by him with extravagant markup that there seems to be no way to recreate.  For example:

http://tasvideos.org/forum/viewtopic.php?p=230830#230830

**Comment by adelikat** [comment]
I'm okay with these posts simply being broken in the new code base.  We can manually fix the posts if desired or let them look bad

**Comment by vadosnaprimer** [comment]
That post can trivially be turned into a simple code embed, which is the proper approach anyway.

**Comment by TiKevin83** [comment]
is this done then or do we need to do more to enhance forum signatures?

**Comment by nattthebear** [comment]
Let's ignore this until someone complains about their signature being broken.
