### ISSUE TITLE
Forum/MoodReport - add post counts of each usage

### ISSUE THREAD

**Issue by adelikat** [TASVideos/tasvideos#248]
for each user's mood avatar, show the count of instances they used it

**Comment by adelikat** [comment]
Do we even care about this? I wrote this ticket because it was old site functionality, but do we care about such stats? seems useless

**Comment by SamsaraTAS** [comment]
As someone who used the mood report, I always considered it just a one-time curiosity, not really worth the resources to re-implement it on the new site in my opinion. Pardon me while I c/p this to the other issue.

**Comment by vadosnaprimer** [comment]
Post count itself doesn't mean much IMO, the feature was linking to posts that used that avatar. But it's incredibly rare, so if somebody needs it it can be a different issue.
