### ISSUE TITLE
Forum/MoodReport - link to usages of each mood

### ISSUE THREAD

**Issue by adelikat** [TASVideos/tasvideos#249]
for each user's mood avatar - provide a link that will go to a page displaying the topics they used the mood in

**Comment by vadosnaprimer** [comment]
*posts

**Comment by adelikat** [comment]
Do we even care about this? I wrote this ticket because it was old site functionality, but do we care about such stats? seems useless

**Comment by SamsaraTAS** [comment]
As someone who used the mood report, I always considered it just a one-time curiosity, not really worth the resources to re-implement it on the new site in my opinion. Pardon me for c/ping this from the other issue.

**Comment by vadosnaprimer** [comment]
Oh it **was** a different issue, lol. Yeah most of the time it's just curiosity. The only example when it may be needed is when you remember someone made a post with a certain avatar and you want to find it, but don't remember the content to do a text search. But rarity is extreme, so I'd wait for a few new requests that demand it back.
