### ISSUE TITLE
Send Message to user when auto-assigning a role

### ISSUE THREAD

**Issue by adelikat** [TASVideos/tasvideos#252]
When auto-assigning a role to a user, generate a private message to the user from TASVideoAgent letting them know and breaks down the new permissions

**Comment by vadosnaprimer** [comment]
And include links to relevant wiki pages that need to be examined.

**Comment by meshuggahtas** [comment]
Relevant issue https://github.com/TASVideos/tasvideos/issues/147

**Comment by adelikat** [comment]
Closing this as a duplicate of #147
