### ISSUE TITLE
Unpublish a movie

### ISSUE THREAD

**Issue by adelikat** [TASVideos/tasvideos#259]
Mistakes happen.  We should have a very resitrcted privilege to remove a publication.

Perhaps we want to only allow this within 24 hours of a publication? To restrict it to mistakes and not for removing "outdated" publications

**Comment by vadosnaprimer** [comment]
Actually deciding on unpublication is a very tricky subject. See http://tasvideos.org/forum/viewtopic.php?p=472406#472406 as well as the rest of the thread.

**Comment by adelikat** [comment]
I built this one!

**Comment by ThunderAxe31** [comment]
Wouldn't be better to simply mark a publication page as "hidden", so that it can only be found and seen by staff members?
