### ISSUE TITLE
Group approval for dangerous changes

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#262]
Some things can be very meaningful/important, so giving any single user ability to remove them may be dangerous. It would be interesting to require several users to confirm removal for certain things to actually get it wiped. Then there can be several levels of wiping: hiding from users, hiding from staff, hiding data from the site but keeping a backup, and finally actually getting completely rid of it.

**Comment by adelikat** [comment]
I'm not sure this makes sense anymore.  We aren't going around deleting things and there is good staff discussion before retiring features.  And good discussion before majorly refactoring wiki pages and such.

Unless there are objections, I'm going to go ahead and close this ticket in a few days

**Comment by adelikat** [comment]
Closing for reasons stated above
