### ISSUE TITLE
Remove references to JudgingsByJudge module

### ISSUE THREAD

**Issue by adelikat** [TASVideos/tasvideos#269]
/HomePages/feos as an example of its usage

**Comment by vadosnaprimer** [comment]
The judge module will become obsolete, if judge activity needs also contains _claimed but unjudged_ submissions (which is what I use the module for). And if there;s due linking #521

**Comment by adelikat** [comment]
Yes, claimed movies will show up

**Comment by adelikat** [comment]
Retitling this, we will remove references to the module and use Activity pages instead

**Comment by adelikat** [comment]
References replaced with links to Activity pages
