### ISSUE TITLE
Allow TOC to point to tabs

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#280]
TOC can only see/link to headers, and headers aren't the only way to organize a page. Tabs are incredibly helpful too, and they allow to organize it better in many cases. But we can't link to tabs right now.

**Comment by nattthebear** [comment]
TOCs are automatically generated, so this wouldn't be "allow" but instead "force", no?

**Comment by vadosnaprimer** [comment]
Yeah probably.

**Comment by nattthebear** [comment]
This would be quite a change to existing pages, but as long as you're sure it's for the better, I can give it a look.

**Comment by vadosnaprimer** [comment]
I had this cute page
http://tasvideos.org/wiki.exe?page=EncodingGuide/PublicationManual&rev=128
I needed to have some links to its chapters and had to turn it into this madness
http://tasvideos.org/EncodingGuide/PublicationManual.html

Strictly speaking, if there's a way to link to tabs, it doesn't even have to be in the TOC (tho won't that be messier to implement and maintain?)

**Comment by nattthebear** [comment]
Haven't we been over this before?  The "cute" page is absolutely horrid and the "madness" is a reasonably outlined page.

Tabs mean I need to click things while I'm reading.  Tabs have poor accessibility and break outline views.  Tabs mean I can't see two related adjacent sections on the screen at once, because they're hidden.  Show me somewhere else on the internet where informative encyclopedia-like articles hide most of the data behind tabs within the body of each article.

**Comment by nattthebear** [comment]
Almost forgot, tabs require javascript, and while javascript is ubiquitous these days, requiring javascript crap to fire just to read basic article text is still a really annoying movie

**Comment by vadosnaprimer** [comment]
In some cases you do want to hide stuff:
http://tasvideos.org/Search.html?key=%22TAB+Hide%22&subs=1&nomovs=1
Since there's no expandable spoiler on tasvideos, people do it via tabs. In other situations it's a matter of taste. Having all the main chapters right in front of you at the same time helps to quickly navigate between them, while TOC requires scrolling to the top every time.

The part we've been through is some of the headers that TOC wasn't recognizing, and I think it was resolved by simply allowing more header types and differentiating them more.

**Comment by vadosnaprimer** [comment]
> Almost forgot, tabs require javascript, and while javascript is ubiquitous these days, requiring javascript crap to fire just to read basic article text is still a really annoying move.

Is there a way to know how many people have it disabled, or maybe we should just ask? Makes sense to support the noscript people, but I bet they're in vanishing minority.

**Comment by adelikat** [comment]
I'm with natt, I don't think this is a real feature.  It's a hack to support a poorly designed wiki.  Use outline views, and make subpages, and keep content manageable on a single page
