### ISSUE TITLE
Wiki diff "Full View" checkbox

### ISSUE THREAD

**Issue by adelikat** [TASVideos/tasvideos#281]
It would be nice to have a "full view" checkbox on the relevant pages, that when clicked shows all the lines of text, not just the diffs.

In the code, this would be passing in null for the contextSize instead of a number.

The following pages are relevant here: Diff, EditHistory, PageHistory
While we are at, these pages have a lot of copy pasta that could be consolidated

**Comment by vadosnaprimer** [comment]
Ability to change that number on the fly would be interesting too!

**Comment by nattthebear** [comment]
Hmm, so the new diff viewer is full view all the time.  Which I guess fixes this?  Unless we need the limited view as well.

**Comment by vadosnaprimer** [comment]
I didn't realize the new diff comes with full view at all times. On huge pages, finding what was changed may be a problem, especially when you need to do it repeatedly on different revisions. Full view needs to be optional.

**Comment by nattthebear** [comment]
https://github.com/TASVideos/tasvideos/pull/1151
