### ISSUE TITLE
Different BG color for monospace

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#329]
It'd be awesome if a different BG color was used for monospace font in the wiki (things like starting with a space and `{{these}}`), like some darker grey or maybe white? We will need A LOT of small code embeds, including inline, on pages like https://tasvideos.mistflux.net/EmulatorResources/PCem/DOS and it's very hard to spot what is regular text and what is exact internal strings. When reading such stuff, it helps a lot if code is highlighted, because that serves as attention anchors of some kind.

Wiki `> quote` syntax has some nice darker grey that could be used here.

If the line starts with a space, the entire line's BG can be changed, and if it's `{{}}` then only of the text within the tag

**Comment by nattthebear** [comment]
> If the line starts with a space, the entire line's BG can be changed, and if it's {{}} then only of the text within the tag

`{{` doesn't have separate inline vs block treatment depending on whether it starts a line; it always generates an inline tag.  The old parser also behaves this way.

**Comment by vadosnaprimer** [comment]
I mean starting a line with a space is how you enable monospace for the whole line, and `{{}}` is for inline. So those are the things that would need different treatment here.

**Comment by nattthebear** [comment]
Ahh, right.  That is supported in the new parser, and generates similar markup to the old parser, so the only thing that needs to be done here is, throw in the styles.

**Comment by vadosnaprimer** [comment]
Unfortunately I don't know css enough to even hack the existing thing just to see how it would look. Though I'm seeing that the `>` tag is probably not supported on the new site? https://tasvideos.mistflux.net/TextFormattingRules#Emphasis

**Comment by vadosnaprimer** [comment]
I noticed that it uses different font on inline and full-line monospace.
https://tasvideos.mistflux.net/EmulatorResources/PCem/DOS/Configurations
https://i.imgur.com/YrBJ4xa.png

I think the font should be the same.

**Comment by adelikat** [comment]
To your last point about different fonts, it is different on the prod site too

**Comment by vadosnaprimer** [comment]
With default firefox fonts, I don't see the difference
https://i.imgur.com/EXsh5c4.png

**Comment by vadosnaprimer** [comment]
The same request goes for the `tt` tag on forum.
