### ISSUE TITLE
Submenu goes OOB

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#334]
https://i.imgur.com/YN6oRW0.png

This adds a horizontal scrollbar too. Shouldn't appear partially beyond the browser view that it did fit otherwise.

**Comment by meshuggahtas** [comment]
Is this still relevant? The menu have been changed, so the right side should always have Register Log in Search, giving enough space for dropdown menus.

**Comment by vadosnaprimer** [comment]
Indeed.
