### ISSUE TITLE
Forum posting - mood avatar preview

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#340]
When making a post, it'd be amazing to have a way to preview your mood avatar, at least the one you've selected.

**Comment by meshuggahtas** [comment]
Currently, single avatar can be checked @ Profile. Mood avatars can be as many as the user provided, so it would be better to enhance the forum post preview to show your "forum profile" as in your name+avatar+rank+location etc.

Current forum post preview
![preview](https://user-images.githubusercontent.com/31288337/150095709-b3612195-c6c2-458d-b116-01f66031f729.PNG)
