### ISSUE TITLE
Ability to view (links to) all screenshot descriptions on one page

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#355]
If we ever want to organize them, we should be able to find them. Is there any GUI way right now that I'm missing?

**Comment by adelikat** [comment]
There is currently no way to do that.  Would be a pretty easy wiki module to throw together

**Comment by meshuggahtas** [comment]
Is this still relevant after removal of screenshot hover texts?

**Comment by vadosnaprimer** [comment]
Hover texts weren't removed.
