### ISSUE TITLE
GUI to manage game versions

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#356]
Game versions (unknown/any/USA/Dendy/PRG0/r1/etc) have always been a mess. If we want to organize them, we need a way to see all movies (submissions, userfiles?) a given version is present in. For example, unknown is default, and it often doesn't get updated when publishing, so we may wanna check where it actually belongs and fix the rest. Maybe there's already GUI I'm missing.

**Comment by adelikat** [comment]
Nice idea for the future
