### ISSUE TITLE
Replace all overflow-y scrolls

### ISSUE THREAD

**Issue by Masterjun3** [TASVideos/tasvideos#399]
This is a debatable design feature. Currently, there are several elements with a maximum height, which show content in a scrollable block if the height exceeds the maximum value.

I personally agree with the feedback on the forums that this should be replaced with a different design. The block-scrolling can interrupt page-scrolling, and this is especially noticable on mobile devices where actual page-scrolling is only possible on the side edges of the screen.

For small limited blocks such as the featured movie or the news on the front page it should be asked if it's even necessary to limit the height. 
For potentially larger blocks such as the submission text, a friendlier solution would be a label at the bottom saying "Read more", which when pressing displays more of the content.

**Comment by nattthebear** [comment]
I'm tentatively in agreement, but it'd be nice to see some design proposals.
