### ISSUE TITLE
Add an option for the judge to subscribe to submission thread

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#404]
It'd be nice to have a checkbox somewhere, to automatically subscribe to the thread of the submission you're judging. Needs to remain an option tho.

**Comment by adelikat** [comment]
What if the claim button automatically did this?

**Comment by vadosnaprimer** [comment]
In case someone writes a manual claim message and changes the status manually, subscribing manually can be missed. If it's really annoying to set up to not depend on the button, then the button is ok. Just has to remain an option even then.

**Comment by vadosnaprimer** [comment]
I talked to judges and they actually don't mind if the Claim button just subscribes them to the submission thread, without it being optional.

**Comment by adelikat** [comment]
Should publishers subscribe too when they claim for publishing?
