### ISSUE TITLE
Staff page is missing users and edit count

### ISSUE THREAD

**Issue by bigbass1997** [TASVideos/tasvideos#409]
https://tasvideos.mistflux.net/Users

All Moderators, Vested editors, and Encoders are not listed. The Additional privileges tab is broken as well.

For the roles that do show up, there appears to be an extra User corresponding to each role. Example: For the Editors role, there is this user https://tasvideos.mistflux.net/Users/Profile/Editor, and so on for the others.

Additionally, there are many people across most roles, that have contributed to the site through wiki edits, rather than pubs/subs. Yet edits are not longer listed here compared to the old site.
I'd also suggest making the stats per user more dynamic, like the old site. Such that users without pubs for example, don't have the "Publications: 0" stat at all. Shortening the words down to "Pubs" and "Subs" might look better too (just my opinion).

**Comment by adelikat** [comment]
I do not want to put edit count, unless this is something really desired.  It is highly not-performant to make such a query.

As for other roles, this is a wiki page, that would need to be edited to show those roles.  I cannot just make it something it is not, in the new code base.  On a post go-live we could edit this page to reflect new roles.  However, I would strongly consider rethinking the page and whether we should simply link to: https://tasvideos.mistflux.net/Users/List or https://tasvideos.mistflux.net/Roles/List

**Comment by bigbass1997** [comment]
> As for other roles, this is a wiki page, that would need to be edited to show those roles. I cannot just make it something it is not, in the new code base.

I think there's some misunderstanding here. The wiki _already_ is set up in such a way to show those roles, the module calls are there for that. If you look at said page, here's is the moderators section (and similar for the other two roles):
```
__Moderators__%%%
(the moderator user role)%%%
[module:WikiUsers|roles=moderator]
```
Upon some digging for this module, I've discovered the issue is that the role name has changed for the mentioned roles.
- `moderator` is now `Forum Admin`
- `vestededitor` is now `Vested Editor`
- `encoder` seems to have disappeared entirely (Samsara used to have it, according to the old staff page)

But, the module doesn't support these legacy names: https://github.com/adelikat/tasvideos/blob/master/TASVideos/ViewComponents/WikiUsers.cs#L45-L49

Either the page can be edited to replace the roles with their new names (tested and this does fix the issue), or the C# code needs these legacy names added to the switch that I've linked to above.

**Comment by bigbass1997** [comment]
Revisited this issue. `moderator` and `encoder` appear to be working already again. `vested editor` is no longer a role, so I've removed that section from the page. `sitedeveloper` needed to be changed to `site developer`. And I fixed some minor formatting issues on the page.

Edit count isn't a major concern. Page is now working as expected.
