### ISSUE TITLE
Document local developer setup

### ISSUE THREAD

**Issue by adelikat** [TASVideos/tasvideos#417]
We should have detailed documentation on how to get up and running with a developer setup.
This should include Windows, Mac, and Linux.
It is required that all OSes have a documented way that does not include paid software.
Optionally we can include paid software such as RIDER for those who have it.
Both Visual Studio and VS Code must be support and documented options for OSes that support them (only Visual Studio on linux is a non-supported option)

Document todos:
[x] Windows with Visual Studio
[] Windows with VS Code
[x] Mac with Visual Studio for Mac
[] Mac with VS Code
[] Linux with VS Code

**Comment by adelikat** [comment]
If necessary, we can have a docker with docker-compose set up as an easy way to run locally

**Comment by meshuggahtas** [comment]
Steps I did to contribute code (eventually):

- Install latest Visual Studio (Community 2019) from https://visualstudio.microsoft.com/
- Run Visual Studio installer
	Select the followings:
		ASP.NET and web development
		.NET desktop development

- Clone repository from https://github.com/adelikat/tasvideos.git
- Open TASVideos.sln
- Select profile "Dev MsSql (Sample Data)"

**Comment by YoshiRulz** [comment]
Tried setting this up again, still can't run anything. I went with VSCodium over Rider so I didn't have to recreate all the launch configs, but it turns out you're not able to run .NET apps OOTB because of a licensing issue. The consensus is to [swap out the debugger binary](https://github.com/VSCodium/vscodium/issues/82#issue-409806641).

<details>
<summary>My `shell.nix`</summary>

```nix
{ pkgs ? import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/b34d0163e67e425395b4998278bc5f2195c69d48.tar.gz") {} # nearly 21.11, one more day
, lib ? pkgs.lib
, stdenv ? pkgs.stdenvNoCC
, dotnet-sdk ? pkgs.dotnetCorePackages.sdk_6_0
, git ? pkgs.gitMinimal
, netcoredbg ? pkgs.netcoredbg
, postgresql ? pkgs.postgresql_13
, vscode ? pkgs.vscode-with-extensions.override {
	vscode = pkgs.vscodium;
	vscodeExtensions = with pkgs.vscode-extensions; [
		ms-dotnettools.csharp
	];
}
}:
pkgs.mkShell {
	buildInputs = lib.remove null [ # omit packages with e.g. `nix-shell --arg vscode null`
		dotnet-sdk
		git
		netcoredbg
		postgresql
		stdenv
		vscode
	];
	shellHook = ''
		alias vscode='codium'
	'';
}
```
</details>

**Comment by meshuggahtas** [comment]
Here's my install guide, not completed so far as I have issues to tackle: https://github.com/meshuggahtas/tasvideos/wiki/Fresh-Install

Issues:
https://github.com/TASVideos/tasvideos/issues/611<-- this should be accepted after this issue (with my guide) also gets accepted
https://github.com/TASVideos/tasvideos/issues/621 <-- well I will need to try again and verify if git and gitversion are installed correctly

**Comment by meshuggahtas** [comment]
Done by https://github.com/TASVideos/tasvideos/pull/644 and the 4 Wiki pages have been copy pasted to this repo. Closing issue.

I think @YoshiRulz issue might warrant a new issue, if it's still persists after the removal of gitversion which solved cross-platform local developer problem of mine.
