### ISSUE TITLE
Submissions - Retain Judge through cancel/uncancel process

### ISSUE THREAD

**Issue by adelikat** [TASVideos/tasvideos#418]
- User submits a movie
- Judge claims the movie
- User cancels the movie
- User uncancels the movie

In this situation we want the following to occur:
- Original Judge is marked the judge (this currently happens)
- Other judges are blocked from claiming/judging the submission
- If status was previously JudgingUnderway, it automatically moves to this status
- If status was previously Accepted, it either moves to this status or back to JudgingUnderway (we can discuss this detail)

**Comment by SamsaraTAS** [comment]
A rare scenario to consider when implementing this in the future is that there's a chance the claiming Judge might no longer have their position when the movie is uncancelled.

**Comment by Invariel** [comment]
Upon removing a role, there should be logic to "fix" any issues like this that come up, not just judge but also publisher, etc.

**Comment by adelikat** [comment]
The original report, I can't reproduce, maybe it has been fixed, or was always a non-issue.

Clearing out unpublished judgements/publications in flight is a bit more complicated but I will take a look

**Comment by adelikat** [comment]
So yeah, I don't want to do this logic.  The code has no business logic related to roles.  I could do it by permission, if a user loses one of these permissions we could automatically remove them from pending submissions.  But then what if it was a mistake? There would be no easy way to undo.

I think the simplest approach is best.  If you are moving such a role from someone, we should take care to remove them from active submissions.  For canceled ones, should they get ressurected, any senior or admin could easily fix that up.
