### ISSUE TITLE
Search term restrictions should be easier

### ISSUE THREAD

**Issue by meshuggahtas** [TASVideos/tasvideos#420]
"The field Search Terms must be a string with a minimum length of 5 and a maximum length of 50."

Search term shouldn't be restricted that much. This would be problematic for the following scenarios: 
- If a game's title is less than 5 letters
- If a game's title and it's platform title combined less than 5 letters (not sure if space will count in the future)
- If a game's title is more than 50 letters

**Comment by adelikat** [comment]
less characters means more performance problems
