### ISSUE TITLE
User subpages links list doesn't change CamelCase to spaces

### ISSUE THREAD

**Issue by Zinfidel** [TASVideos/tasvideos#440]
This is **only** for the links list in the subpage module. The titles of the sub pages are spaced as before.

http://tasvideos.org/Zinfidel.html
https://tasvideos.mistflux.net/HomePages/Zinfidel

Behavior on old site:
![image](https://user-images.githubusercontent.com/1929934/133658693-4037220b-9caa-4952-afad-39f1676d5186.png)

New site:
![image](https://user-images.githubusercontent.com/1929934/133658725-307b92f1-36d4-4956-9911-a44cf95b5087.png)

**Comment by vadosnaprimer** [comment]
Sometimes adding spaces automatically doesn't look good at all

![image](https://i.imgur.com/gzOqbgg.png)

![image](https://i.imgur.com/domx15G.png)

**Comment by adelikat** [comment]
Yes, that behavior is not replicated from the old site on purpose, for this very reason.
While it is not a priority, we could try out the .net humanizer library: https://github.com/Humanizr/Humanizer
It might yield nice results for a situation like this

**Comment by Zinfidel** [comment]
> Yes, that behavior is not replicated from the old site on purpose, for this very reason.

On that topic, it *does* appear to have been replicated for titles
![image](https://user-images.githubusercontent.com/1929934/133661496-30ef0b51-1067-40f4-856a-01d585c53656.png)

**Comment by TiKevin83** [comment]
bumping up priority due to the issue observed by Zinfidel

**Comment by adelikat** [comment]
I don't agree with the priority here.  We've had these kinds of spacing issues in titles for 17 years
