### ISSUE TITLE
Inconsistencies between dark/light mode

### ISSUE THREAD

**Issue by shenef** [TASVideos/tasvideos#451]
Some elements shift when toggling between dark/light mode.
It seems there are changes to the border and padding on card and card-header classes when switching the mode.
https://tasvideos.mistflux.net/Profile is one of the pages where that is more noticeable.
Both modes on top of each other using difference blending: 
![image](https://user-images.githubusercontent.com/20268890/134332394-66fb9f4e-04db-4b08-ad2a-e09ce3827af7.png)

**Comment by Masterjun3** [comment]
I asked and this is intentional.
It's probably pretty limiting to keep the layout perfectly in sync everywhere, and I don't see any reason to keep it pixel-perfect.

**Comment by TiKevin83** [comment]
Yes this is intended, the widths of some things like borders may need to change slightly between light and dark.
