### ISSUE TITLE
Document that .svg links are inlined at TextFormattingRules

### ISSUE THREAD

**Issue by SandTAS** [TASVideos/tasvideos#454]
The [documentation for links](http://tasvideos.org/TextFormattingRules.html#ReferencesLinks) says:
> URLs ending in `.png`, `.gif`, `.jpg` are inlined if put in square brackets (embedded images).

The new site also inlines `.svg` extensions. This is not necessarily a bug, but it can result in bad rendering for pages that expect the old convention. Here is an example of a large SVG, which was formerly a text link, becoming inlined:
* https://tasvideos.mistflux.net/GameResources/DOS/CaptainComic?revision=7#Resources
* http://tasvideos.org/wiki.exe?page=GameResources/DOS/CaptainComic&rev=7#Resources

**Comment by SandTAS** [comment]
> * https://tasvideos.mistflux.net/GameResources/DOS/CaptainComic?revision=7#Resources

I appended a `?` (empty query) to the `.svg` URL in an attempt to future-proof this instance.
http://tasvideos.org/diff.exe?page=GameResources%2FDOS%2FCaptainComic&rev=8&prev=7

**Comment by vadosnaprimer** [comment]
There's a workaround for inlining images:

> To suppress image embedding, use a space after the URL, it will act as a regular link.

Though maybe there should be some explicit support for this? Or maybe embedding images that are meant to be a link hidden behind a text should be completely disabled? If it's hiddeb behind a text, it doesn't really make sense to inline it, because the editor has already decided it should be a text.

**Comment by SandTAS** [comment]
> Or maybe embedding images that are meant to be a link hidden behind a text should be completely disabled?

That's a reasonable idea. In the past, I had to use the `?` or ` ` trick to prevent inlining of `.png` links that had a text label:
https://tasvideos.mistflux.net/GameResources/DOS/MegaMan#Maps
```
* [https://www.bamsoftware.com/computers/tasvideos/mmdos-secur.map.16.png?|SECUR] ([https://www.bamsoftware.com/computers/tasvideos/mmdos-secur.map-annotated.16.png?|annotated])
```

**Comment by nattthebear** [comment]
I'd like to keep this change if possible; it'd be nice to have orthogonal support for common image formats.

**Comment by SandTAS** [comment]
> I'd like to keep this change if possible

I agree. One way to deal with this issue is to search the existing wiki pages for `.svg` links that would become inlined in the rewrite, and do the trick with adding a space to them in the old wiki, before the migration actually happens.

**Comment by nattthebear** [comment]
@adelikat Are we OK with changing this behavior, so that urls ending in .svg are auto treated like images just as .png?  If so, do we want to do import shenanigans to one-time fix up existing pages that were using them as links?

**Comment by adelikat** [comment]
I think we make this a post-go-live problem.  We fix links after the fact and not in the importer.  Since links can be fixed in a way that works in both old and new, I suggest we go ahead and do that where we reasonably can.  @SandTAS, if you are interested in trying to do that before a go-live date, le me know

**Comment by SandTAS** [comment]
> We only need a post-go-live reminder to add svg to the list of image formats at TextFormattingRules.

I just now tried to edit https://tasvideos.org/TextFormattingRules#ReferencesLinks, but my account doesn't have permission to edit the page, so I won't be able to close this issue myself.
