### ISSUE TITLE
Searchbar module missing

### ISSUE THREAD

**Issue by meshuggahtas** [TASVideos/tasvideos#466]
Title. Added related issue.

https://github.com/adelikat/tasvideos/issues/368

**Comment by adelikat** [comment]
I don't intend to build this.
Better is to just use the search we have that is integrated.  This can be put in the post-go-live todo, to remove references to this module

**Comment by adelikat** [comment]
For clarity, this module provides a box and a button, and all it does is redirect you to the search page with the search parameter as what the box had.  This is actually more clicks than simply using the search in the navbar. 

So yeah, this tab on Movies hasn't aged well and this is a good time to remove it

**Comment by bigbass1997** [comment]
> So yeah, this tab on Movies hasn't aged well and this is a good time to remove it

I've removed the tab.

**Comment by adelikat** [comment]
Thanks!
