### ISSUE TITLE
Return HTTP status code 404 for missing pages

### ISSUE THREAD

**Issue by SandTAS** [TASVideos/tasvideos#469]
Requests for nonexistent pages cause a 302 → 200 redirect.

* https://tasvideos.mistflux.net/Nonexistent
   ```
   HTTP/1.1 302 Found
   Location: /Wiki/PageDoesNotExist?url=Nonexistent
   ```
* https://tasvideos.mistflux.net/Wiki/PageDoesNotExist?url=Nonexistent
   ```
   HTTP/1.1 200 OK
   ```

It would be more semantic to return HTTP status code 404 directly for the original request. The HTTP body can be the same as what /Wiki/PageDoesNotExist shows.

**Comment by SandTAS** [comment]
The redirection is slightly different for apparent homepages.

* https://tasvideos.mistflux.net/Wiki/HomePageDoesNotExist
  ```
  HTTP/1.1 302 Found
  Location: /Wiki/HomePageDoesNotExist
  ```
* https://tasvideos.mistflux.net/Wiki/HomePageDoesNotExist
  ```
  HTTP/1.1 200 OK
  ```

**Comment by nattthebear** [comment]
Yes, we should do this.

**Comment by nattthebear** [comment]
@SandTAS I have implemented 404, but the redirect still exists.  Do you think it's important to also remove the redirect?

**Comment by meshuggahtas** [comment]
Thought I should ask this here: is it a known issue that non extisting pages might give a generic 404 error in browser instead of a TASVideos' one? 
- Hidden UserFile was the first but it was already fixed https://github.com/TASVideos/tasvideos/issues/821
- Deleting a UserFile --> you get redirected to the non existing UserFile resulting in 404

**Comment by meshuggahtas** [comment]
Reopening issue and 1 more 404:
- Trying to visit a non existing movie/submission --> only happens by manually visiting, for example https://tasvideos.org/9000M https://tasvideos.org/9000S

**Comment by adelikat** [comment]
Yes you are supposed to get a 404 for those situations.  This ticket isn't about having a nicer 404 page, but how we should handle non-existent wiki pages

**Comment by meshuggahtas** [comment]
For all the 4 situations? I think the following single issue should be fixed regarding this 404 (in a new issue if you say yes to this):
- Deleting a UserFile --> you get redirected to the non existing UserFile resulting in 404

1. Go to a UserFile
2. Delete it
3. 404

**Comment by adelikat** [comment]
Make a separate ticket for that
