### ISSUE TITLE
Drop Query Params for Highlighting Posts

### ISSUE THREAD

**Issue by SandTAS** [TASVideos/tasvideos#476]
This is a minor enhancement suggestion. Currently, direct links to forum posts include a `Highlight` query parameter that causes the selected post to be highlighted:
https://tasvideos.mistflux.net/Forum/Topics/22808?Highlight=508259&CurrentPage=1#508259

It works by, for each post, checking if `Highlight` is equal to the post `Id`, and if so setting a boolean, which if true causes the CSS classes `forum-post-highlight border-warning border-2` to be applied to the post.
https://github.com/adelikat/tasvideos/blob/bbe2ce2b051f613ea1aacb68aeefd0b47706866a/TASVideos/Pages/Forum/Topics/Index.cshtml.cs#L140-L147
https://github.com/adelikat/tasvideos/blob/cdceb92343a3bddbffedd25df4e4a679d00cc81f/TASVideos/Pages/Forum/Topics/_TopicPost.cshtml#L2

It should be possible to accomplish the same effect using a selector for the [`:target-within`](https://developer.mozilla.org/en-US/docs/Web/CSS/:target-within) pseudo-class on every post, containing the same rules as `forum-post-highlight border-warning border-2`. This would remove the need for a `Highlight` query parameter in the URL. Alternatively, use [`:target`](https://developer.mozilla.org/en-US/docs/Web/CSS/:target) and set the post `id` directly on the containing `div`, rather than on an element contained within it.

**Comment by adelikat** [comment]
I like this idea.  I would encourage someone interested in tinkering with the UI to try this suggestion

**Comment by TiKevin83** [comment]
:target-within has no support in any released browser, so I think we need to leave this as is for now.

**Comment by SandTAS** [comment]
Ah, that's my bad. I should have checked the browser support before suggesting it.

For what it's worth, when looking at the HTML I expected the `id` to be set on the `<div class="card">` element, not on an `<a>` element nested within it. In that case `:target` would work.

Feel free to close the issue—I didn't mean to drop an unactionable open issue on you :)

**Comment by TiKevin83** [comment]
I do think that could be a potential solution, there's also the question of whether Chrome's link to text feature will ever catch on with other browsers, but that wouldn't exactly give the style desired here.

**Comment by SandTAS** [comment]
> For what it's worth, when looking at the HTML I expected the `id` to be set on the `<div class="card">` element, not on an `<a>` element nested within it. In that case `:target` would work.

#885 does this sub-task.

I started to also refactor the CSS to use a `:target` selector rather than `forum-post-highlight border-warning border-2` classes, but I couldn't figure out how to make the block contain the same declarations as the `border-warning border-2` (which come from Bootstrap) without duplication.

But at any rate, it may not be worth doing the `:target` thing now. My original intention was to be able to remove the `Highlight=` from forum post URLs, for better caching and e.g. archiving by Wayback Machine. But the recent c0fcaa686f855b182125c63a9f16bb5edc004baf added another property that depends on `Highlight=`, namely post-specific `meta` elements. I think the post-specific metadata is a good idea, and more important than removing an URL query parameter. If the contents of the page are different, it's actually good that the URL be different.

**Comment by TiKevin83** [comment]
Updating title as this referenced the recent enhancements for the discord posts which could also be helped by refactoring the highlight query param/id system

**Comment by adelikat** [comment]
Wasn't this work done?  We now automatically highlight a post when using the url /Forum/Posts/12345

**Comment by TiKevin83** [comment]
yes, thanks!

**Comment by Masterjun3** [comment]
I thought the point of this issue was to remove the "Highlight" from the url and use the fragment for highlighting.

**Comment by TiKevin83** [comment]
It touched on a lot of things but the main thing I hoped for is fine now since you get the highlighted post even with just the URL to the post. It's less benefit now for the highlight to happen from a target selector because we have to do dynamic things to the page anyway for the head embed tags.

**Comment by adelikat** [comment]
So the problem here is that we use the highlighted post when creating the meta tags which must be done server side, and we cannot get the fragment server side since it is not passed in.

Going to close this ticket based on this detail.  If I'm wrong, then by all means, reopen
