### ISSUE TITLE
Using the Maintenance Log to update SystemTVCcontrol page automatically with New Data.

### ISSUE THREAD

**Issue by Spikestuff** [TASVideos/tasvideos#479]
Right, I have a weird… or valid Feature Request for SystemTVCcontrol, if this works in sync to what is done for Reworked Site.

![image](https://user-images.githubusercontent.com/12412764/134683304-0a4101c9-a0c2-4909-87c0-17624947f07a.png)

As you can see the encode uvjCJrzADfU doesn’t exist in the SystemTVCcontrol page, and it’s due to me not using the site’s YouTube uploader instead it was directly via YouTube.
The proposal isn’t magically figuring out what’s unlisted on that account since it’s already grabbing the information that we provided, so it wouldn’t be of any benefit for us.

The proposal that I have, is for when a TAS is edited/published it fishes the data from there instead and automatically grabs the ID we provided, and then who the editor is and what the Movie ID is.

In this case it would be grabbing the edit from here: http://tasvideos.org/MovieMaintenanceLog.html?id=566 
And then placing: uvjCJrzADfU, 566M and my Uploader User ID into the appropriate fields.

This is to preconfigure the information for later in time if something needs to be checked, and the database of this page is done without human requirement, and not creating extra work for what an Encoder/Publisher would have to do which is to scroll down to the bottom of the page, remember what our User ID is (which some of us know off by heart) and get the Movie and YouTube link.

![image](https://user-images.githubusercontent.com/12412764/134683321-a5658aa4-5243-4869-bb22-f6bbaffe8ddc.png)

And when creating a New video/movie from scratch it would be nice for the User ID to be automatically in there if the preconfiguration doesn’t work.

**Comment by adelikat** [comment]
Closing since we no longer have this page

**Comment by vadosnaprimer** [comment]
The intent of this issue is to have a new page that stores the following info:
- Publication ID
- YT video that is used in it
- user who added it
- date when it was added

Since all this is in movie maintenance log already, it doesn't involve storing TVC access logs anywhere.

**Comment by adelikat** [comment]
This work has been done now, correct? https://tasvideos.org/Publications/YoutubeUploaders

**Comment by vadosnaprimer** [comment]
Can't check, stably getting

> An unexpected error has occurred.
> The information has been logged and will be investigated as we continue to improve the reliability of the site.

**Comment by adelikat** [comment]
Closing this ticket, but a ticket should be made about the fact that the page is broke, again.

**Comment by vadosnaprimer** [comment]
The page that I remember that thing to be only lists _youtube channels that host videos used in publications_. If it's what that page really is, it contains none of the info requested in this issue.

**Comment by adelikat** [comment]
Fair, but I'm still closing this.  I won't build this.  It is too much infrastructure to maintain for the benefit it gives.  Maybe we were spoiled with all the stuff we used to have, but it wasn't maintainable.  It had lots of issues that never got resolved.  Sorry :(

**Comment by vadosnaprimer** [comment]
Isn't it just a matter of displaying a section of the logs we already store?
