### ISSUE TITLE
Forum Compact Mode: hide profile pics and signatures toggle

### ISSUE THREAD

**Issue by MemoryTAS** [TASVideos/tasvideos#481]
Probably would be helpful for mobile users.

**Comment by meshuggahtas** [comment]
Currently the smaller viewport visitors have a compact version by removing signature, awards and join date/posts/location.

Is this feature about having a toggle button to hide/show the remaining data?

**Comment by adelikat** [comment]
Is this still relevant? It automatically goes into a compact mode for mobile

**Comment by MemoryTAS** [comment]
only really relevant if somebody wants it for desktop I guess
