### ISSUE TITLE
A few more darkmode color issues

### ISSUE THREAD

**Issue by Masterjun3** [TASVideos/tasvideos#485]
- ~**Diff page**: https://tasvideos.mistflux.net/Wiki/Diff?path=EmulatorResources~ This is now #515
- **Username** in disabled state: https://tasvideos.mistflux.net/Profile/Settings
- **Delete warning**: Uh, I suppose make a post and try to delete it. Here is the forum: https://tasvideos.mistflux.net/Forum
- **User cards** on the Users page: https://tasvideos.mistflux.net/Users

**Comment by TiKevin83** [comment]
Darkmode diffs should be spun into a separate issue, that will require a fundamental restructuring of our diff engine

**Comment by YoshiRulz** [comment]
Disabled textboxes, on the Profile Settings page for example, still look like the enabled ones as of v2.2.293.

**Comment by Masterjun3** [comment]
Indeed.
