### ISSUE TITLE
GameName module doesn't work on editing preview

### ISSUE THREAD

**Issue by nattthebear** [TASVideos/tasvideos#517]
Preview should always give identical content to final output, but here it doesn't, as we get data in the wrong way:

```
var path = HttpContext.Request.Path.ToString().Trim('/');
```

**Comment by Randomno** [comment]
Same issue with MoviesGameList or different? e.g. https://tasvideos.mistflux.net/Wiki/Edit?path=Games none of the game links work in the Preview.

(I was aware of this before when I went to the page https://tasvideos.mistflux.net/Games/ but considered it my own fault)

**Comment by adelikat** [comment]
Going to close this.  I don't see a reasonable work around, nor is it intended to work the way described in this report.  It is just supposed to be used by a system page that is then rendered on the intended page.  With 2 levels of indirection, there isn't much sanity to the process, and I don't see a less worse way to achieve the results than a module that is limited in use case
