### ISSUE TITLE
Missing ability to split selected posts instead of from post x on

### ISSUE THREAD

**Issue by MemoryTAS** [TASVideos/tasvideos#526]
There is no ability to select individual posts to split from a topic. You have to split from a certain point onwards. If there is a mix of on topic, and off topic discussion, it's helpful to choose which specifically to split.

**Comment by adelikat** [comment]
Kicking the can again, putting in the 2.4 milestone.  While this seemed like an immediate need post-go-live, it actually hasn't come up.  But we should work on this soon.

**Comment by adelikat** [comment]
DUN!
