### ISSUE TITLE
Missing "Latest Post" in Forum view

### ISSUE THREAD

**Issue by Masterjun3** [TASVideos/tasvideos#543]
Old site shows the latest post in a given subforum: http://tasvideos.org/forum/
New site does not: https://demo.tasvideos.org/Forum

This feature was very useful in figuring out which subforums are active and which subforums don't need to be checked for new posts.

This was mentioned in issue #407 but it was only fixed for *inside* the subforum

**Comment by adelikat** [comment]
done
