### ISSUE TITLE
BBCode buttons clip through the sides when creating new posts or topics on mobile

### ISSUE THREAD

**Issue by Masterjun3** [TASVideos/tasvideos#546]
Example page (view on mobile/small widths): https://demo.tasvideos.org/Forum/Posts/Create/22808

**Comment by adelikat** [comment]
I don't see an issue with that page, even on 320px width

**Comment by Masterjun3** [comment]
https://user-images.githubusercontent.com/22375320/139590671-ef713878-61bb-4dce-975d-434bb8788407.mp4

Please reopen.

**Comment by TiKevin83** [comment]
just need to add flex-wrap to the btn-groups
