### ISSUE TITLE
Invalid URL on a certain Homepage Subpage

### ISSUE THREAD

**Issue by Masterjun3** [TASVideos/tasvideos#556]
The page in question: https://demo.tasvideos.org/HomePages/Noxxa/Rankings/Yearly/20042009
Working page on old site: http://tasvideos.org/Noxxa/Rankings/Yearly/20042009.html

An idea why this specific URL fails is because the subpage name is a number.

**Comment by adelikat** [comment]
Closing this as "by design".  We can easily fix pages that are numbers only in production now.
