### ISSUE TITLE
Feature Request: Rollback to previous page revisions

### ISSUE THREAD

**Issue by SamsaraTAS** [TASVideos/tasvideos#558]
Currently, on both the old site and the previous site, the only ways of "rolling back" are to manually revert everything or delete recent revisions. A feature that would allow any page revision to immediately be rolled back to would be useful for wiki moderation. This would be a feature only accessible by site staff, perhaps even just the moderation team, to prevent abuse.

Inspired by [this submission I handled a while back](http://tasvideos.org/7106S.html), where the author tried to completely wipe it clean after rejection, causing me to have to revert everything manually.

**Comment by adelikat** [comment]
I think this is a good idea and would be the same functionality as "Reverse commit" in git

**Comment by adelikat** [comment]
Done
