### ISSUE TITLE
Setting Dark or Auto style multiple times

### ISSUE THREAD

**Issue by meshuggahtas** [TASVideos/tasvideos#579]
Currently clicking on Dark or Auto style has the following effects:
- insert <link rel="stylesheet" id="style-dark" href="/css/darkmode.css"> if clicked on Dark
- insert <link rel="stylesheet" id="style-dark-initial" href="/css/darkmode-initial.css"> if clicked on Auto

However clicking on the same style (Dark and Dark, or Auto and Auto) will insert again, making the original logic fail to switch between styles, _which is coded as_ "remove previous style" and "add new style".

If you click Dark and Auto or Auto and Dark, itt will rewrite the last one to your desired selection.

I don't have a suggestion for a better structure.

Problem located in [TASVideos/wwwroot/js/site.js](https://github.com/TASVideos/tasvideos/blob/master/TASVideos/wwwroot/js/site.js)

**Comment by Masterjun3** [comment]
This was fixed by #591.
