### ISSUE TITLE
Feature Request: i18n

### ISSUE THREAD

**Issue by Invariel** [TASVideos/tasvideos#602]
I know it's a huge ask, and not something to be done for the initial release, but it might be a nice feature for site's main navigation and labeling to support internationalization if it doesn't already.

**Comment by adelikat** [comment]
Going to close this as these tickets cover this request, and define some definite implementation details:
https://github.com/TASVideos/tasvideos/issues/174
https://github.com/TASVideos/tasvideos/issues/33
