### ISSUE TITLE
API - Endpoints with inconsistent key-case schema

### ISSUE THREAD

**Issue by bigbass1997** [TASVideos/tasvideos#604]
The following endpoints respond with keys that are capitalized with PascalCase. But the schema for those endpoints, as well as all others, use keys with camelCase. JSON is case-sensitive, and so most parsers will likely complain or fail completely to parse these responses without special handling or field aliasing.

Endpoints affected:
```
/v1/Games
/v1/Publications
/v1/Submissions
/v1/Tags
```
Note that the respective `/{id}` and `/id?id=` child endpoints do not exhibit this inconsistency.

Recommend using Swagger's interface https://demo.tasvideos.org/api/ to see examples of this.

At the least, the keys in the response and schema should match. But ideally the case being used should be consistent across all endpoints (so these responses should likely use camelCase).

**Comment by adelikat** [comment]
@bigbass1997 : I fixed and deployed this, and also the inconsistency in Tags with the ?id= query param where a route param was intended.  This is a breaking change, so letting you know here for lack of a better way to communicate this.
