### ISSUE TITLE
Update MovieTokens wiki page

### ISSUE THREAD

**Issue by adelikat** [TASVideos/tasvideos#609]
After go live, MovieType will no longer be a searchable parameter and needs to be removed. 
Also double check if there is any new functionality in the new search parameters, and if any syntax has changed

**Comment by vadosnaprimer** [comment]
Is it possible to regenerate those docs every time there are changes in tokens?

**Comment by adelikat** [comment]
Do you anticipate changes to be common? I don't

**Comment by bigbass1997** [comment]
I've removed the movie Type parameter and associated tab of possible types from the page. Not sure if there is anything new that needs to be added though.

**Comment by adelikat** [comment]
I cleaned it up some, I think the page is still a work in progress, but the spirit of this ticket was to  convert to the new params, and remove no longer supported features.  Closing this ticket
