### ISSUE TITLE
Replace all overflow-y scrolls - version 2

### ISSUE THREAD

**Issue by Masterjun3** [TASVideos/tasvideos#616]
The previous issue #399 was closed even though this isn't solved.
I previously made sure certain overflow scrolls only happen on the desktop view of the page. Now they've been removed completely in a lot of pages and the initial reason they were there in the first place was disregarded.

I will now repeat the opening message:
> This is a debatable design feature. Currently, there are several elements with a maximum height, which show content in a scrollable block if the height exceeds the maximum value.
I personally agree with the feedback on the forums that this should be replaced with a different design. The block-scrolling can interrupt page-scrolling, and this is especially noticable on mobile devices where actual page-scrolling is only possible on the side edges of the screen.
For small limited blocks such as the featured movie or the news on the front page it should be asked if it's even necessary to limit the height.
For potentially larger blocks such as the submission text, a friendlier solution would be a label at the bottom saying "Read more", which when pressing displays more of the content.

**Comment by TiKevin83** [comment]
If I can try to summarize, in places like the forum thread where I didn't remove the Y scroll in my PR, you'd still like to have the design of that scroll changed to cut off and link out to the full text with a "more" link?

**Comment by Masterjun3** [comment]
Yes, we will eventually need that kind of design anyway. It would have made sense to implement it, and then use it in every spot where an overflow-y scroll was.
Not sure what the reasoning was behind resolving "Replace all overflow-y scroll" by not replacing all overflow-y scrolls.

**Comment by Masterjun3** [comment]
There is now a Show more TagHelper #901 that removed the last direct occurence of overflow-y (author notes in forum). The only ones left are now in the TwoColumnSelectTagHelper.

**Comment by adelikat** [comment]
@Masterjun3 : What do you intend to do in the two column picker?

**Comment by Masterjun3** [comment]
I thought about replacing it with a more mobile friendly selection picker. It's kind of weird to use on mobile anyway.

**Comment by Masterjun3** [comment]
We replaced the two-column-select with a new improvement of the multi select html. 910b15227ad5571e9ed100c2da4e8f89ec5f5abe
That one *still* has scrolling inside scrolling, but I have no idea how we can fix that with all the other features we need.
So basically, I'm closing this now as "good enough". Maybe in 10 years there will be cool new HTML UI elements we can use to make this better.
