### ISSUE TITLE
macOS + Visual Studio Version empty

### ISSUE THREAD

**Issue by meshuggahtas** [TASVideos/tasvideos#621]
I've tried my https://github.com/TASVideos/tasvideos/wiki/Local-Development-Setup#macos-big-sur-110 steps which let me build but getting `InvalidOperationException: Sequence contains no elements at SetViewBag.cs 18th line`. That is, Version being empty.

![VirtualBox_MACOS_20_11_2021_07_36_03](https://user-images.githubusercontent.com/31288337/142717554-f82ae0f8-32ea-45f5-8088-df9559de0fe7.png)

I've came across this error when trying Windows Visual Studio without installing Git beforehand.

git version 2.34.0
.NET 5.0.403 runtime 5.0.12
Cloned latest repo with last commit https://github.com/TASVideos/tasvideos/commit/55c8268db72428a324a445695ee76d9978cc3f19

**Comment by meshuggahtas** [comment]
This problem also occurs at Ubuntu 20.04 + VSCode. This means both Ubuntu and macOS with VSCode unable to view any of the website because the Version is required for every single page.

- Tried updating gitversion, no
- Going in to my local repo directory and running dotnet-gitversion, gives the correct 2.1.+438 or what build metadata version
- Tried manually editing gitversion.deps.json, no
- Tried dotnet-gitversion /updateassemblyinfo which makes me unable to build (no reference to Assembly)
- Tried dotnet-gitversion /updateprojectfiles which makes me unable to build (no reference to Assembly)
- Tried looking for VSCode settings, no
- Tried googling it, only crumbs of information 

I believe this problem is not because I'm using containers (I mean... I don't see how it would affect) but a configuration error in the project. I would be glad if someone else could try it on a non virtualized container.

**Comment by meshuggahtas** [comment]
Also affects macOS + Visual Studio

**Comment by meshuggahtas** [comment]
New tests (gitversion got removed):
Windows+VSCode OK
Windows+Visual Studio OK
Ubuntu+VSCode OK
macOS+VSCode under testing
macOS+Visual Studio under testing

Note that TiKevin83 now faces an issue of assembly version at Windows+VSCode and Windows+Visual Studio:
```
C:\Development\tasvideos\TASVideos\obj\Debug\net5.0\AssemblyInfo.g.cs(11,12): error CS0579: Duplicate 'AssemblyFileVersion' attribute [C:\Development\tasvideos\TASVideos\TASVideos.csproj]
C:\Development\tasvideos\TASVideos\obj\Debug\net5.0\AssemblyInfo.g.cs(12,12): error CS0579: Duplicate 'AssemblyVersion' attribute [C:\Development\tasvideos\TASVideos\TASVideos.csproj]
C:\Development\tasvideos\TASVideos\obj\Debug\net5.0\AssemblyInfo.g.cs(13,12): error CS0579: Duplicate 'AssemblyInformationalVersion' attribute [C:\Development\tasvideos\TASVideos\TASVideos.csproj]
    0 Warning(s)
    3 Error(s)
```

**Comment by adelikat** [comment]
We have upgrade .net and gitversion and refactored some things, going to assume this is fixed, especially since we compile and run the same code in the same way on the server.  Can create a new ticket if there is a specific issue that still occurs
