### ISSUE TITLE
VSCode + TASVideos project + Chrome + HTTP problem

### ISSUE THREAD

**Issue by meshuggahtas** [TASVideos/tasvideos#634]
Chrome blocks insecure content by default, so after building the project, you will be presented with ERR_SSL_PROTOCOL_ERROR and as well it will use HTTPS protocol.

edit: **the following solution does not works**, even after trying to change the settings of the HTTP site using the URL chrome://settings/content/siteDetails?site=http%3A%2F%2Flocalhost%3A5000
1. Press the (i) icon next to the URL to the left
2. Press Site settings
3. Change Insecure content to allow

I believe this should be mentioned in the local developer setup guide.

More tests:
Firefox+HTTP+5000: works
Firefox+HTTPS+5001: works after accepting risk
Chrome+HTTP+5000: unable to visit because it automatically changes to HTTPS resulting in ERR_SSL_PROTOCOL_ERROR
Chrome+HTTPS+5001: works
Edge+HTTP+5000: works
Edge+HTTPS+5001: works

Original issue text:

> In Windows+Visual Studio, it launches :5000 but it gives **ERR_SSL_PROTOCOL_ERROR** so I have to use https://localhost:5001
> In Windows+VSCode, it launches :5000 but it gives **ERR_SSL_PROTOCOL_ERROR** so I have to use https://localhost:5001
> In Ubuntu+VSCode, it launches :5000 and it works
> In macOS+VSCode, it launches :5000 and it works
> In macOS+Visual Studio, it launches :5000 and it works
> 
> I would assume it should use the same port between OSes.

**Comment by meshuggahtas** [comment]
Added Chrome note to https://github.com/TASVideos/tasvideos/wiki/Local-Development-Setup#5-configuration

For formatting purposes, Chrome related error is noted at Windows steps, Safari related error is noted at macOS steps. Leaving issue open in case someone has a better suggestion to make sure new users on Ubuntu or macOS won't fall into using Chrome and not finding this information.

**Comment by TiKevin83** [comment]
I can't replicate this issue on Windows 10 + Visual Studio 2022 Community, the default localhost port doesn't have a plain HTTP warning in chrome for me

**Comment by meshuggahtas** [comment]
It looks like the project settings have been changed, so it doesn't uses a localhost:5000 localhost:5001. This means Windows 10 might fixed. macOS probably affected. Ubuntu might fixed.

**Comment by meshuggahtas** [comment]
Sorry, my issue wasn't descriptive enough. 
- This issue happens using the **TASVideos** named build which is used by **VSCode** developers.
- The issue only happens on **Chrome**.

Now that I also have a clear picture, I think the workaround should be suggested as changing the VSCode default browser application to be used. This sounds simple but according to this page https://stackoverflow.com/questions/47519768/how-do-i-set-the-default-browser-as-chrome-in-visual-studio-code it isn't works for every scenario or requires relatively advanced methods to make sure it won't use the default browser of the system.

**Comment by meshuggahtas** [comment]
Closing this issue because this is not the project's fault. If someone wants to use HTTP only with Chrome, change default browser application or change settings of secure connection while developing. There is no need to change starting port.
