### ISSUE TITLE
Fill in Rom Information for Subs/Pubs

### ISSUE THREAD

**Issue by adelikat** [TASVideos/tasvideos#649]
This is not a developer project necessarily.

Rom info is now a requirement to properly catalog a submission.  We need to go back and backfill these values for submissions and publications.  It needs to be a good dump if the movie syncs, or the bad dump if that is the only one it syncs on.

We can easily build a wiki module to show missing rom info

**Comment by meshuggahtas** [comment]
Tasks elaborated:

1. Gather the list of submissions and publications (all movies except UserFiles) without ROM info:
- Requires a SQL query or wiki module

2. Analyze and verify ROM info: 
- A TAS might sync on multiple ROMs or neither of them.
- ROMs usually have multiple versions. 
1. Identify region.
2. Identify version.
- Prepare your emulator to run as fast as possible to reduce the time taken with watching the movie syncing: don't run other applications while testing, use turbo, disable performance limits.
- To verify syncing, publications have video encodes. Submissions usually have a temporary video encode. If you don't know how the ending should look like, google for a RTA speedrun equivalent of the movies' game and objectives.
- Make sure you always check GoodTools or do an Internet search for the ROM name.

**Comment by TiKevin83** [comment]
Since this is wiki markup specific it should be closed if we've set up a system for logging tasks like this elsewhere

**Comment by meshuggahtas** [comment]
I've been asking this multiple times without an answer: Where is the place where wiki related tasks can be shared and discuss as someone who is not a staff member?

**Comment by adelikat** [comment]
Closing this, we have https://tasvideos.org/TODO/NoRomHash to track this work
