### ISSUE TITLE
jrsr (JPC-RR) movies not accepted in submissions

### ISSUE THREAD

**Issue by Randomno** [TASVideos/tasvideos#653]
Tested a few and none worked.

**Comment by adelikat** [comment]
Can you provide some examples? It's a supported format complete with unit tests

**Comment by Randomno** [comment]
I tried zip files from existing submissions on the site. An example: http://tasvideos.org/submissions/7003.zip

**Comment by adelikat** [comment]
Yup, can reproduce locally, got broken awhile back with a database update

**Comment by adelikat** [comment]
Fixed
