### ISSUE TITLE
Tone down table borders?

### ISSUE THREAD

**Issue by brunnerh** [TASVideos/tasvideos#659]
The borders seem unnecessarily salient. For the light theme I would go from gray-600 at least to gray-500:

Before:
![image](https://user-images.githubusercontent.com/834235/146059452-42db0719-5a2c-4ea9-ae69-480a40faf05b.png)

After:
![image](https://user-images.githubusercontent.com/834235/146059504-e0a1ddaf-60f3-43f0-8862-ee26dc79fb37.png)

For the dark theme I would go from gray-600 to gray-700. (Using a custom property and just reassigning that for the dark scheme might be the easiest here)

Before:
![image](https://user-images.githubusercontent.com/834235/146059742-3c0b5b84-83f5-44a4-ba81-9650666d2434.png)

After:
![image](https://user-images.githubusercontent.com/834235/146059847-5386cc53-ad6f-4ee1-82ff-3511f5b59a4b.png)

Personally, I would also just drop the vertical lines completely because they do not contribute much (it is easy to see which cell contents belong to which column).

![image](https://user-images.githubusercontent.com/834235/146061342-f60b11cb-9c0b-4201-b05b-d075b5c705bb.png)

In general any additional line distracts from the contents and contributes visual noise. Even the horizontal lines are arguable because of the existing alternating color scheme which does most the work of separating the rows.

**Comment by TiKevin83** [comment]
I generally agree with the suggestion here, just not a priority before go-live

**Comment by ThunderAxe31** [comment]
What about the submission queue? https://tasvideos.org/Subs-List
