### ISSUE TITLE
News links on index page do not really behave like links

### ISSUE THREAD

**Issue by brunnerh** [TASVideos/tasvideos#660]
These links toggle content dynamically on click:
![image](https://user-images.githubusercontent.com/834235/146063173-b263d6a4-2c6c-433e-8538-2af793ef623b.png)

But opening them in a new tab/window (e.g. via the context menu or middle mouse click) just opens the same page, without the contents for the entry being expanded.

**Comment by meshuggahtas** [comment]
- Opening news header link in a new tab should correctly open the correct thread and post
- Clicking news header link should correctly expand the content of the news

2: Add legacy site feature, binding the correct thread's correct post, which would be https://staging.tasvideos.org/Forum/Topics/8694?CurrentPage=10&Highlight=510513#510513 for the first one in the picture.
