### ISSUE TITLE
Discord + long submission update test

### ISSUE THREAD

**Issue by meshuggahtas** [TASVideos/tasvideos#668]
There is a maximum length which doesn't let TASVideoAgentDev post on discord. Unsure which field and what is the length.

Affects submissions and userfiles for sure.

237 characters works, 257 doesn't

Example working message:
New Submission! Go and see #7302: MESHUGGAH, 123456789012345678901234567890123456789012345678901234567890's SGX 123456789012345678901234567890123456789012345678901234567890 "12345678901234567890123456789012345678901234567891" in 07:55.91

Example not working message:
New Submission! Go and see #7303: MESHUGGAH, 1234567890123456789012345678901234567890123456789012345678901234567890's SMS 1234567890123456789012345678901234567890123456789012345678901234567890 "12345678901234567890123456789012345678901234567891" in 06:01.11

**Comment by TiKevin83** [comment]
Closing as fixed by the discord embed enhancements
