### ISSUE TITLE
Submitting movie and back ERR_CACHE_MISS

### ISSUE THREAD

**Issue by meshuggahtas** [TASVideos/tasvideos#669]
When submitting a movie with long fields, pressing back in the browser might give an ERR_CACHE_MISS error. Unsure what is the problem.

Maximum branch field seems consistent in getting this error.

- Submit a new movie with maximum branch field value
- Submit it
- Press back

**Comment by Masterjun3** [comment]
This just means the browser detected it can't use its cache. And going back after submitting wouldn't even help anyway because you don't want to resubmit a submitted movie. It also wouldn't work because of the antiforgery token system.
Closing because this is standard browser behavior.
