### ISSUE TITLE
Unsupported movie formats for submission

### ISSUE THREAD

**Issue by meshuggahtas** [TASVideos/tasvideos#670]
Currently the following movies can not be uploaded for:
- 32X/SegaCD .gmv error at https://github.com/TASVideos/tasvideos/issues/665
- Doom: .lmp http://tasvideos.org/6959S.html <--- https://github.com/TASVideos/tasvideos/issues/1243
- NES: .fm3 http://tasvideos.org/3773S.html <--- https://github.com/TASVideos/tasvideos/issues/352
- Windows: .wtf http://tasvideos.org/4234S.html <--- https://github.com/TASVideos/tasvideos/issues/331

**Comment by adelikat** [comment]
I do not intend to support .fm3

**Comment by vadosnaprimer** [comment]
fm3 is still used to this day http://tasvideos.org/userfiles/user/Scumtron and it's the same as fm2 to the parser, with just some extra info that the site doesn't care about, but very useful for users. But I already explained this in https://github.com/TASVideos/tasvideos/issues/352#issuecomment-909303777

**Comment by adelikat** [comment]
Closing this ticket, we have tickets for each individual issue reported here
