### ISSUE TITLE
DS wrong movie time length

### ISSUE THREAD

**Issue by meshuggahtas** [TASVideos/tasvideos#673]
Submitting a published DS TAS on the new site will show different movie time length.

http://tasvideos.org/2241S.html 26:27.5
Resubmitting it on new site 26:32.11

Note: might be not an issue, for example a change in frame rate without updating previously published movies with old frame rate

edit: latest published DS TAS also have this issue

**Comment by meshuggahtas** [comment]
The legacy site time seems to be correct one using 59.826098288081.

**Comment by CasualPokePlayer** [comment]
> http://tasvideos.org/2241S.html 26:27.5 Resubmitting it on new site 26:32.11
> 

Old site used 60 FPS in that case, new site uses 59.826098288081 FPS. Not a bug on us.

> 
> edit: latest published DS TAS also have this issue

Checking that and everything is correct there, I don't see any issues.
