### ISSUE TITLE
C64 wrong movie time length

### ISSUE THREAD

**Issue by meshuggahtas** [TASVideos/tasvideos#674]
Submitting a published C64 TAS on the new site will show different movie time length.

http://tasvideos.org/4526S.html 21:25.22
Resubmitting it on new site 17:56.80

Note: might be not an issue, for example a change in frame rate without updating previously published movies with old frame rate

edit: Latest published C64 TAS also has this issue

**Comment by meshuggahtas** [comment]
The new site time seems to be the correct one using 59.826089499854. But the encode is 21:25... ?

**Comment by fsvgm777** [comment]
Sorry for commenting after the issue got closed, but C64anabalt runs at PAL speed, so 50.1245 would be correct in this case.

**Comment by CasualPokePlayer** [comment]
I would assume the correct movie time on the current site was hacked in due to the movie file not actually providing a way to tell the parser that this is a PAL movie. I would be more interested in the "latest published C64 TAS" having this issue.
