### ISSUE TITLE
PSX wrong movie time length

### ISSUE THREAD

**Issue by meshuggahtas** [TASVideos/tasvideos#675]
Submitting a published PSX TAS on the new site will show different movie time length.

http://tasvideos.org/7267S.html 03:02.48
Resubmitting it on new site 03:04.47

Note: might be not an issue, for example a change in frame rate without updating previously published movies with old frame rate

**Comment by meshuggahtas** [comment]
The legacy site time seems to be the correct one using 59.940060138702

**Comment by vadosnaprimer** [comment]
Since that submission is now accepted, and replacing the movie with an improvement made the site recalculate the time and it's now incorrect (doesn't match bizhawk's), I wanna request to rise priority for this issue.

**Comment by meshuggahtas** [comment]
IIRC I used https://tasvideos.org/PlatformFramerates and copy pasted the values. I don't see that value in that list, so I'm assuming I've used a different page with an outdated FPS number, maybe the submission had that framerate given in the submission Frame Rate

**Comment by vadosnaprimer** [comment]
Old site had

![изображение](https://user-images.githubusercontent.com/7092625/149313074-912a1e57-7e56-4580-8cfd-208c642634d1.png)

**Comment by adelikat** [comment]
Framerate updated with a database query, closing
