### ISSUE TITLE
Forum userfile and wip tag

### ISSUE THREAD

**Issue by meshuggahtas** [TASVideos/tasvideos#677]
Is there a difference between the two? Seems functionally the same.

**Comment by TiKevin83** [comment]
Can you provide more information on this ticket?

**Comment by meshuggahtas** [comment]
When I tried all the forum tags, they all had differences. But if I use the tag userfile and wip tag, they seemed to be exactly the same. Is there a difference between the userfile tag and the wip tag, or only the name differs?

**Comment by vadosnaprimer** [comment]
I think the wip tag is not supposed to exist, because not every userfile is a wip. It can also be a text file like watch and script.

**Comment by TiKevin83** [comment]
@adelikat could use your direction on what's going on here, are there supposed to be separate WIP and UserFile tags and if so can this ticket be closed?

**Comment by adelikat** [comment]
there's about 1500 usages of the userfile tag, and 49 usages of the wip tag.  Mind if I just edit those 49 posts then remove support for the WIP tag?

**Comment by MemoryTAS** [comment]
sounds good to me

**Comment by adelikat** [comment]
Ok, I updated all references of [wip] to [userfile], removed support for [wip] and deployed to prod
