### ISSUE TITLE
E-mail confirmation shouldn't show an error when confirmed

### ISSUE THREAD

**Issue by meshuggahtas** [TASVideos/tasvideos#678]
- Register new user
- Click on the link in the e-mail to confirm registration
- E-mail confirmed, message shown on the link:
Error
An error occurred while processing your request.
Request ID: 00-47d4a0da15b61e4bbb2f696f3b337d60-1106eff2455c3b49-00

**Comment by meshuggahtas** [comment]
Registered new user with gmail account, e-mail confirmation didn't arrived automatically. Manually clicking resend solved it.

**Comment by meshuggahtas** [comment]
The emails did arrive, albeit minutes later. I can't verify the exact time duration, but the longest time was around 3 minutes.

**Comment by adelikat** [comment]
Closing this, as we have had many registrations.  If there is an intermittent problem we need more information to confirm.  Logging was added that can find more info.
