### ISSUE TITLE
Restore the "About" option in the navigation 

### ISSUE THREAD

**Issue by Masterjun3** [TASVideos/tasvideos#680]
On the old page it's a tab linking our information page "WelcomeToTASVideos".
This option is currently hidden in the "Home" dropdown (which very much shouldn't be a dropdown, but that can be a different issue), and is poorly titled "Welcome". It should be "About" like on the old page and it's own option, preferably at the very right end of the list.

We do have the Welcome banner, but it only appears on the frontpage. A lot of links are to publications where the banner doesn't appear.

This tab is incomparably important to absolute first timers to our page. So important in fact that I personally count it as go-live critical.

**Comment by vadosnaprimer** [comment]
I agree that it's very important. Not only to people who see the site for the first time, but also for people who need to reread info that is posted or linked there. Basic principles and spirit of the site, feels worth having easily available at all times.
