### ISSUE TITLE
Avatar format possibilities should be written down

### ISSUE THREAD

**Issue by meshuggahtas** [TASVideos/tasvideos#682]
Doesn't specify what format is allowed. 

The following avatars works: PNG, JPG, WEBP, GIF
https://upload.wikimedia.org/wikipedia/commons/4/4a/100x100_black_and_white_pixels.png
https://upload.wikimedia.org/wikipedia/commons/a/aa/Logo_100x100.jpg
https://upload.wikimedia.org/wikipedia/commons/4/41/Webp-minilogo.webp
https://upload.wikimedia.org/wikipedia/commons/b/ba/Rotating_earth_%28Very_small%29.gif

edit: Currently the avatar related informations are @ https://tasvideos.org/Profile/Settings

**Comment by TiKevin83** [comment]
we'll want to only allow PNG/JPG/GIF to ensure integration with open graph tags like the poster avatar coming through in links to forum posts

**Comment by meshuggahtas** [comment]
Oh open graph okay. I guess WEBP could still be added?

**Comment by TiKevin83** [comment]
What I'm saying is even though it has good browser support now it would be helpful to the open graph tags to block webp for now as it isn't supported

**Comment by meshuggahtas** [comment]
Sorry, misinterpreted the protocol. 

- Twitter for example allows WEBP https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary-card-with-large-image 
- https://ogp.me/ doesn't lists PNG nor GIF. 
- Facebook has what you suggest, PNG/JPG/GIF only https://developers.facebook.com/docs/sharing/webmasters/#images

**Comment by adelikat** [comment]
Updated the description to include allowed formats.  This is just a wiki page edit so further discussions should be moved to the site and not the issue tracker
