### ISSUE TITLE
Switch code embeds to dark mode when it's enabled

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#684]
https://staging.tasvideos.org/Forum/Topics/2012?CurrentPage=3&Highlight=406381#406381

![изображение](https://user-images.githubusercontent.com/7092625/147368828-4d869ab6-1fa7-412d-b1f6-85bce8dd19a5.png)

https://staging.tasvideos.org/EmulatorResources/Mamerr/MAR

![изображение](https://user-images.githubusercontent.com/7092625/147368834-389691fc-8dcc-4f1a-a800-4d7ffe5916a0.png)

In dark mode code embeds with defined syntax stay in light mode. Should probably ping @Zinfidel too.

**Comment by TiKevin83** [comment]
will need to swap out prismjs's css based on dark mode

**Comment by TiKevin83** [comment]
light
<img src="https://user-images.githubusercontent.com/38826675/147690308-3dc6bd59-5a78-4ae0-9936-cfe134a028b0.png" width="500">

dark
<img src="https://user-images.githubusercontent.com/38826675/147690423-a9d66545-a163-4dbe-937a-f94a33ab77d6.png" width="500">
