### ISSUE TITLE
Search results should go straight to the publication page when clicked

### ISSUE THREAD

**Issue by FitterSpace** [TASVideos/tasvideos#685]
The new search bar is awesome and works pretty much flawlessly as far as I can tell. But I think the experience could be improved a bit if the links on the search results went straight to the publication page instead of requiring an extra click to get there. Here's what I mean:

Say you search for Super Mario Bros. and click the first search result.
![image](https://user-images.githubusercontent.com/22065181/147369127-abbf1a20-dd8c-4a24-8c12-886623f1de0f.png)

I assume that most people that search for a game and click on it in the search results want to see the publications for that game. Instead, clicking on the Super Mario Bros. link will take you to this page, which I think is a little confusing:
![image](https://user-images.githubusercontent.com/22065181/147369166-a623bbba-dbf3-4d01-9907-ca8aa4a29646.png)

The description and the information about the game below that are fine, I think that's good to have. But I think the list of publications should be shown below that. Or maybe clicking on the search result could take you straight to the publication page, since that's what people are most likely interested in when they search for a game. There could be links to the publication history, submissions, and user files on the publication page so people can still access those. Linking to this extra page that calls TASes "publications" may be confusing for people not familiar with how TASVideos operates. They probably just want to see the list of TASes for a game when they search for it.

Also, there's a heading at the bottom for "Roms" which I don't understand the purpose of. I know TASVideos doesn't distribute roms, so I thought it would be for rom hack patches or something like that, but I haven't found a game with any roms listed under it. I think this could cause some confusion and I don't want people getting the impression that TASVideos distributes ROM files for games they shouldn't. I think this could be improved by only having a section for Roms if there is a rom file there to begin with. If I'm misunderstanding the purpose for that section, let me know. But I could see how it can be confusing since I'm a bit confused by it myself.

**Comment by adelikat** [comment]
This page is intended.  It has all the publications, submissions, user files, and game resource pages.  Isn't it better to see all content for a game?  What if there are no publications, but there is a cancelled submission or an interesting WIP?
