### ISSUE TITLE
Can't remove an user not found from authors list

### ISSUE THREAD

**Issue by ThunderAxe31** [TASVideos/tasvideos#688]
Repro:
1. Get to submission form: https://staging.tasvideos.org/SubmitMovie
2. Add an author name of an user that doesn't exist, or replace the sole author with a user name that doesn't exist (eg: stinkymario)
3. Fill the other mandatory fields, game name, ROM name, comments and explanations, and add an acceptable zipped movie file
4. Hit Preview button
5. Hit Submit button
6. The submission form will spawn an error notice in form of red text under the last author field (eg: "Could not find user: stinkymario")
7. Try to remove the name of the user that doesn't exist, replace it with an appropriate user, etc.
8. Hit Submit button again
9. You will still get the same error notice, no matter what. The only workaround is refreshing the page and refilling every field from scratch, and avoid inputting any incorrect username in the authors list, otherwise you're stuck again.

**Comment by Masterjun3** [comment]
I couldn't reproduce the issue.

After either removing the wrong author or replacing it with a correct author, the error went away and a submission was created.
