### ISSUE TITLE
[UI Request] Combine Rating Pages

### ISSUE THREAD

**Issue by SamsaraTAS** [TASVideos/tasvideos#690]
Currently, publication ratings are separated into two pages: One for rating the movie yourself, and a separate one for viewing ratings. Given how often the rating system as a whole has been criticized over the years for being unnecessarily labyrinthian, it makes sense to me to combine these two separate pages into one, allowing people to both rate a movie and see others' ratings on a single page.

I made a quick MSPaint mockup of what it could look like:
![image](https://user-images.githubusercontent.com/14018768/147600653-cf1804de-eb45-47c3-b149-fd983cf815eb.png)

As a bonus, this would remove the Votes button from publication pages, slightly de-cluttering the big mass of buttons that it currently is, and possibly helping to refine the proposed organization changes in #689 

We could also drop Technical Rating while we do this. I don't think anyone would miss it.

**Comment by vadosnaprimer** [comment]
I agree. Also my biggest issue (sorry for taking so long to actually try this out!) is that there's no way to rate the movie without visiting any new links? Also I'd round current common rating to 1 fractional digit, because importance (and impact) of the second one is vanishingly small.

**Comment by ThunderAxe31** [comment]
My view about improving the rating system is much more drastic:
1. Merge entertainment and technical.
2. Have 1-5 rating value, no decimals (like Google reviews, Playstore, Amazon, etc.)
3. Viewing and rating without leaving the movie page at all.

Also, it would be cool to put the rating along with the post, like a review comment of... Google reviews, Playstore, Amazon, etc.
