### ISSUE TITLE
Font stack isn't being used

### ISSUE THREAD

**Issue by msikma** [TASVideos/tasvideos#691]
I noticed the new website shows up as using Helvetica for me personally (this is the default sans-serif font on macOS). However, when I checked the CSS I saw that there's a different font stack defined:

--bs-font-sans-serif: system-ui,-apple-system,"Segoe UI",Roboto, "Helvetica Neue", Arial,"Noto Sans","Liberation Sans",sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol","Noto Color Emoji"

I think this is a really nice font stack, but it doesn't get used because it gets overwritten by another rule:

<img width="684" alt="Screen Shot 2021-12-29 at 13 58 17" src="https://user-images.githubusercontent.com/1507745/147664917-19ba58af-5a98-482e-987d-29a7116f68a2.png">

When I disable the `body: sans-serif;` rule the font stack comes through.

**Comment by TiKevin83** [comment]
We had an accessibility request from a different user to use system default fonts instead of the forced font stack from bootstrap

**Comment by msikma** [comment]
I'm curious as to the details of their request. Obviously they have an accessibility need that isn't being met, but I feel there has to be a better solution than changing the stack to use the default browser font only.

Using the default `sans-serif` uses the browser default font, not the system default font. The browser default fonts are actually not considered the best options for accessibility purposes—they're mostly just there because they've always been there. They don't support multiple weights and they're not designed to be as readable as some of the newer fonts like Roboto or San Francisco. On macOS in particular, it's been long known that Helvetica Neue (which still comes with the system by default) is always a better font than Helvetica, not to mention the fact that Helvetica has an improper baseline that causes all padding to look off.

I'm guessing they probably have a custom font set and want that custom font to come through? That's understandable, and unfortunately Chrome does not have an option for forcing specific fonts to override site CSS like Firefox does.

I think it might be a better option to implement this as a switch of some sort, though. A persistent switch can be easily implemented without any need for backend work (I can give an example), and this would allow for the majority of users to see their actual system fonts (San Francisco for macOS, Segoe UI for Windows, Roboto for Android).

**Comment by TiKevin83** [comment]
We have a similar switch for light/dark mode so I could definitely implement that, I'll see if I can connect with the other user again for more detail

**Comment by meshuggahtas** [comment]
> We had an accessibility request from a different user to use system default fonts instead of the forced font stack from bootstrap

I have no knowledge of an accessibility issue that requires system default font. Acccessibility tools are not visual, a common misconception. Custom fonts can be used in browsers.

I believe a single users' wish which is probably solvable by other means shouldn't override the overall community's "wishes".

**Comment by msikma** [comment]
> edit: "Chrome does not have an option for forcing specific fonts to override site CSS like Firefox does."

> There is at least 3 different ways to accomplish this (solving the issue for that accessibility required user): [..]

Oh yeah, there are ways to do it—I just meant it has no way to do this out of the box.

Granted, I believe if someone needs a special font to make websites accessible, the best way to solve it would be through something like a custom stylesheet or add-on like you mentioned, since that way it will work for all websites instead of just this one.

I see a PR has already been made and merged and I think that should be sufficient, so as far as I'm concerned this can be closed. But like I mentioned before, if there are more details about the user's specific needs I could possibly give a suggestion to help with it.

**Comment by meshuggahtas** [comment]
I'm also up for helping any accessibility required person, forgot to mention this last time.
