### ISSUE TITLE
Unread sent PMs are not flagged from old site

### ISSUE THREAD

**Issue by ThunderAxe31** [TASVideos/tasvideos#697]
This is an unread PM I just send in staging site:
![image](https://user-images.githubusercontent.com/36802254/147794813-0cda4bbc-0a6a-4c52-be5d-c51ab138fbfe.png)

And this is an unread PM I sent one years ago:
![image](https://user-images.githubusercontent.com/36802254/147794882-37702b93-ca11-4527-8c6d-146ce07bbdbf.png)

In the second screenshot, it's supposed to display the paper plane icon and the red delete button, but it doesn't.

**Comment by adelikat** [comment]
Which page are you looking at?

**Comment by ThunderAxe31** [comment]
https://staging.tasvideos.org/Messages/Sentbox

**Comment by adelikat** [comment]
How do you know the 2nd is unread?

**Comment by adelikat** [comment]
If the user has seen the PM, you cannot delete it

**Comment by ThunderAxe31** [comment]
> How do you know the 2nd is unread?

because it's unread on current site

![image](https://user-images.githubusercontent.com/36802254/147795454-8954ea3a-f591-4c4e-9cb3-618c0f316a50.png)

**Comment by TiKevin83** [comment]
I'm thinking this may not be fixable after the import has happened now?

**Comment by adelikat** [comment]
yeah, too late.  Plus, the importer code wasn't wrong, there was just multiple ways to interpret "read" with phpbb2 code.  In this example, maybe the inbox was opened but the actual message wasn't?
