### ISSUE TITLE
User timezone setting is not imported from old site

### ISSUE THREAD

**Issue by ThunderAxe31** [TASVideos/tasvideos#698]
As in title. I logged with my account in staging site, and I check the time zone setting, and I found it set to the first value, +11.

**Comment by YoshiRulz** [comment]
Repro'd as written when logging in on day 1. After setting it once it worked properly.

**Comment by adelikat** [comment]
Yeah, the importer did its best to convert from offset to timezone and didn't do so good.  Nothing we can do about it at this point though, other than for everyone to pick their timezone themselves.  It was only a rough guess anyway as it would find the first timezone in a given timezone offset, which is likely wrong.
