### ISSUE TITLE
Feature Request: Helper Buttons for Submission Markup

### ISSUE THREAD

**Issue by TiKevin83** [TASVideos/tasvideos#706]
The submission markup could have helper buttons to insert things like the YouTube embed module

**Comment by vadosnaprimer** [comment]
Submission form has "Encode Embedded Link" filed for this.

**Comment by TiKevin83** [comment]
![image](https://user-images.githubusercontent.com/38826675/147860626-fdb5f905-9c21-4745-a0a0-781bc82487af.png)
this section should have a link to the text formatting rules and helper buttons for common modules is what I'm referring to, does that have an existing issue?

**Comment by adelikat** [comment]
Oh hey, we built this some months back, is' a helper bar for any wiki markup, which includes submissions, and one of the buttons is the youtube module helper
