### ISSUE TITLE
Discord links generated by editing posts are broken

### ISSUE THREAD

**Issue by TiKevin83** [TASVideos/tasvideos#708]
The edit link:
[4:36 PM]  BOT  TASVideoAgent: Post edited by Noxxa (Awards: SNES TASer of 2021 - Nominations open!)  https://tasvideos.org/p/510967#510967

The actual URL should be https://tasvideos.org/Forum/p/510967#510967

**Comment by vadosnaprimer** [comment]
It used to generate those shorter links for forum and post, and the site would just redirect to the full link. Now it generates full link for forum but short link for post, which doesn't redirect.
