### ISSUE TITLE
"New Post" Indicator for Boards and Topics

### ISSUE THREAD

**Issue by scrimpeh** [TASVideos/tasvideos#709]
Old feature from phpBB: When there was a new post made in a board since you last visited, the icon for the board in the forum overview, and the icon for the topic in the topic list would light up.

I found this an immensely useful feature for keeping track of activity and would like to have some kind of notification icon for new posts again. 

This would probably also necessitate a "Mark All Unread As Read" button somewhere.

**Comment by vadosnaprimer** [comment]
That's very useful yes. I used it every day until the old forum started running out of storage space and failing to mark them as read. For people without email notifications this is probably mandatory?
