### ISSUE TITLE
Existing Game Results from Google Search Are Dead Links

### ISSUE THREAD

**Issue by TiKevin83** [TASVideos/tasvideos#714]
https://tasvideos.org/Wiki/PageNotFound?possibleUrl=Game%2FGbc-pokmon-yellow-version

The game page works from this URL now https://tasvideos.org/446G

**Comment by meshuggahtas** [comment]
I'm not sure but probably https://search.google.com/search-console/welcome can be used to fix (enhance and update) google search result problems.

**Comment by meshuggahtas** [comment]
Google link to test: https://www.google.com/search?q=tasvideos+game+gbc+pok%C3%A9mon

Note that the links are dead because they are indexed pre 2022.

**Comment by Masterjun3** [comment]
This seems to be fixed because google reindexed and now uses the /123G pages.
