### ISSUE TITLE
Clicking the image on a publication should link out to the video

### ISSUE THREAD

**Issue by Meerkov** [TASVideos/tasvideos#723]
Right now, a submission has a blue "Watch ->" button below the image. This is fine...

But I think it would be cleaner/better/more intuitive to have a floating "Watch ->" on top of the image, and clicking anywhere on the image will lead to the video. (Alternative text: "Watch on YouTube" or "Watch on NicoNico" depending on the platform).

This matches the behavior on YouTube (clicking image opens that video), and is an intuitive action. This also results in 1 less button below the image (currently there are 6, and it's a little cluttered).

**Comment by vadosnaprimer** [comment]
There can be several links for watching, even on the same site. For example a CamHack encode.

**Comment by adelikat** [comment]
While there can be multiple watch buttons, most only have 1.  In those cases, the image could just do the same thing as the button.

Maybe when there are more than 1, clicking brings up a quick menu to pick which one

**Comment by vadosnaprimer** [comment]
I don't mind it being an extra thing, but I don't want it to _replace_ existing buttons.

**Comment by adelikat** [comment]
Agreed
