### ISSUE TITLE
MoviesByAuthor newbie list shows all authors who co-authored a movie with a newbie

### ISSUE THREAD

**Issue by Randomno** [TASVideos/tasvideos#727]
e.g. https://tasvideos.org/Mothrayas/Awards/2020/TASerRookie

Many non-newbie authors are listed because they were involved in a movie with a newbie.

The "newbies=show" parameter works correctly, only the "newbies=only" has an issue.

**Comment by adelikat** [comment]
Bumping up priority as we reach the new year and the need for this module for award nominations
