### ISSUE TITLE
Sorting movie tokens doesn't seem to be supported

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#729]
https://tasvideos.org/MovieTokens (Rating parameters tab):

```
Q - sort by tech quality
E - sort by entertainment
Y - sort by combined rating
U - sort from newest to oldest
V - sort from oldest to newest
S - sort from shortest to longest
L - sort from longest to shortest
F - 1 random movie
```

https://tasvideos.org/Publications/Filter has no way to sort.

So links in https://tasvideos.org/Movies (Special categories tab) that have `RatingX` are not working.

In general, this is a very useful feature when you need to compare movies by rating or publication date.

**Comment by adelikat** [comment]
Will not be supporting rating sort.  It is a post processing calculation, and too expensive.
Random I would say adds negative value.
Length is also a problem as it is post processing now.

Oldest to newest and newest to oldest are fine

**Comment by adelikat** [comment]
Closing this, we have date sort, the others I do not intend to support
