### ISSUE TITLE
Remove PublicationsFromNewestToOldest Page and References

### ISSUE THREAD

**Issue by Yave-Yu** [TASVideos/tasvideos#743]
1. Seems all icon font are not be loaded correctly.
![Screenshot_2022-01-03-10-24-03-069_com android chrome~01](https://user-images.githubusercontent.com/54294476/147896096-bd6ef469-d7e6-4a5a-a8ab-81ee70d97efe.jpg)
2. Filter couldn't sort anymore, but old site could.
3. List has sort feature, but...
![Screenshot_2022-01-03-10-24-24-720_com android chrome~01](https://user-images.githubusercontent.com/54294476/147896126-59ca3e2a-7309-4c74-885d-959be0207c53.jpg)

**Comment by meshuggahtas** [comment]
1 - Try pressing CTRL+SHIFT+R. If not working, write down your platform and browser.
2 - Known issue
3 - Hmm... Is this module even required now that we have the new site? https://tasvideos.org/PublicationsFromNewestToOldest

**Comment by adelikat** [comment]
How is the intent of that module not redundant to the latest publications module that is on the front page? My vote is to remove this page

**Comment by TiKevin83** [comment]
Main priority here is cross-browser testing of the fontawesome icon font, @Yave-Yu can you reply with the browser + device you're experiencing this on?

**Comment by Yave-Yu** [comment]
Mobile phone: Android 11+Chrome

**Comment by TiKevin83** [comment]
It would be helpful to know the exact device, chrome version and system language

**Comment by YoshiRulz** [comment]
CNR tofu. Tested Chrome and Firefox Nightly, LineageOS 17.1 (Android 10), OnePlus 6.

**Comment by meshuggahtas** [comment]
I've tested a lot of Android + Chrome combinations and none of them yielded in font awesome not loading.

- Do you have Javascript enabled?
- Do you see empty boxes or the icons does shown on this site? https://fontawesome.com/v5/cheatsheet Top right sign in icon and many other icons

Here is an image of what you should see:
![pic](https://user-images.githubusercontent.com/31288337/148024642-e6982c4e-814c-4eb1-870e-6b00123c42c1.PNG)

**Comment by Yave-Yu** [comment]
Well...now the first issue is gone on my device.
![Screenshot_2022-01-07-15-56-20-219_com android chrome](https://user-images.githubusercontent.com/54294476/148511138-da3e4493-1ab0-416c-8d0f-5a6ff3215df7.jpg)

**Comment by meshuggahtas** [comment]
Good, also I see some nice chinese/japanese characters at bottom of your image.

So removing https://tasvideos.org/PublicationsFromNewestToOldest remains before closing this issue.

**Comment by adelikat** [comment]
We now have Movies-List-SortV-Limit100 that can replace this page.  At this point, this is a non-devleopment task, so I'm closing the ticket.  Staff will handle this reorg
