### ISSUE TITLE
Record Submission Queue sorting choice

### ISSUE THREAD

**Issue by Zinfidel** [TASVideos/tasvideos#744]
When I look at the submission queue, I like to have it sorted by the Status field. By default, it is sorted by submission date.

I think it would be a nice convenience to record user selections here in cookies/user account info.

**Comment by vadosnaprimer** [comment]
Agreed. Sorting by date makes it look messy and is only needed when you specifically need the oldest (or the newest) ones. When picking what to judge, I only sort by date among unclaimed submissions, and then sert back by status to see the overall picture.

**Comment by adelikat** [comment]
I just don't think this feature request adds enough value.  You can get what you need from a bookmark, you could even link it from your homepage if you want the convenience of having it on the site.
