### ISSUE TITLE
On-hover animated screenshots are broken

### ISSUE THREAD

**Issue by mateon1** [TASVideos/tasvideos#746]
Screenshots that should animate on hover are broken.
An affected example is https://tasvideos.org/3358M which explicitly mentions the screenshot in the movie description.

Looking at the last archived version: http://web.archive.org/web/20211224044323/http://tasvideos.org/3358M.html
The old site used `onmouseover` and `onmouseout` attributes to set the src attribute via Javascript.

**Comment by vadosnaprimer** [comment]
3358M refers to alternative screenshot that was a gif file with a bunch of screenshot from the movie, not to the tooltip text. There were several movies like this and they all mention it in the same manner.

**Comment by mateon1** [comment]
Ah, I see. I checked 3050M and the tooltip for that does work. I'll retitle the issue to refer to animated screenshots, then

**Comment by meshuggahtas** [comment]
Browser + Platform test:
https://tasvideos.org/3050M **OK**
- Android + Chrome: there is no hover, but if I open it in a new tab, I can see the text
- iOS + Safari: same
![mmmmetroid](https://user-images.githubusercontent.com/31288337/150093434-69a02a7a-9238-4fc6-94f9-a7d6220d55c9.PNG)

https://tasvideos.org/3358M **this issue**
- Android + Chrome: nothing, 3358M.png
- iOS + Safari: same

**Comment by adelikat** [comment]
@meshuggahtas : please make a separate issue.  This isn't about the alt text behavior.  It is about publications that had multiple screenshots

**Comment by adelikat** [comment]
The hover feature wasn't built, and I dont' want to build it.  For reasons of accessibility and mobile support, effort vs value, and because it gets in the way of more useful features down the road like the ability to have a gallery of screenshots with a nice view.

Removed the "hover over the screenshot" references that I found on a number of publications including the example one.

**Comment by meshuggahtas** [comment]
I assume there is no issue to create if galleries become a feature. I've initially thought alt text won't fit on mobile screens, but it turns out you can tap it to get full text.

+1 for galleries!
