### ISSUE TITLE
YouTube TASVideosChannel updates inconsistently when adding new urls

### ISSUE THREAD

**Issue by despoa** [TASVideos/tasvideos#749]
While the feature of updating the corresponding YouTube videos on TVC and making them public by adding the URL to the publication page is there, it only works maybe half the time. It certainly doesn't work when adding the URLS in >2 hour successions. TiKevin suggests that it's due to a timed token preventing TVC from being updated.

In addition, as a side effect, all the TVC YouTube links that failed to be updated automatically get put under this entry in https://tasvideos.org/Publications/YoutubeUploaders

![image](https://user-images.githubusercontent.com/30417976/147947312-dbe6315b-42b4-4457-a3aa-2179683b36e9.png)

**Comment by vadosnaprimer** [comment]
I also couldn't get it to update/sync when editing the publication.

**Comment by fsvgm777** [comment]
Of note that it can also happen when publishing a movie, as has happened with Gamera (4572M) just now.

**Comment by fsvgm777** [comment]
Okay, so after making sure the "Unknown user" was gone in the page despoa linked (which linked to the publication I made yesterday, I made a dummy minor edit on that, and it synced the YT description.

**Comment by adelikat** [comment]
A fix was made that was causing this to be unreliable, closing this ticket
