### ISSUE TITLE
Divide "Latest Publications" of home page into separate lists

### ISSUE THREAD

**Issue by ThunderAxe31** [TASVideos/tasvideos#754]
Remember how the home page used to have two separate lists for Vault and Moons publications? These two lists were at some point merged in one, after that Vault was abolished, in order to remove the feeling of inferiority towards movies considered less entertaining.

However, now that we a much more definite list of goals, I think it would be useful to suddivide the recently published movies into separate lists. Specifically these:

- Major Skip
- No Major Skip
- Full Completion
- Moons (which I still strongly [suggest](https://tasvideos.org/Forum/Topics/22917?CurrentPage=3&Highlight=511194#511194) to rename to "Alternative Goals" or something)

Opinions, anyone?

**Comment by adelikat** [comment]
I think the homepage needs less lists of things, not more.  It's overwhelming and not good UX especially for a landing page.

I'll defer to @vadosnaprimer and @MemoryTAS

**Comment by MemoryTAS** [comment]
yeah I don't think it's really needed. There's things I would like to talk about in regards to TAS navigation and discover features but I don't think this is it.

**Comment by vadosnaprimer** [comment]
I wouldn't mind having links to those extra lists as separate pages.

**Comment by adelikat** [comment]
We should talk about a tier rename from Moons to Alternate Goals, that's a pretty good idea.

As for separate pages, that is a wiki editing problem, or possibly the need to create new tags to use for movie list filtering, all of which can be done from a UI and are not a development problem.  Closing this ticket
