### ISSUE TITLE
Forum thread titles and page numbers can be hard to read in dark mode

### ISSUE THREAD

**Issue by FitterSpace** [TASVideos/tasvideos#762]
This might be a nitpick, but I find that the dark blue text can be hard to read in the dark theme. Forum titles are generally okay but the page numbers are a bit hard for me to read sometimes. I find that making the text brighter and a bit more saturated makes a big difference in how readable it is, without messing up the site's overall theme.

Here is a before and after example:
![image](https://user-images.githubusercontent.com/22065181/147991437-2aa1f7cd-d5b5-4c8f-8050-6f618494d6d3.png)

**Comment by vadosnaprimer** [comment]
Pics?
