### ISSUE TITLE
"No YouTube" page not showing all results

### ISSUE THREAD

**Issue by Zinfidel** [TASVideos/tasvideos#764]
https://tasvideos.org/NoYoutube

![image](https://user-images.githubusercontent.com/1929934/147995996-d18bbf5d-2761-465c-b1a2-a33c80053978.png)

From memory and asking in the publisher channel, we know that there should be many more entries on this page for the obsoleted section. Right now there is only one entry showing up in the obsoleted section. There should definitely at least be some mupen and PCSX movies in that list.

Note that the list was larger on the deprecated site, so if it's possible to access the old page it might be of use.

**Comment by Masterjun3** [comment]
Can you maybe give examples of movies that should be there? Maybe the non-youtube link was not imported and so the movie instead moved to https://tasvideos.org/UnstreamedMovies ?

**Comment by Zinfidel** [comment]
Indeed many of the entries in the unstreamed movies page originally appeared in the no-YouTube list. For example, this one:
https://tasvideos.org/1272M

Now that I've looked at this, I think I might know what is going on. The one entry in the NoYT list has only a nicovideo streaming link, while the link above has no streaming link at all.

Perhaps on the new site, the NoYT "filter" is finding only entries that have streaming links but none of them are YT links, whereas before it would also include movies without streaming links at all (thus causing some overlap with the unstreamed list).

I guess this may not actually be a bug but simply a shift in perspective on how these lists are generated.

**Comment by adelikat** [comment]
That's precisely how it was coded.  Intentional, but changeable if people want it

**Comment by Zinfidel** [comment]
I'll share with publishers to see what everyone thinks, but now that I understand what is going on I don't think this needs to change.

**Comment by adelikat** [comment]
I'll close for now, reopen if you guys decide you want this behavior

**Comment by EZGames69** [comment]
I definitely think having the no youtube list work as it previously did is useful for us Publishers.  It’s one of the first things I look through when I want to find movies to re-encode

**Comment by despoa** [comment]
I agree with EZGames69.

**Comment by vadosnaprimer** [comment]
Doesn't it make sense to just use `unmirroredmovies` now instead? If there's no streaming URL, then by extension there's no YT URL, so one can just pick items from that list like from the no-yt list before, no?

**Comment by Zinfidel** [comment]
I agree with @vadosnaprimer - at this point the unstreamed movie list serves the same purpose and will contain the exact same info that we've been using, since the part of the Venn diagram that belonged to the NoYT list has been demolished.

The NoYT page still serves a purpose as a canary for now-rare cases of movies winding up with only bad streaming options that we can check occasionally.
