### ISSUE TITLE
Remove Custom Embed Logic from Discord Bot

### ISSUE THREAD

**Issue by TiKevin83** [TASVideos/tasvideos#771]
Now that open graph tags are working we can drop the custom embeds created for discord notifications and work to improve the open graph tags if/when missing to improve social media sharing experiences in general

**Comment by ThunderAxe31** [comment]
I don't dislike the discord embeds, my issue is about the "update from <user>" line, because it's redundant, as the blue link already tell everything (with few exceptions that need to be fixed).

However, I don't know what open graph tags are. Can I have an example image to see what they look like?

**Comment by TiKevin83** [comment]
Current bot notifications:
![Screenshot_20220104-102628_Discord](https://user-images.githubusercontent.com/38826675/148082683-a760aae2-70f5-4de6-918a-81a480a4cc0d.jpg)

Open Graph Embeds (automatically shows up in Facebook, Twitter, Discord, etc now)
![Screenshot_20220104-102310_Discord](https://user-images.githubusercontent.com/38826675/148082946-1be2d7ac-77ed-4c60-92cb-6cd44600edda.jpg)

**Comment by ThunderAxe31** [comment]
Would it be possible to make it like this?
![148082946-1be2d7ac-77ed-4c60-92cb-6cd44600edda](https://user-images.githubusercontent.com/36802254/148126209-89508708-ed5e-4ed6-a6be-2069ee0badc1.jpg)

**Comment by TiKevin83** [comment]
I think that depends on how the site handles OG tags which would mean no in Discord? But really not sure
