### ISSUE TITLE
Sandbox-like page for testing CSS changes which showcases every UI component

### ISSUE THREAD

**Issue by YoshiRulz** [TASVideos/tasvideos#774]
I can't find an example of this but I'm certain I've seen it in an Android dev context.

edit: photoshopped, but this is what I'm going for ([source](https://github.com/adapta-project/adapta-gtk-theme)):
![Materials](https://raw.githubusercontent.com/adapta-project/adapta-github-resources/master/images/Materials.png)

**Comment by meshuggahtas** [comment]
Is this even possible to show all of them on a single page? The major pages with additional design are Frontpage, Publications, UserFiles, Profile, Forum...

And then there is the https://tasvideos.org/TextFormattingRules/ListOfModules which would be bloated if there would be an example already loaded on the site for each module.

Unfortunately I don't have any suggestion at the moment.

**Comment by adelikat** [comment]
With razor pages, this isn't feasible, there is no componentization concept, which is its huge failing ultimately.

Closing this ticket as "won't fix".  Maybe one day when the site is all javascript and using a framework like vue or react.  Then a component library and a storybook sandbox is not only possible, but expected.
