### ISSUE TITLE
Missing images/files in wiki and forum posts

### ISSUE THREAD

**Issue by bigbass1997** [TASVideos/tasvideos#777]
Various pages and posts that use content from `http://media.tasvideos.org/` are now broken; however there are a few instances where they still work.

Broken examples:
https://tasvideos.org/GameResources/DOS/Jetpack#NamingConventions
https://tasvideos.org/Forum/Posts/119478#119478
https://tasvideos.org/Forum/Posts/81290#81290 (.avi files)

Still working examples:
https://tasvideos.org/Forum/Posts/184070#184070
https://tasvideos.org/1669S (seems everything under `http://media.tasvideos.org/autosnaps/` still exists)

If this is just a problem where the URL path has changed, and the files still exist somewhere, I can fix up the wiki at the least. However I'm thinking that maybe the missing files weren't copied over during the migration from the old site?

**Comment by adelikat** [comment]
Avi files are gone, I removed them.
For the images, they have all been "flattened" and exist in the root level
Autosnaps are an exception as a special rule was put in since they were so common

**Comment by bigbass1997** [comment]
Thanks. I've fixed all broken images I could find on the wiki that used `media.tasvideos.org`.
