### ISSUE TITLE
Missing reference to Submissions.rss

### ISSUE THREAD

**Issue by SmashManiac** [TASVideos/tasvideos#786]
There does not appear to be any link or metadata on the Submissions page referencing Submissions.rss, so its existence cannot be discovered through the website.

**Comment by meshuggahtas** [comment]
I think the only place it's listed is this particular page:
https://tasvideos.org/XMLDataFeed

**Comment by meshuggahtas** [comment]
The legacy site used to show the **combined.rss** at the row of Page history and other links. 
![rss](https://user-images.githubusercontent.com/31288337/148431110-c9bab6b8-5e1f-465b-b84c-ba503f8752a5.PNG)

I'm unsure how many visitors could used it, but I would suggest adding a link to all RSS feeds (XMLDataFeed) to the new site to the same place. Quick mock up:
![rss2](https://user-images.githubusercontent.com/31288337/148432611-c23cb19e-d0a9-45fb-aaa2-e57943a1fed8.PNG)

**Comment by adelikat** [comment]
added it back to the subs-list page
