### ISSUE TITLE
SSL + Browser testing

### ISSUE THREAD

**Issue by meshuggahtas** [TASVideos/tasvideos#787]
An issue for solving feos'  and potential future visitors problem, who is not able to visit https://tasvideos.org with:
- Win7 + Chrome
- Win7 + Opera 

while they can with
- Win7 + Firefox 
- Win7 + virtualized Ubuntu + Opera

because of **ERR_CERT_DATE_INVALID** in their browser.

Notes: 
- Testing in progress, I'm testing with browserstack live machines, so there can be false positive results
- Only testing OSs with latest browsers
- Removed combinations where https://caniuse.com/?search=es6 is not supported, added Partial support where it's only partially supported

Current conclusions:
- The DST Root XA C3 expired cert is OK, used for Android compatbility, more info https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/
- List of valid certificates https://letsencrypt.org/certificates/
- Certificate compatibility https://letsencrypt.org/docs/certificate-compatibility/
- Firefox uses the Mozilla's CA Certificate Program, which is why this browser works even when other browsers fail on specific OSes. The current cert being used can be find here https://wiki.mozilla.org/CA/Intermediate_Certificates

Known to work perfectly:
- iPhone
- iPad
- Android

Verified not working combinations:
- macOS El Capitan and earlier (2015 October, unsupported since 2018 October) with any browser (maybe except firefox?) **are not supported by Let's Encrypt**
https://live.browserstack.com/dashboard#os=OS+X&os_version=El+Capitan&browser=Safari&browser_version=9.1&device_browser=chrome&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Ftasvideos.org%2F&speed=1

Unknown:
- Windows 8.1 + IE 11 (ES6: partial support): browserstack problem
https://live.browserstack.com/dashboard#os=Windows&os_version=8.1&browser=IE&browser_version=11.0&device_browser=chrome&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Ftasvideos.org%2F&speed=1
- Windows 7 + IE 11 (ES6: partial support):  browserstack problem https://live.browserstack.com/dashboard#os=Windows&os_version=7&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Ftasvideos.org%2F&speed=1

TODO:
Windows 8 ie 11				Turn on TLS 1.0, TLS 1.1, TLS 1.2 in Advanced settings.

OSX Yosemite Opera 12.15	Fatal error 70 Handshake failed
OSX Mountain Lion opera 12.15
OSX Snow Leopard opera 12.15
Windows 8.1 opera 12.16

My SSL certificate chain:
- https://crt.sh/?q=cabd2a79a1076a31f21d253635cb039d4329a5e8
- https://crt.sh/?q=a053375bfe84e8b748782c7cee15827a6af5a405
- https://crt.sh/?q=c60426ae5cdc50d0bc0ce6b4f32522dd1da7b104

**Comment by vadosnaprimer** [comment]
Thank you! WinXP may not be worth testing since browsers that work on it are **super** outdated (don't ask me why I know this).

**Comment by nattthebear** [comment]
You can also look at the handshake simulation section of https://www.ssllabs.com/ssltest/analyze.html?d=tasvideos.org

**Comment by meshuggahtas** [comment]
That's an awesome link! Since I'm at the very beginning of understanding SSL, I can only conclude the following:
- Safari 9 / OS X 10.11 == macOS El Capitan and earlier + Safari 9.1: SSLLabs says OK, but I got the certification expired stuff. This should prove that the combination should work but the certification has a problem?

**Comment by nattthebear** [comment]
Seems like the handshake simulator only looks at SSL protocol stuff, not certificate stuff: https://success.qualys.com/discussions/s/question/0D52L00005eO2vhSAC/taking-certificate-trust-into-account-for-handshake-simulation

**Comment by meshuggahtas** [comment]
Testing 7 different SSL/TLS checker, I've found 2 where it says there is a problem:
- https://www.sslchecker.com/sslchecker
![ssl](https://user-images.githubusercontent.com/31288337/148057586-f5f51233-8fea-465a-9681-2453501e2590.PNG)
That's what my macOS El Capitan also says (invalid date for DST Root XA C3 expired at 2021.09.30)
- https://observatory.mozilla.org/analyze/tasvideos.org?third-party=false#tls
Doesn't mentions what is the problem

**Comment by TiKevin83** [comment]
@meshuggahtas I'm very confused why you tested a bunch of browsers we can't support due to being pre-ES6, also that SSLChecker report of a missing root cert isn't an issue because the missing one is expired.

I believe the cert expiring in the future to be caused by our traffic being intercepted, which we can't fix.

**Comment by meshuggahtas** [comment]
The bunch of browsers were tested because of the issue itself (1 user having difficulty to browse HTTPS tasvideos in 2 browsers but 1) and this particular issue https://github.com/TASVideos/tasvideos/issues/743 (1st time I see someone doesn't loaded font awesome on Android which I tested heavily before tasvideos went live).

"... the missing one is expired" --> and that's the error what I've also got in some tests so... this is an issue right?

**Comment by TiKevin83** [comment]
https://tasvideos.org/WelcomeToTASVideos#MinimumSystemRequirementsForSiteBrowsing
I checked on browser support and made this edit to the welcome page. Bootstrap is pulling in use of a feature that is slightly ahead of ES6 but it doesn't change the support table much.

**Comment by meshuggahtas** [comment]
Oh, that was a good idea and execution of placing a note for visitors about minimum requirements.

I'm going to verify your table of OS+Browser versions with BrowserStack now.

**Comment by meshuggahtas** [comment]
Tested by trying to click on the dropdown of Dark Light Auto icon.

Safari 11+ might be enough:
https://live.browserstack.com/dashboard#os=OS+X&os_version=High+Sierra&browser=Safari&browser_version=11.1&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Ftasvideos.org%2F%23&speed=1
Internet Explorer: can't test right now, browserstack problem
Chrome, Firefox OK

Not sure if this test would be valid for iOS and Android too.

Did you wrote the Android 4.4 from the following table? I think it should be 5.4 then and iOS 11, in case they can be lowered because no other requirement has higher version dependence (which I don't know, I'm not familiar with the whole technology of the site)
![es6](https://user-images.githubusercontent.com/31288337/148112092-3069efa4-e686-419a-81d8-6cc17f950c40.PNG)

**Comment by TiKevin83** [comment]
4.4 is as far back as I could test with Chrome, the webview engine isn't a critical support path for android since that only matters for viewing the site within an app

**Comment by meshuggahtas** [comment]
Okay, I just wanted to be sure, thanks!

**Comment by meshuggahtas** [comment]
Conclusion:
- Use Firefox if you have issues with ERR_CERT_DATE_INVALID
- The server's SSL configuration is valid and working
- Upgrade your system to minimal requirements for visiting documented by TiKevin83 @ About (WelcomeToTASVideos). 
Closing issue.
