### ISSUE TITLE
Updating Github Wiki links

### ISSUE THREAD

**Issue by meshuggahtas** [TASVideos/tasvideos#788]
Now the site is live, will be there a demo.tasvideos.org site for demo purposes? Asking before prematurely changing links from demo to www.

Links to be changed:
- README.MD bottom demo site
- https://github.com/TASVideos/tasvideos/wiki/Project-Structure bottom Api link
- https://github.com/TASVideos/tasvideos/wiki/Quality-Assurance online validators link

**Comment by adelikat** [comment]
Links updated
