### ISSUE TITLE
Issues with the "www." subdomain

### ISSUE THREAD

**Issue by Masterjun3** [TASVideos/tasvideos#790]
If you put "www." in front of the tasvideos.org URL, you get to our site, but you don't retain your site data, so you're logged out.

Another question would be whether we even need to have a www URL instead of just making it redirect to the original URL without it.

**Comment by nattthebear** [comment]
`www.tasvideos.org` should 301 to `tasvideos.org`.

**Comment by adelikat** [comment]
It should, and the attempt was made.  This is an nginx issue and we currently aren't sure why it is failing to redirect.

**Comment by Invariel** [comment]
Issue has been resolved.  nginx decided to play nicely today.
