### ISSUE TITLE
There should be a guide on how to use the tags when you're posting on the forum

### ISSUE THREAD

**Issue by FitterSpace** [TASVideos/tasvideos#795]
This is more of a special request than a critical issue, but I think the forum should have a guide on how to use the different tags that can be seen here:
![image](https://user-images.githubusercontent.com/22065181/148108779-feb34fb5-6e33-481e-a469-859d472b73ca.png)

I wanted to link to another thread so I clicked the "thread" buttons, then it spit out the following text: [thread][/thread]

I wasn't sure what to do here and it took me a little while to figure out that you're supposed to format it like this:
[thread=#####]hyperlink text[/thread]

I believe the old forum had a guide that showed you how to format these things when you hovered over the button. It would say something like the format I posted above. Some forums, like github, have a markdown guide you can click on to read about all the different text formatting options and such. Maybe that could also work on TASVideos if the hovering thing doesn't work out.

**Comment by Climax12345** [comment]
First time first profile first peoject
