### ISSUE TITLE
Forum thread titles should always be the same height

### ISSUE THREAD

**Issue by FitterSpace** [TASVideos/tasvideos#797]
This is a minor issue, but forum threads with page numbers below them are taller than forum threads with only one page. I personally think the forum page would look cleaner if every row in the table was the same height.

![image](https://user-images.githubusercontent.com/22065181/148110371-c7cadf8c-6142-40f8-9983-16d761a67375.png)

**Comment by Masterjun3** [comment]
I disagree.

**Comment by Masterjun3** [comment]
Having the same height everywhere would put very much whitespace on the screen for no purpose.

Imagine it here:
![image](https://user-images.githubusercontent.com/22375320/148112239-16b38b3e-4a14-42f0-994a-1e755efb0bdf.png)

**Comment by FitterSpace** [comment]
I understand. It makes sense to do it that way since it benefits smaller screens. I was pretty pissed when I got a notification for a response that just said "I disagree," but I'm glad you came back with a good reason for it I didn't consider.
