### ISSUE TITLE
It's impossible to distinguish between topics with read and unread posts

### ISSUE THREAD

**Issue by FitterSpace** [TASVideos/tasvideos#799]
I believe this issue has already been talked about, but ikuyo suggested to have bold text for unread posts and neutral text for posts you're already read, like this:

![image](https://user-images.githubusercontent.com/22065181/148111073-e6bf5a86-554d-4398-a37a-94c3d5c7e03c.png)

The old forum had a symbol to the left of the thread title, which I thought worked fine, but this is a clean solution without having to use symbols to show which posts you're up-to-date on.

**Comment by TiKevin83** [comment]
There was a lot of debate back and forth about visited styles on links in the new site, we settled on not having visited styles as it seems to not be a common pattern in the modern web and I've read some articles that site it as a security concern (sites being able to change behavior based on your browsing history could lead to pulling your history from computed styles).

**Comment by Masterjun3** [comment]
Note that there are other ways than visited styles (which was debated) to mark whether you read a thread or not.
This however requires a lot of tracking on the server side, so this is a big problem that isn't solvable too easily.
However, it's obvious that users want to know about new or old posts when browsing, so we should at least have one open issue like this.

**Comment by trlkly** [comment]
Visited vs. unvisited links shouldn't be a security concern in modern browsers, as they all have modified how they style those links to prevent sniffing. 

And every forum I use still distinguishes between topics where I've read all the content and topics where there is new content. I don't think any of them use visited styles--they just keep track of what the last post you visited was. (Visited styles, however, are a fast implementation as long as the topic URL already changes.)

**Comment by Masterjun3** [comment]
The topic URL doesn't change even with new content. That's why the previously implemented visited styles were misleading and were removed again.

Keeping track of the latest posts every user has visited in every topic in a database table would require updating the table on every user visit, which was decided to be too many updates for the site's hardware situation.

**Comment by trlkly** [comment]
Another option then would be to save the information client-side in the newer storage technologies. (I think even localStorage would work, but yo umight want something newer). You'd only need to store URLs of the topics and the date each was accessed, and could add a storage limit and/or time limit to avoid it becoming too unwieldy. Then use JavaScript client-side to access that information and format the post links appropriately. 

I would be quite surprised if at least one currently used forum solution doesn't already do it this way.
