### ISSUE TITLE
Publishing: Error when actually publishing and no Discord/IRC notify.

### ISSUE THREAD

**Issue by fsvgm777** [TASVideos/tasvideos#807]
When publishing a movie, an error may occur. However, the movie does get published as it should, but without any Discord or IRC notification, which may be related.

@EZGames69 can provide more details on what the actual error is, as I don't remember exactly what the error was.

**Comment by fsvgm777** [comment]
What I do remember is that Colin landed on an Access Denied page.

**Comment by EZGames69** [comment]
that is correct, as soon as I hit publish, it gave me an Access Denied error, but the movie published just fine.

My theory of what happened is the site didn't know where to redirect me after hitting publish, normally it would load the movie page that I just published on the old site, so perhaps that's where the fault is.  But that's just a guess.

**Comment by adelikat** [comment]
We fixed this today
