### ISSUE TITLE
Some URLs in text lost their colon and became http// or https//

### ISSUE THREAD

**Issue by SandTAS** [TASVideos/tasvideos#809]
Here's a post in the old forum:

https://web.archive.org/web/20170903052220/http://tasvideos.org/forum/viewtopic.php?t=7860#275096
> 2 test speedruns
> http://www.youtube.com/watch?v=5PzxP2y-bBA
> http://www.youtube.com/watch?v=FtcSKgeTePI

In the new forum, the URLs have lost their colon character and are no longer made into links:

https://tasvideos.org/Forum/Posts/275096#275096 ([archived snapshot](https://web.archive.org/web/20220104212410/https://tasvideos.org/Forum/Topics/7860?CurrentPage=1&Highlight=275096#275096))
> 2 test speedruns
> http//www.youtube.com/watch?v=5PzxP2y-bBA
> http//www.youtube.com/watch?v=FtcSKgeTePI

You can find more instances of this occurrence by a search for ["http"](https://tasvideos.org/Search?searchterms=http%3A) or ["https"](https://tasvideos.org/Search?searchterms=https%3A). For example:

* [Batman](https://tasvideos.org/Forum/Posts/31958#31958)
* [Super Mario Bros. 3](https://tasvideos.org/Forum/Posts/318292#318292) (however see the [very next post](https://tasvideos.org/Forum/Posts/323147#323147) which has a working URL)
* [Tetris, again](https://tasvideos.org/Forum/Posts/138459#138459)
* [Metal Slug 6](https://tasvideos.org/Forum/Posts/493771#493771)
* A strange example: [279952](https://tasvideos.org/Forum/Posts/279952#279952) has broken URLs (missing the colon), but when it is quoted in [279962](https://tasvideos.org/Forum/Posts/279962#279962) the URLs are complete and working

**Comment by nattthebear** [comment]
Well, that's strange.  This feels like a phpbb baked vs unbaked problem, in which case it's a bit late to fix it by any means other than hacks.

@SandTAS Have you been able to reproduce this at all with new posts, after the migration?

**Comment by SandTAS** [comment]
I have not seen it on new posts, only old posts.

**Comment by adelikat** [comment]
Ran through the affected posts and fixed them
