### ISSUE TITLE
Publishing: Allow multiple streaming links to be added at once for alternative encodes (ex: camhack)

### ISSUE THREAD

**Issue by EZGames69** [TASVideos/tasvideos#811]
We occasionally will post additional encodes of movies if we want to show other features that make viewing better.  The most well known example being the Camhack encodes: https://www.youtube.com/watch?v=SqZe40afgx8

There hasn't been a method to adding these encodes at once, as they usually get added in later.  On the new site, it only allows for one YouTube encode and one Archive link at a time.  If there was a way to click a button to "add" another link entry, that would be helpful.

**Comment by vadosnaprimer** [comment]
Another popular example is Cutsceneless.

**Comment by TiKevin83** [comment]
Related to #779 as well with the utility to link to verifications

**Comment by adelikat** [comment]
This was built awhile ago
