### ISSUE TITLE
Hidden userfiles display a blank page

### ISSUE THREAD

**Issue by bigbass1997** [TASVideos/tasvideos#821]
When attempting to view a userfile that's marked as hidden, only a completely blank page is shown.

Example: https://tasvideos.org/Userfiles/Info/72592885614782763 (which is linked to from https://tasvideos.org/4490M "you can download the original m64 file \<here\>.")
Also tested by having TiKevin mark one of his userfiles as hidden, and the same result happened for me (but not for him).

The old site would allow people with the link to view/download the file, and comment on it: https://web.archive.org/web/20211023091529/https://tasvideos.org/userfiles/info/72592885614782763

**Comment by meshuggahtas** [comment]
I get 404 currently for that UserFiles link
