### ISSUE TITLE
SystemPage SearchInstructions needs update and inclusion

### ISSUE THREAD

**Issue by meshuggahtas** [TASVideos/tasvideos#834]
- Search is now postrgres based,
- the period character and asterisk character doesn't works.
- More examples could be shown, as the currently linked (at Search page) https://www.postgresql.org/docs/current/textsearch-controls.html#TEXTSEARCH-PARSING-QUERIES is not simple to grasp for an average visitor
- SearchInstructions on legacy site:
![legacys](https://user-images.githubusercontent.com/31288337/148436788-4cffd10b-b45f-4557-b680-85c265a5abfb.PNG)

**Comment by adelikat** [comment]
We have System/SearchTerms as the system page now (in hindsight, it would have been better to reuse the previous).  I added some info from this page, and put a todo on TODO, closing this because it is not a dev ticket, but a staff wiki edit problem

**Comment by meshuggahtas** [comment]
Since I'm just a contributor and I don't know how these wiki stuffs gets talked about, I leave me notes here:
- **megaman** and **Megaman** won't give the exact same results. It will be definitely in different orders, and I think they don't result in the same amount of hits

Example:
https://tasvideos.org/Search?SearchTerms=megaman - Wiki and post results
https://tasvideos.org/Search?SearchTerms=Megaman - Wiki and post results in different order

- There is definitely a bug in what strings get's evaulated as matching. Sometimes it matches a game's name, sometimes it matches a part of a game's name and sometimes it won't show it.

Example:
https://tasvideos.org/Search?SearchTerms=banned shows GBC - Pokémon: Platinum Edition because the name is Kou Dai Yao Guai - Bai Jin **Ban** (ned)
https://tasvideos.org/Search?SearchTerms=jin+ba shows nothing, 0 results
https://tasvideos.org/Search?SearchTerms=jin+ban shows many results
