### ISSUE TITLE
Put a regular topic link into the topic reply notification email

### ISSUE THREAD

**Issue by Masterjun3** [TASVideos/tasvideos#836]
When receiving a topic reply notification for a topic you're watching, all you get is the post link and an unwatch link.
Sometimes the post is deleted, so the link becomes useless. This wouldn't be the case if a delete post link would automatically link to the topic, but this feature doesn't exist.
It would be very useful to have a regular topic link inside the email as a fallback.

**Comment by TiKevin83** [comment]
IMO instead of linking twice a link to a deleted post should route to the thread and a deleted thread to the subforum etc.

**Comment by meshuggahtas** [comment]
Current scenarios:
- Post got deleted: link will redirect to https://tasvideos.org/Forum/NotFound
- Thread got deleted: link will redirect to https://tasvideos.org/Forum/NotFound

I vote for Masterjun's "link to thread as well" in the email notification. I'm unsure about the redirect idea.

**Comment by Masterjun3** [comment]
One thing that can't be solved with the deleted post redirect is moved posts.
So this should be added independently of what to do with deleted posts.

**Comment by Masterjun3** [comment]
I have a suggested rework of the email text.
```
Hello,

The TASVideos forum topic "Site Bug Reports and Feature Requests" has received a new post since your last visit.

https://tasvideos.org/Forum/Posts/511483

No more notification emails for this topic will be sent until you visit it.
If the post was moved or deleted you can find the topic at the following link:
https://tasvideos.org/Forum/Topics/23000


To stop this particular topic from notifying you, click the following link:
https://tasvideos.org/Forum/Topics/23000?handler=Unwatch

To stop all topic notification emails, follow this link and click "Stop Watching All":
https://tasvideos.org/Profile/WatchedTopics
```
To compare, you can see the current version here:
https://github.com/TASVideos/tasvideos/blob/f6d934624d42fb56fa245d030635cf56e70cba7a/TASVideos.Core/Services/Email/EmailService.cs#L76-L88

**Comment by TiKevin83** [comment]
```
Hello,

A new post(html link if possible) has been sent to the TASVideos forum topic "Site Bug Reports and Feature Requests(link if possible)" since your last visit.

https://tasvideos.org/Forum/Posts/511483 (drop this and the bit about the thread link if you can inline the links)

Notification emails will not be sent for subsequent posts until your next visit to the topic.

--
To stop this particular topic from notifying you, visit the following link:
https://tasvideos.org/Forum/Topics/23000?handler=Unwatch

To stop all topic notification emails, follow this link and press "Stop Watching All":
https://tasvideos.org/Profile/WatchedTopics

--
Thanks,
TASVideos staff
```

**Comment by meshuggahtas** [comment]
Personally I like that I can do much more straight away from the email and also feel overwhelmed by the number of links which is 4 currently. Would it have more appeal and structure if the links and descriptions would be separated in new lines? Of course only if this would be an issue for others than me.

Something along the lines (bolded: variable text):

Hello,
```
A new post has been sent to the TASVideos forum topic **Site Bug Reports and Feature Requests** since your last visit.

<a href="https://tasvideos.org/Forum/Posts/511483">Post</a>
<a href="https://tasvideos.org/Forum/Topics/23000">Forum Thread - Site Bug Reports and Feature Requests</a>
<a href="https://tasvideos.org/Forum/Topics/23000?handler=Unwatch">Stop this topic from notifying you</a>

Notification emails will not be sent for subsequent posts until your next visit to the topic.

To stop all topic notification emails, follow <a href="https://tasvideos.org/Profile/WatchedTopics">this link</a> and press "Stop Watching All".

--
Thanks,
TASVideos staff
```

**Comment by TiKevin83** [comment]
I'd be fine with that too

**Comment by meshuggahtas** [comment]
I guess the last lines about "Notification emails will not be sent" and "To stop all " could be appended. Don't know, don't want to "optimize" it over the cost of potential readability issues for international speakers of entirely different alphabet users or other accessibility reasons. But I guess that's all I wanted to add on my part.

**Comment by Masterjun3** [comment]
I have several issues with your suggestions.
- Using HTML is fine, I just didn't want to change the visual style too much. I also didn't know if HTML would be a problem, but apparently it's fine so that can be used.
- Having the most important link to the post just be "post" is poor design. It's too small of a word. The full link is better.
- Saying "Notification emails will not be sent for subsequent posts until your next visit to the topic." is wrong. You will still receive emails, just not for that particular topic. My version removes this ambiguity.
- I intentionally put the topic title at the very beginning. Because you're getting a lot of emails with the same structure, this is necessary to differentiate and know exactly which topic it is.
- For meshuggah's suggestion, the links are too close together and the link is too small. Bad design. You want the most important and most used link to be the most prominent one.

**Comment by TiKevin83** [comment]
Edited my suggestion per above. I would argue that making the focus of the first sentence the post link is more important to prominence than how large the link text is. The differentiation of emails by thread topic is already solved by the topic being in the email's subject line.

**Comment by Masterjun3** [comment]
> IMO instead of linking twice a link to a deleted post should route to the thread and a deleted thread to the subforum etc.

Please make this a separate issue. It's irrelevant here.

**Comment by adelikat** [comment]
You can't redirect to the thread, because once a post is deleted, it is gone, we don't know what what topic it was for.  A major reworking of the database, or routing (and worrying about backwards compatibility), for this to be possible.

Also, I liked Masterjun's suggested email.
