### ISSUE TITLE
List of pages where pagination is required

### ISSUE THREAD

**Issue by meshuggahtas** [TASVideos/tasvideos#837]
- https://tasvideos.org/MoviePublishingHistory
- https://tasvideos.org/FullRecentChanges
- https://tasvideos.org/WikiOrphans
____
- https://tasvideos.org/MovieMaintenanceLog - There is only a Next button, nothing else. 
- https://tasvideos.org/Subs-List
- https://tasvideos.org/RejectedSubmissions
____
- https://tasvideos.org/Userfiles
- https://tasvideos.org/Profile/UserFiles
- https://tasvideos.org/Profile/Ratings
- https://tasvideos.org/Profile/Unrated
- https://tasvideos.org/Profile/WatchedTopics
____
- https://tasvideos.org/Publications/Filter 
- https://tasvideos.org/Games - This is a tricky one as it's currently in tabbed form
____
Relevant open issue: https://github.com/TASVideos/tasvideos/issues/15
Note: Some pages might have additional language 
____
- https://tasvideos.org/ConsoleVerifiedMovies
- https://tasvideos.org/Players-List
- https://tasvideos.org/GameS/List - Unsure about this one
____
- https://tasvideos.org/Messages/Savebox
- https://tasvideos.org/Messages/Sentbox
- https://tasvideos.org/Messages/Inbox
____
- https://tasvideos.org/Wiki/EditHistory/TASVideoAgent
- https://tasvideos.org/Activity/Judges/adelikat
- https://tasvideos.org/Activity/Publishers/adelikat

**Comment by TiKevin83** [comment]
duplicate of #15

**Comment by meshuggahtas** [comment]
Ok, closing issue and copying the list to #15

**Comment by YoshiRulz** [comment]
These pages were deemed out of scope of the other issue.

---

For `/Publications/Filter` I assume you meant the individual `<select/>`s? Game and author definitely need a search (you can click and type a prefix currently), maybe tags and platform too.
