### ISSUE TITLE
[Request] Ability to reposition subforums

### ISSUE THREAD

**Issue by SamsaraTAS** [TASVideos/tasvideos#838]
EDIT: Changing the title and body to better reflect what we want out of this.

Currently, the [Site subforum](https://tasvideos.org/Forum/Subforum/3) contains a large amount of important threads for community engagement, notably including the feedback thread for the new site itself. This subforum is sitting at the very bottom of the main forum page, and I believe it's not drawing as much attention as it should due to that. Due to this, I feel implementing a feature to move subforums around would be highly beneficial.

**Comment by vadosnaprimer** [comment]
Agreed! Site is where most of the stuff is going on right now, and it's not gonna slow down.

**Comment by adelikat** [comment]
I see the point of this ticket as the building of a UI that will allow this, not just the one off task of changing the database

**Comment by adelikat** [comment]
Thea ability to move forums around was built awhile ago, forgot to close this ticket
