### ISSUE TITLE
module:frames isn't working

### ISSUE THREAD

**Issue by ThunderAxe31** [TASVideos/tasvideos#840]
https://tasvideos.org/4413M

> This movie is a 0.00 minute improvement over the previous record.

**Comment by Masterjun3** [comment]
It works for locales that use dot separation for numbers.
The source code says `[module:frames|amount=30717|fps=59.727500569606]` and the site decides you live in Europe, with comma separators, so that means 30717 frames at 59727500569606 FPS.
Which is very 0.

![image](https://user-images.githubusercontent.com/22375320/148495052-d4c31707-1b82-467e-b180-84a126b2ce3e.png)

**Comment by vadosnaprimer** [comment]
I'm using a comma locale and it shows things properly.

![изображение](https://user-images.githubusercontent.com/7092625/148522647-2a43b469-1d58-4636-b66e-3728519a53ee.png)

**Comment by meshuggahtas** [comment]
- https://tasvideos.org/SandBox
- English + [module:frames|amount=30717|fps=59.727500569606] = 8:31.95
- English + [module:frames|amount=30717|fps=59,727500569606] = 8:34.28
- Hungarian +[module:frames|amount=30717|fps=59.727500569606] = 8:34.28
- Hungarian + [module:frames|amount=30717|fps=59,727500569606] = 0

Something is not OK

**Comment by ThunderAxe31** [comment]
Device: Samsung Galaxy S5 Mini
Browser: Chrome 96.0.4664.104
OS: Android 6.1: SM-G800F Build/MMB29K
Language: Italian

**Comment by Masterjun3** [comment]
> I'm using a comma locale and it shows things properly.

Yeah sorry, I used wrong wording. It's not about locales using decimal separators with comma vs. dot.
It's about locales using digit-grouping separators with dots vs. non-dots.

**Comment by ThunderAxe31** [comment]
Ugh, it's the other way around for me
![Screenshot_2022-01-07-17-22-52](https://user-images.githubusercontent.com/36802254/148574065-91c1c9d7-c246-4e57-968a-5376fd8490db.png)

**Comment by meshuggahtas** [comment]
@ThunderAxe31 what is the top language selected in your chrome settings >Language?

**Comment by ThunderAxe31** [comment]
Italian, as automatically matching the OS setting, but it can be changed.

Now I tried setting it to English (United States) and the outcome didn't change, despite Chrome interface becoming all English.

**Comment by ThunderAxe31** [comment]
oh wait, now that I refreshed, the outcome changed. However...
![Screenshot_2022-01-07-17-35-25](https://user-images.githubusercontent.com/36802254/148575815-19829d52-91cb-4c3e-8815-8c9bd4020108.png)

**Comment by meshuggahtas** [comment]
It should change after you leave settings and refresh the page.

**Comment by meshuggahtas** [comment]
From Discord: that's what I didn't understand previously when the first locale bug appeared. Is the goal is to 
- let users write comma or dot depending their own locale
or
- only for transforming locale variable data when displaying?

I think the potential situations where someone needs or wants to use their own locale while visiting the website boils down to these:
- time length
- modules with decimal operator parameter
