### ISSUE TITLE
Give an actual description for the Awards subforum

### ISSUE THREAD

**Issue by ThunderAxe31** [TASVideos/tasvideos#846]
Current:
![image](https://user-images.githubusercontent.com/36802254/148535827-82376841-4215-4139-92f9-a6c56994cef1.png)

Suggestion:
anything more descriptive than that

**Comment by meshuggahtas** [comment]
List of subforums without description:
https://tasvideos.org/Forum/Subforum/23 N64
https://tasvideos.org/Forum/Subforum/40 GC WII
https://tasvideos.org/Forum/Subforum/20 GBA
https://tasvideos.org/Forum/Subforum/41 DS
https://tasvideos.org/Forum/Subforum/44 Saturn
https://tasvideos.org/Forum/Subforum/29 PSX
https://tasvideos.org/Forum/Subforum/63 PS2
https://tasvideos.org/Forum/Subforum/30 Arcade
https://tasvideos.org/Forum/Subforum/16 Published Movies

**Comment by adelikat** [comment]
Descriptions are added via a UI by anyone with the appropriate privilege, please bring this up on the forums, this is not a technical ticket
