### ISSUE TITLE
Individual users' player point ranks not listed anywhere

### ISSUE THREAD

**Issue by MemoryTAS** [TASVideos/tasvideos#849]
From a discussion I had, they weren't intended to be completely removed or anything so they need to be listed _somewhere_. Profile could work if there's not enough space in forum posts.

**Comment by meshuggahtas** [comment]
- Player points are currently @ https://tasvideos.org/Profile or https://tasvideos.org/Users/Profile/Memory right side Publications
- Forum ranks are currently at same page but left side Roles
- In the post you see both data https://tasvideos.org/Forum/Topics/23001?CurrentPage=1&Highlight=511476#511476

Could it be the values were not filled at the time of reporting the issue?

**Comment by MemoryTAS** [comment]
> * Player points are currently @ https://tasvideos.org/Profile or https://tasvideos.org/Users/Profile/Memory right side Publications
> 
>     * Forum ranks are currently at same page but left side Roles
> 
>     * In the post you see both data https://tasvideos.org/Forum/Topics/23001?CurrentPage=1&Highlight=511476#511476
> 
> 
> Could it be the values were not filled at the time of reporting the issue?

Not what I'm referring to, in the old site I would have "Skilled Player" in my list of roles. Information is at https://tasvideos.org/PlayerPointsAndRanks

**Comment by adelikat** [comment]
It's intended that it isn't on forums anymore.  I believe the decision was due to space considerations.  But it should at least be displayed on the profile page

**Comment by meshuggahtas** [comment]
I think we have enough space after the many redesigns. The longest player point rank text is Experienced player (999), 24 characters

**Comment by adelikat** [comment]
After some discussion this was not intentional that it isn't listed on forum posts, and we need to add it there
