### ISSUE TITLE
On the Filter page, only selecting Show Obsoleted or Only Obsoleted leads to an error page

### ISSUE THREAD

**Issue by ActuallyTruncated** [TASVideos/tasvideos#860]
Steps to reproduce:

- Go to the filter page: https://tasvideos.org/Publications/Filter
- Check the box for Show Obsoleted or Only Obsoleted. (Actually, selecting both also works.)
- Click Filter.

You will be sent to this error page: https://tasvideos.org/Wiki/PageDoesNotExist?url=Movies-

The URL parameter is "Movies-", and not "Movies-Obs" or "Movies-ObsOnly" as would be expected.
Additionally, manually going to "Movies-Obs" or "Movies-ObsOnly" forwards you to "Movies".

**Comment by adelikat** [comment]
Yeah, I don't want to support being able to show ALL the movies that way

**Comment by adelikat** [comment]
What would be fancy is for the submit button to be disabled until something other than those 2 checkboxes is picked

**Comment by ActuallyTruncated** [comment]
> Yeah, I don't want to support being able to show ALL the movies that way

I can understand that, and it is not what I tried to accomplish. I was on a player page, and from there wanted to filter out to only see obsoleted movies. But when clicking Filter from a player page, the player restriction is lost. However, this is already reported as issues #662 and #627 .
