### ISSUE TITLE
no way to make a relative link that includes a query string parameter

### ISSUE THREAD

**Issue by MemoryTAS** [TASVideos/tasvideos#865]
For example "[=ref.exe?page=TODO|refer]" on https://tasvideos.org/TODO doesn't work anymore and there's no equivalent way to do it without linking the full url.

**Comment by nattthebear** [comment]
On that page, the wiki markup is:
```text
[=ref.exe?page=TODO|refer]
```
and the exact corresponding HTML output is
```
<a href="/Ref.exe?page=TODO" class="intlink">refer</a>
```

Everything seems to be correct there?  The link isn't working, but I think that's because Ref.exe isn't a thing anymore?

**Comment by MemoryTAS** [comment]
Yes, ref.exe isn't a thing anymorre but I don't see a way to link to https://tasvideos.org/Wiki/Referrers?path=TODO besides listing the full url

**Comment by nattthebear** [comment]
What about
```[=Wiki/Referrers?path=TODO|refer]```

**Comment by MemoryTAS** [comment]
that works, I thought I tried that, thanks
