### ISSUE TITLE
Password generators page does not work

### ISSUE THREAD

**Issue by InfoManiac742** [TASVideos/tasvideos#878]
The password generators page (https://tasvideos.org/Passwordgenerators) is completely broken on the new website. I've attached a screenshot below. Tested on Windows 10, both Firefox and Chrome.
![image](https://user-images.githubusercontent.com/26778801/148662413-8c1bc61f-0dca-4b58-918b-5a18858b7a78.png)

**Comment by SamsaraTAS** [comment]
The modules likely aren't going to be rewritten for the new site. The page has been deleted.

**Comment by adelikat** [comment]
Sorry you wasted your time browser testing, it was just functionality that was never re-implemented.  I liked the password generators but they weren't worth re-engineering in a new programming language or the burden of maintaining.

Also shoutouts to a light mode user
