### ISSUE TITLE
UseFile game list clears when selecting a system

### ISSUE THREAD

**Issue by adelikat** [TASVideos/tasvideos#884]
Reported at https://tasvideos.org/Forum/Posts/511526#511526

"There's a bug with user files that I found. Selecting a system for a user file is supposed to narrow down the game list but it brings up an empty list instead. At least I can still select the game as long as I do not select a system for said user file."

Probably a regression in the javascript from some refactors

**Comment by meshuggahtas** [comment]
The culprit is probably here @ https://github.com/TASVideos/tasvideos/blob/8776b44e8e74b61b7fceb8e6c582968f09d09f1c/TASVideos/Pages/UserFiles/Upload.cshtml#L62

**Comment by Masterjun3** [comment]
The issue is that the request goes to Games/List which requires CatalogMovies permissions to access.

**Comment by meshuggahtas** [comment]
Reopening issue since it's not working as of v2.2.233 commit https://github.com/TASVideos/tasvideos/commit/deb666dcb8a0676db0208ada88a0609d0a1d4a3f
(This issue closed 8 hours ago, so I assume this commit is already live)

**Comment by adelikat** [comment]
Please don't assume a commit is already live.  The footer links to the current revision that is live
