### ISSUE TITLE
JRSR parser does not support tab as a delimiter

### ISSUE THREAD

**Issue by SandTAS** [TASVideos/tasvideos#889]
If you upload [ilari-ddave.jrsr](https://tasvideos.org/1718M?handler=Download) from [1718M](https://tasvideos.org/1718M) (to UserFiles, for example), it shows up as having no frames:

> For DOS
> In 00:00.00 (0 frames), 2757 rerecords

This is because the file uses tab, not space, as a delimiter, and [the code expects space](https://github.com/TASVideos/tasvideos/blob/fb00367c4a6dc00297bccdbfeb993597bf080248/TASVideos.Parsers/Parsers/Jrsr.cs#L117).

```
!BEGIN events
+480395196	org.jpc.emulator.peripheral.Keyboard	KEYEDGE 28
+481061856	org.jpc.emulator.peripheral.Keyboard	KEYEDGE 28
+481728516	org.jpc.emulator.peripheral.Keyboard	KEYEDGE 63
```

The [documentation](https://tasvideos.org/EmulatorResources/JPC/JRSRFormat#Spaces) gives a few other delimiters:

> Following Unicode codepoints act as spaces:
> * Codepoints 0x20 (SPACE) and 0x09 (TAB)
> * Codepoints 0x1680, 0x180E, 0x2028, 0x205F and 0x3000
> * Codepoints 0x2000-0x200A.

Here is a test case with all the possibilities for spaces: [spaces.jrsr.gz](https://github.com/TASVideos/tasvideos/files/7834523/spaces.jrsr.gz). The expected total time is 18 ns.

**Comment by adelikat** [comment]
This is the worst movie format.

**Comment by SandTAS** [comment]
I wrote a JRSR parser for the [Arduino USB keyboard verification project](https://tasvideos.org/Forum/Topics/22864). I'll try porting it to C#.
