### ISSUE TITLE
JRSR parser does not understand absolute timestamps

### ISSUE THREAD

**Issue by SandTAS** [TASVideos/tasvideos#890]
Timestamps in JRSR files may be absolute or relative; most files' [events section](https://tasvideos.org/EmulatorResources/JPC/JRSRFormat#EventsSection) begins with a `+0 OPTION RELATIVE` to make the following timestamps relative; but by default they are absolute.

> Timestamps must be nonnegative integers. By default they are relative to initial poweron. When computing movie length, it is customary to ignore all special events.
>
> * Class "OPTION":
>   * "RELATIVE": Further timestamps will be relative to last timestamp.
>   * "ABSOLUTE": Further timestamps will be relative to initial poweron (warning: buggy in versions R10.7 and before). 

I know of only one file that uses absolute timestamps, [ilari-ddave.jrsr](https://tasvideos.org/1718M?handler=Download) from [1718M](https://tasvideos.org/1718M). This file does not currently parse correctly because of #889, but if you work around that (by converting the tabs in the file to spaces) and upload the file, you get an absurdly long video length, because all the absolute timestamps [are summed](https://github.com/TASVideos/tasvideos/blob/fb00367c4a6dc00297bccdbfeb993597bf080248/TASVideos.Parsers/Parsers/Jrsr.cs#L81).

> For DOS
> In 1:02:54:41.00 (5812846 frames), 2757 rerecords

```
!BEGIN events
+480395196	org.jpc.emulator.peripheral.Keyboard	KEYEDGE 28
+481061856	org.jpc.emulator.peripheral.Keyboard	KEYEDGE 28
+481728516	org.jpc.emulator.peripheral.Keyboard	KEYEDGE 63
...
+392797738650	org.jpc.emulator.peripheral.Keyboard	KEYEDGE 203
```

The actual expected duration is the final timestamp, 392797738650 ns.

The code should keep track of the most recent OPTION setting seen (initialized to ABSOLUTE), and do something like
```
if (OPTION == ABSOLUTE)
    totalNanoSeconds = getTime(line);
else
    totalNanoSections += getTime(line);
```

**Comment by adelikat** [comment]
This is the worst movie format.
