### ISSUE TITLE
Add default check option for minor edit of forum posts

### ISSUE THREAD

**Issue by ThunderAxe31** [TASVideos/tasvideos#891]
In the old site, there was this profile setting for the forum, which would make minor edit for post checked by default. I want that back, because I tend to do a lot of minor edits to my posts, and I often forget to enable the minor edit check.

**Comment by adelikat** [comment]
I'd like to keep options to a minimum to avoid feature bloat.  What if edits to posts were just minor by default? @MemoryTAS  @vadosnaprimer

**Comment by vadosnaprimer** [comment]
I don't mind defaulting post edits to minor. I think it's more frequent that you edit the post many times and only after some important change you want to explicitly announce the edit.

**Comment by adelikat** [comment]
Yeah, that's what I'm thinking too.  I think historically, a vast majority of my post edits have been minor

**Comment by adelikat** [comment]
I decided to default minor edit to true for editing one's own post, but keeping false for editor another's post.  The idea being that for a moderator, it would be expected that the post would something you want to announce
