### ISSUE TITLE
User Files are sorted randomly which makes it painful to find anything

### ISSUE THREAD

**Issue by ThunderAxe31** [TASVideos/tasvideos#893]
See here for example: https://tasvideos.org/UserFiles/ForUser/ThunderAxe31
The files aren't sorted by upload date, as it was before. Note that upload date simply depends on the file ID in the url, so the bigger the number is, the more recent is, which is very straight-forward in itself. So please, just make the files ordered in descending date as it used to be on old site, starting from the most recent movie up to the most old one.

**Comment by vadosnaprimer** [comment]
They seem to be sorted by descending date on every page, but the way they are spread _across pages_ seems completely random. It should sort first, then split into pages.

**Comment by meshuggahtas** [comment]
Note there is 2 type of "sort" being used, depending on where do you see the list.

https://tasvideos.org/Profile/UserFiles - Date based
https://tasvideos.org/UserFiles/ForUser/MESHUGGAH - have no idea. ID based?
