### ISSUE TITLE
Add “compare to” in the edit logs

### ISSUE THREAD

**Issue by EZGames69** [TASVideos/tasvideos#897]
Old site had the ability to compare the changes to a previous version of a pub description/page/etc.

**Comment by Masterjun3** [comment]
The "Page History" button at the bottom of a publication does that.

**Comment by vadosnaprimer** [comment]
![изображение](https://user-images.githubusercontent.com/7092625/148700577-e2e1db16-d630-4613-805a-a6d359f0b38d.png)

**Comment by meshuggahtas** [comment]
![ok](https://user-images.githubusercontent.com/31288337/148700601-0e8b1b44-3d2f-4726-8a1a-45cfe51053c8.PNG)   ?

**Comment by EZGames69** [comment]
Oh my bad, I was looking in the “logs” portion, not the “page history” part.  I probably missed it because you have to scroll a bit on mobile to find it.
![6F8954C4-B70F-4641-9441-BFE4811C2874](https://user-images.githubusercontent.com/44628443/148701228-f04ea77a-9320-4fd2-8b1c-65afa7d2c3a3.jpeg)
