### ISSUE TITLE
all movies are gone :(

### ISSUE THREAD

**Issue by Zinfidel** [TASVideos/tasvideos#900]
The site seems to think that there aren't any movies.

Repro steps:
Homepage > Movies > Publications > click anything with any filter > 0 results

![image](https://user-images.githubusercontent.com/1929934/148706463-2aa93619-d9d1-47b8-b3e6-af352fe8f425.png)

Seem p bad

![image](https://user-images.githubusercontent.com/1929934/148706428-6fcea600-e220-4c8a-adf1-5e6ad1e924be.png)

**Comment by Masterjun3** [comment]
New "limit" specifier defaults to 0. 14755f8fdbcf0dba5293d098ee9427061c324c3b
0 Movies: https://tasvideos.org/Movies-stars-nes
3 Movies: https://tasvideos.org/Movies-stars-nes-limit3
