### ISSUE TITLE
Suggestion: Forum Markup: ignore one newline if it comes after a `[/quote]` quote end tag

### ISSUE THREAD

**Issue by Masterjun3** [TASVideos/tasvideos#902]
Not sure how possible this suggestion is, but this is a gripe I've had with the old site as well, but the new site has elevated it even further.

Currently, a post like this

```
[quote]Hello this is the quote[/quote]
And this is immediate text under it.

And this is far off text.
```
shows up like this
![image](https://user-images.githubusercontent.com/22375320/148711299-5de04435-f303-4be9-981c-a1c78dfbecea.png)

The amount of whitespace between the quote and the following text is so big not only because the quote block has a margin, but because the quote-end already implies a newline by design, as it is a separate block. And then the newline after the `[/quote]` is parsed and another newline is added.

If one newline would be ignored, it would result in a nicer post, closer representing the source.
![image](https://user-images.githubusercontent.com/22375320/148711438-b2aad528-3a21-472b-b5aa-3c06092a3ec6.png)

**Comment by nattthebear** [comment]
> but the new site has elevated it even further.

Why is that?  Different styling?

**Comment by Masterjun3** [comment]
The empty space between the quote and text is even further apart now than the old site, so it's looking like the quote and the text are unrelated.

**Comment by Masterjun3** [comment]
See for example this post https://tasvideos.org/Forum/Posts/509803#509803 (or other posts in that thread).
The source code of the post has properly separated quote+quotereply, like in my example post above. But the forum makes it appear perfectly in the middle of the previous and the next quote.

The idea of ignoring a newline can be extended to every markup block with an implied newline, as that creates a disconnect between source code and render.

**Comment by vadosnaprimer** [comment]
The same is true for code samples and especially lists

![изображение](https://user-images.githubusercontent.com/7092625/148737134-e9e49337-14e0-461a-9d5d-7298635fc7e3.png)

**Comment by nattthebear** [comment]
I can make changes to the parser, but this feels more like a styling problem.  I checked on the old site and the behavior is very similar.  The old site inserts `<br/>` where the new site uses `white-space: pre-wrap`, but the result is the same.  Given that we have this consistent behavior between the old and new parsers, why did we choose to style things in way that doesn't work well with it?
