### ISSUE TITLE
Game page bugs

### ISSUE THREAD

**Issue by coolkirby2000** [TASVideos/tasvideos#903]
1. "Screenshot Url" does not seem to do anything. Screenshots were added for [SMB](https://tasvideos.org/1G) and [Bio Hazard](https://tasvideos.org/2300G) but do not appear on the Game page on mobile or desktop.
2. In the Game Versions/Roms section, setting the type to anything except Unknown changes to Unknown anyway when you click Update (to save the page).
3. Back on the main Game page, the Roms section has multiple Roms stacking horizontally. Notice the "Pocket Monsters" column on the right. This is especially hard to read on mobile. Is this intended or a bug?
![image](https://i.imgur.com/TgCvY1s.png)

**Comment by Masterjun3** [comment]
Yeah I have a WIP branch addressing issues 1. and 3.
I can also look at 2.

**Comment by adelikat** [comment]
Fixed #2
