### ISSUE TITLE
Include game version into publication name

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#906]
Sometimes we publish different region versions separately
https://tasvideos.org/Movies-2413M-2648M
so it's important to show those versions as a part of movie name, like it was on the old site:

PSX Tenchu: Stealth Assassins (USA) by Hâthor in 29:52.65
PSX Tenchu: Stealth Assassins (JPN) by xxNKxx in 16:34.17

It also makes sense to include version into youtube name.

**Comment by Masterjun3** [comment]
I wonder if it would be worth it to create a flag for each publication telling whether it's necessary to show the game version.
Showing it seems to be unnecessary for the majority of movies, yet absolutely necessary for some.

**Comment by vadosnaprimer** [comment]
Ah that sounds like we should have an optional field in pubs where this version would be displayed, and rom version/revision would be a separate thing. The former is decorative, the latter is for internal bookkeeping.

**Comment by meshuggahtas** [comment]
Unknown means unknown country. It has information value when there are other game versions with known country.

I don't know about Any as game version for Goodsets.

**Comment by vadosnaprimer** [comment]
I mean the old site had unknown as default, and for games without versions it just printed unknown in the pub name, which is useless.

**Comment by vadosnaprimer** [comment]
I created ROM entries but versions are still not displayed in pub name.
https://tasvideos.org/Movies-2413M-2648M

**Comment by ViGadeomes** [comment]
I agree with this issue and I would like to propose to also add the version in the submission system list because when two movies of the same game with different regional versions can be published side by side and submited at the same time, It can be a little bit confusing.

**Comment by vadosnaprimer** [comment]
There's a submission whose acceptance is kinda blocked by not having this info displayed
https://tasvideos.org/Forum/Posts/511550

**Comment by adelikat** [comment]
Fixed enough for now, could be improved
