### ISSUE TITLE
Customizable locale settings

### ISSUE THREAD

**Issue by Masterjun3** [TASVideos/tasvideos#908]
There has been frequent feedback of people wanting their date format to be different. This currently relies on the locale setting sent by the browser.
However, requiring people to change their entire web browsing experience to show better dates on tasvideos.org is **not** a good solution.
We need a way to set certain locale related settings. And ideally not as a profile setting but a site setting like dark mode.

Side note: As a (poor) workaround, I currently use a manually created `.AspNetCore.Culture` cookie, with a value of `c=kw-gb|uic=kw-gb`, which is a locale using yyyy-MM-dd, a 24 hour clock, and dot separators for decimals.

(Edit: I added some implementation details in the [comment below](https://github.com/TASVideos/tasvideos/issues/908#issuecomment-1969392775))

**Comment by Spikestuff** [comment]
It's important in a DM setting as well since none of these are in my timezone:
![image](https://user-images.githubusercontent.com/12412764/155432057-ff2e0a09-5092-49df-975f-5ec35e9bbbe1.png)

**Comment by Masterjun3** [comment]
To implement this, for every request the code would need to override the `CultureInfo.CurrentCulture` object with the custom format the user has specified. This would need to be done as soon as possible, maybe as a Middleware (I think we already use a library middleware for selecting the current culture of the browser).

The problem is how to actually make a new culture with these settings. I think custom cultures can be built manually, but I think they have to be actually installed into the server operating system to be used. More research has to be done here.
