### ISSUE TITLE
Hidden UserFiles enhancement

### ISSUE THREAD

**Issue by meshuggahtas** [TASVideos/tasvideos#911]
https://tasvideos.org/Profile **302**
https://tasvideos.org/Profile/UserFiles 291
https://tasvideos.org/Users/Profile/MESHUGGAH 291
https://tasvideos.org/UserFiles/ForUser/MESHUGGAH 291
Old site 291

Screenshot of Profile
![account](https://user-images.githubusercontent.com/31288337/148972704-928547ae-e178-4436-92b4-20f10a50fa55.PNG)

**Comment by adelikat** [comment]
Isn't this by design? 291 is the number of public movies you have, and on any page where it is a public view, it shows this.

On your profile which your personal view, it shows 302

**Comment by meshuggahtas** [comment]
I can't verify it because of the high quantity. But I'm assuming that if I'm logged in and I go check my own userfiles, it should lists all my userfiles. It only lists 291, so my conclusion is that for whatever reason, my profile incorrectly states +11 files only at that page.

**Comment by meshuggahtas** [comment]
Okay, it looks like there is no bug. The old site have been changed in the past months, as in the past I was able to view my own hidden files when I'm logged in, being nogameoverbtoads the first when I try to upload a new userfile.

This issue is more of an enhancement request:
- The one and only place you can view your own hidden are @ https://tasvideos.org/Profile/UserFiles and CTRL+F **(unlisted)** Your own hidden files should be visible at every other page where your hidden userfile is part of something:
- https://tasvideos.org/UserFiles/Game/66 userfiles of a game
- https://tasvideos.org/UserFiles/ForUser/MESHUGGAH my own profile when I'm logged in
