### ISSUE TITLE
List of unknown Wiki Modules

### ISSUE THREAD

**Issue by meshuggahtas** [TASVideos/tasvideos#914]
- https://tasvideos.org/EncoderGuidelines Unknown module **SystemEncodeInfo**
A table listing platforms, minimal width, screenshot size and ratio
- https://tasvideos.org/SiteRules Unknown module **BannedAvatarSites**
Bulletin list of 4 links
- https://tasvideos.org/MovieStatistics File data section with different problems, example: **Could not display statistics for given parameter: alength**

(edits)

Looks like this page is just very old and not used at all (page should be deleted): https://tasvideos.org/EmulatorResources/BugReports **An error occurred attempting to retrieve data from https://code.google.com/feeds/p/bizhawk/issueupdates/basic.**

**Comment by adelikat** [comment]
All these issues have now been adddressed
