### ISSUE TITLE
Bug: award icons for publications year 2019 and 2020 don't exist or are incorrectly returned

### ISSUE THREAD

**Issue by ActuallyTruncated** [TASVideos/tasvideos#916]
On the award subpages for year 2019 and 2020, under the heading Publications, the images for award icons are missing or broken.

https://tasvideos.org/Awards/2019
https://tasvideos.org/Awards/2020

It works on the previous years, for example 2018.
https://tasvideos.org/Awards/2018

The pages themselves just call the award module, for example [module:awards|year=2019], so it's either the module that needs to be fixed, or the files which are missing on the server.

**Comment by meshuggahtas** [comment]
The awards for 2019 and 2020 has a different file naming convention
![awards](https://user-images.githubusercontent.com/31288337/149034263-f8926769-c2ed-4e4a-9019-f8a873c6f3da.PNG)

**Comment by adelikat** [comment]
I propose that we fix the names of the images rather than the code
