### ISSUE TITLE
Feature Request: Default Options for Watching a Topic when Posting

### ISSUE THREAD

**Issue by meshuggahtas** [TASVideos/tasvideos#929]
The way of watching topic has changed, and I'm unsure if this is an issue and/or what is the general consensus on this. I personally would like it to be automatically on for every user, so everyone who participates able to get updates defaultly.

Situation:
- Old site: if you posted in a forum thread, you were "watching the topic" automatically (getting notifications in email with the ability to unsubscribe)
- New site: Opt-in from multiple places

The old site logic lets participants of threads getting update if there's any. 

Some scenarios and their probably preferred topic watching value to be set after posting in a thread:
- General user: watching topic after posting
- Any user in Awards: not watching topic after posting
- Moderator editing someone's post: not watching after editing (Sometimes a moderator might post in the thread for example when the previously moderated post had to be deleted and public address was required. Another thing to decide the nature of the thread, where there might be a new derail is about to happen or just simply an off-topic banter in the off-topic threads)

I'm not sure how UserFile comment notifications works/handled, but similar situations apply there.

**Comment by meshuggahtas** [comment]
Thanks, I rename the issue as feature request of mine

**Comment by Masterjun3** [comment]
Currently, watching a topic is only on by default if you're creating a topic.

An option with 3 values (Always on / Auto / Always off) could be implemented as a user setting like minor edits #891.
Auto would mean the current behavior: On topic creation the checkbox is checked, and on post creation the checkbox reflects the current watch status.

**Comment by adelikat** [comment]
Do we want this as a user setting?

**Comment by vadosnaprimer** [comment]
I do.
