### ISSUE TITLE
MoviePublishingHistory page doesn't show full history

### ISSUE THREAD

**Issue by WarioBarker** [TASVideos/tasvideos#933]
It only goes back 60 days, which is also what the NewMovies page does. It makes sense there, but not on the page that's supposed to be "The complete list of all movie entries added and obsoleted."

It especially sucks for me since I was slowly going up through the new videos and was still in September 2020.

Still, based on the page history, it looks like it'd be a simple and quick fix (removing "|maxdays=60"), so if someone could do that it'd be cool.

**Comment by Randomno** [comment]
#833, dunno why the page was edited from 60 days to 60 days.

**Comment by adelikat** [comment]
I have no intent of this being a full unpaged publication history, way too inefficient on the server

**Comment by meshuggahtas** [comment]
> It especially sucks for me since I was slowly going up through the new videos and was still in September 2020.

For your own plan, as a workaround:
- 1. Login
- 2. Go to https://tasvideos.org/Wiki/Edit?path=MoviePublishingHistory
- 3. Add [module:moviechangelog|maxdays=22222]
- 4. Press Review
- 5. Save the page as HTML
- 6. Leave the page without saving changes to the Wiki

This way you will get a functional single page listing what you wanted without giving unnecessary load to the server.

**Comment by WarioBarker** [comment]
> For your own plan, as a workaround:
> 
> 1. Login

Already done.

> 2. Go to https://tasvideos.org/Wiki/Edit?path=MoviePublishingHistory

"Access denied

You do not have access to this resource."

Even then, I'm on mobile, so I can't save pages as HTML. I *can* save pages via the "Download link" option, but that'd require saving an edit with the 22222 maximum (since for whatever reason the revisions predating the 60-day limit being added use said limit anyway).

**Comment by meshuggahtas** [comment]
Here.

1. https://drive.google.com/file/d/19clLSoLLoUn6PkXYZxRxRfGG9AsP7bok/view?usp=sharing
2. Download it with the blue Download button or top right Download icon
3. Open it with your mobile browser
4. The page I sent you only has the list, but after you click on a movie, it will use the original TASVideos site. Bookmark this page so you can return back anytime to the list

**Comment by WarioBarker** [comment]
Got the above downloaded and it's working. Thanks!

**Comment by TiKevin83** [comment]
Is this now essentially a feature request for a full movie history module with paging to avoid overloading the database?

**Comment by meshuggahtas** [comment]
Yes, so I guess to enhancement Future labels should be added to this issue https://github.com/TASVideos/tasvideos/issues/15 and           close this one which is part of that one.
