### ISSUE TITLE
Make redirect after UserFile delete

### ISSUE THREAD

**Issue by meshuggahtas** [TASVideos/tasvideos#937]
Currently visiting a single UserFile and deleting it will result in a 404. 

1. Visit a given UserFile to be deleted
2. Delete
3. 404 because the UserFile no longer exists

I'm not sure where should it redirect. I assume only logged in user who is the author can delete UserFile, so https://tasvideos.org/Profile/UserFiles could work. Unsure if the staff with the required permission would be satisfied with that redirect. edit: when a moderator would delete a reported UserFile and then returning to their own UserFiles

Doesn't happens when viewing https://tasvideos.org/Profile/UserFiles

**Comment by adelikat** [comment]
This was just a bug, it is intended to return to the page you were on when you clicked the button.  That bug was fixed awhile ago
