### ISSUE TITLE
Move "minor edit" and "edit comments" close to the Save button

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#938]
The editing field is to huge now, and if you're doing a lot of edits, it becomes incredibly annoying to jump back and forth with the mouse, hitting things on the opposite sides of the screen, and in my case I even have to scroll up and down (900p monitor).

**Comment by adelikat** [comment]
Not to invalidate your suggestion but you can click minor edit, type your comments and press enter which will submit the form and save, nullifying the need to go "all the way down to the bottom" to click something
