### ISSUE TITLE
Feature Request: TimeZone 24 hour format

### ISSUE THREAD

**Issue by meshuggahtas** [TASVideos/tasvideos#947]
Currently it's 12 hour format and there is no profile setting called Time Format (or whatever it should be called. maybe a simple checkbox of use 24 hour format?)

Original forum post https://tasvideos.org/Forum/Topics/22808?CurrentPage=4&Highlight=508852#508852

**Comment by Masterjun3** [comment]
This is a locale setting. It's the same thing addressed here #908.

**Comment by meshuggahtas** [comment]
Sorry, searched for timezone in issues not locale. Closing issue.
