### ISSUE TITLE
Add a UI way to view source code of previous revisions.

### ISSUE THREAD

**Issue by Masterjun3** [TASVideos/tasvideos#948]
Currently it's only possible by modifying the URL yourself.
Visiting the rendered version of previous revisions is possible here https://tasvideos.org/Wiki/PageHistory?path=Movies , but there's no button there to view the source code.

Additionally, when viewing a rendered version the "View Source" button should show the source code page of the revision. Currently it always shows the latest source code page.

**Comment by vadosnaprimer** [comment]
Agreed, needed this a bunch of times on the old site.
