### ISSUE TITLE
Make profile card titles clickable and lead to useful pages

### ISSUE THREAD

**Issue by Masterjun3** [TASVideos/tasvideos#952]
Make titles clickable, e.g. clicking your username brings you to the external view of your page (/Users/Profile/[username] instead of /Profile).
- Can also fix the judged and published movie card body showing even without movies. 
- Consider showing player rank somewhere #849.
- Clarify signature.
- "TimeZone".
- "Joined On:" doesn't work with relative times.
- "My profile" vs. "Your account profile".
- oops now it is a list of additional stuff I want to do with the profile page, it's all optional to this issue, just needed a place to store the information.

**Comment by adelikat** [comment]
I'm just going to close this as the first sentence is vague, and if I interpret it correctly I don't even agree with.  Your username in the nav bar should go to your profile, not external profile (so you can go to things like settings)

The laundry list has some things that have been done, and anything else need to be separate tickets
