### ISSUE TITLE
Make button "forum-header-dismiss" white in dark mode

### ISSUE THREAD

**Issue by ThunderAxe31** [TASVideos/tasvideos#956]
Look, I've tried coding it myself, but I couldn't figure out how the dark mode works.

Current vs desired:
![image](https://user-images.githubusercontent.com/36802254/149424783-0148f1d3-3f25-4a3d-ab0a-a3f465cfd7f9.png) ![image](https://user-images.githubusercontent.com/36802254/149425104-655a1f63-e403-4d09-bf1f-6a9763c2e523.png)

**Comment by Masterjun3** [comment]
Yeah I see why this one might be a bit more difficult. That X is an embedded svg, and the svg sets the color to `#000` in its own code.
