### ISSUE TITLE
The generic og:image is small and could be bigger

### ISSUE THREAD

**Issue by Masterjun3** [TASVideos/tasvideos#962]
This can be seen for example in embeds on Discord.
I was told we probably don't want to just use the mega man by itself or we *could* get in legal trouble for using completely unmodified spritework.
So I tried to make a new image we could use instead (currently visible on my homepage https://tasvideos.org/HomePages/Masterjun/NewSiteMagic )

A comparison can be seen here:
![image](https://user-images.githubusercontent.com/22375320/149487878-8684922d-cf90-4255-bd39-1f3c41de3fac.png)

**Comment by meshuggahtas** [comment]
I vote on
- Custom graphics / category (wiki edit, new submission, new publication, new news)
- 1px circular black border for Masterjun's example image. I personally don't like how it blends to the bland grey (dark mode discord theme which I also use) and the shape just simply looks off to me.
- I also wanted to write "Circular shape" for Masterjun's example image, with the reasoning "globe shape looks off", suggeseting circular shape and it would just show more "boring" part of the image is it's just a background of 2-3 colors
