### ISSUE TITLE
Alignment of polls

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#963]
If feels very weird to have **interactive** elements scattered around almost randomly, fully dependent on how long the **description** is.

![изображение](https://user-images.githubusercontent.com/7092625/149496239-4bd2c098-148c-4841-b243-0573bd55f05f.png)

It would be much better if radiobuttons/checkboxes were vertically aligned. An intuitive idea would be to swap button/box with description. But then there are cases when the description is just too long, and putting the checkbox at the end would put it on a third line.

![изображение](https://user-images.githubusercontent.com/7092625/149496180-d8ec3e87-642e-461c-9efc-5bdc9a7a7abf.png)

So maybe interactive elements should be aligned with the percentage bar instead?

PS: Percentage bars feels unnecessarily wide too, ~140px. IMO they don't carry enough information to justify squishing the option description if it's long. I'd make them 100px at max (1% = 1px).

**Comment by Masterjun3** [comment]
Note that the entire textfield is the interactable element.

**Comment by Masterjun3** [comment]
> Percentage bars feels unnecessarily wide too, ~140px. IMO they don't carry enough information to justify squishing the option description if it's long. I'd make them 100px at max (1% = 1px).

The bars aren't squishing anything. The description is always the same percentage of the total width whether you have a full movie title or a single word. With the design like it is now, it's impossible to make them resize based on content. It would make the bars unaligned which makes them useless.

**Comment by vadosnaprimer** [comment]
At certain screen width it does this

![изображение](https://user-images.githubusercontent.com/7092625/149500060-1730d1f9-7616-4ea0-a4a9-b50f1d9a2476.png)

which looks much better than right before that width

![изображение](https://user-images.githubusercontent.com/7092625/149500164-4c78a5f9-2000-473e-8a69-c2b30977dd1d.png)

Since bar size and count size are very limited and predictable, maybe it's possible to put all descriptions above the bar if biggest description gets too long?

**Comment by vadosnaprimer** [comment]
Yeah it's fair to say that we only use to have long option descriptions in Awards polls, and even there it's not always long.

**Comment by YoshiRulz** [comment]
The problematic UI was replaced in https://github.com/TASVideos/tasvideos/commit/94424272982883fa40df78fa74f36c9199e6b413.
