### ISSUE TITLE
RSS Feeds Should Have Content Previews

### ISSUE THREAD

**Issue by blahmoomoo** [TASVideos/tasvideos#967]
I used the combined RSS feed with my RSS reader back when it existed. It included publications, submissions, and news posts in one feed.

Using separate RSS feeds for this content is fine (though it took some time to notice that the combined feed broke). But the new feeds no longer preview the content. For example, a publication would include the screenshot and most or all of the description, and a submission would include the top few thousand characters of the submission post (including YouTube embeds). Now there is no content to preview at all. This makes it harder for an interesting post to catch my eye.

**Comment by meshuggahtas** [comment]
I haven't tested RSS feeds for the sole reason of potentially very low number of readers.

Checking it out with Feeder, it looks like the screenshot is simply broken. Looks like its intended to have a preview but the image has problems.

Conclusions:
- It makes sense to let the user subscribe to their preferred category what we offer: News, Submissions, Publications, Wiki.
https://tasvideos.org/XMLDataFeed
It would make hard to decide what should be combined. Publications and News would be my suggestion, in case there is an audience to cater around
- I guess if those readers who subscribed to a now unmaintained RSS feed, we should post an update about the end of that feed? With an explanation and a link to the list of supported categories
- **Feature request:** There are no preview images attached to RSS posts, should be similar as other external notifications
- **Issue:** There is an "broken" RSS image used https://tasvideos.org/images/tasvideos_rss.png 
Broken as in I can't see in testing with an RSS feed reader called Feeder. I see the little blue mario instead
![feed](https://user-images.githubusercontent.com/31288337/149535192-245d696b-6bd6-4ea9-ad98-03e232e52d11.PNG)

**Comment by Zinfidel** [comment]
I'm one of the increasingly rare individuals that still uses RSS, including the site's feed. I use a feed reader called Feedbro (it's a Chromium browser extension). I noticed the missing images but honestly don't care too much, I just read the headlines anyway. If there are any screenshots or tests I can help with, please give me a mention.
