### ISSUE TITLE
Indented quote > doesn't work

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#973]
Current site does nothing if the line starts with `>`

https://tasvideos.org/TextFormattingRules#Emphasis

![изображение](https://user-images.githubusercontent.com/7092625/149571547-7a3c70a2-eb79-423c-9e0e-d3f79219b9ce.png)

Old site did this

![изображение](https://user-images.githubusercontent.com/7092625/149571641-651857d0-42d3-4102-a32d-407bb984e93a.png)

This feature is much more handy than full-blown quote block that you have to remember how to type
https://tasvideos.org/TextFormattingRules#Quotations

**Comment by nattthebear** [comment]
I swear this worked?  I'll look at it soon.

**Comment by nattthebear** [comment]
Ahh, so this does work!  You get a `<blockquote>`, which at one point we styled reasonably and now we style to look exactly the same as a paragraph.  Unassigning.

**Comment by vadosnaprimer** [comment]
If it looks exactly the same as regular text then existence of the function is pointless, however it was used a lot previously to visually separate text from the rest, and yes it's much easier to use than block quote.

**Comment by nattthebear** [comment]
Oh agreed!  I unassigned myself because I'm not involved much in the styling of this site, but this should be fixed.
