### ISSUE TITLE
Term definition misses BG color

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#974]
https://tasvideos.org/TextFormattingRules#Lists

![изображение](https://user-images.githubusercontent.com/7092625/149572902-81cd861f-9718-412f-8797-669fb848bd78.png)

Old site

![изображение](https://user-images.githubusercontent.com/7092625/149572950-53a2c78c-6a88-4566-b1a1-1437d6ecb586.png)

Also explanation used to be shifted from the term.

**Comment by nattthebear** [comment]
We're making `<dt>`s and `<dd>`s so this is just a styling change.

**Comment by meshuggahtas** [comment]
I also missed the shifting and nice bg color for terms. Personally I'm okay with the current design as well, I've just preferred the visual breaking for important terms to focus on one by one when theere are multiple terms.
