### ISSUE TITLE
YouTube autosync mishandles website links with spaces in them

### ISSUE THREAD

**Issue by despoa** [TASVideos/tasvideos#980]
As shown in the description of [this video](https://www.youtube.com/watch?v=As4ifMCrmBQ), the autosync feature for TASVideos can't seem to handle website links with spaces in them. What should be "https://tasvideos.org/Users/Profile/Walker%20Boh" in the description is instead rendered as "https://tasvideos.org/Users/Profile/Walker Boh".

**Comment by adelikat** [comment]
@nattthebear : I guess https://github.com/TASVideos/tasvideos/issues/918 didn't fix this issue?

**Comment by nattthebear** [comment]
Maybe.  Do we need to force resync existing videos?

**Comment by despoa** [comment]
You may have to. That video was posted four days ago, which was before the commit that supposedly fixed the issue was pushed, but I don't remember if the video synced first or if I added the title and description manually, then it synced.

**Comment by vadosnaprimer** [comment]
I did a minor edit on that pub so YT gets resynced and the link fixed itself.

**Comment by nattthebear** [comment]
@vadosnaprimer Thanks for validating that.  @adelikat Do we have a way to trigger a resync of all?

**Comment by adelikat** [comment]
We do not.  We currently do not even have a reliable way to do it at all.  Seem sabout half the time I get a non-descriptive 400 error from google when a sync is attempted.  Still investigating.  But for the purposes of this ticket, the work is done.  We can manually fix as needed.
