### ISSUE TITLE
Publication history with SGB games or different versions of games not showing

### ISSUE THREAD

**Issue by despoa** [TASVideos/tasvideos#981]
Publications such as [this one](https://tasvideos.org/950M) and [this one](https://tasvideos.org/1700M) should be have visible publication history pages and should be linked together through those pages. However, they're not showing up. There's nothing shown in the publication history pages, not even the game TASed itself.

edit: Adding this also applies to obsoleted publications of romhacks such as [this one](https://tasvideos.org/1063M), where they're made obsolete by movies using romhacks deemed superior.

**Comment by meshuggahtas** [comment]
(Didn't knew how to label it, thought pub system was the closest one)

**Comment by Masterjun3** [comment]
It seems like the publication history page can't deal with cross-game obsoletions. Every game has its own page, and the page is empty if the game has no current publications, that is, if the end of the obsoletion chain is a different game.

**Comment by despoa** [comment]
Added a section regarding obsoleted movies involving romhacks.

**Comment by adelikat** [comment]
I think the GameVersion revamp solved this problem? Or at least allowed us to re-categorized accordingly.  Is there any work left to do here? @Masterjun3 @MemoryTAS  @vadosnaprimer

**Comment by vadosnaprimer** [comment]
Obsoletion histories of those runs look complete to me now. @despoa please confirm.

**Comment by Masterjun3** [comment]
I can confirm this is fixed with the Game Revamp.
There are only a few games left where this happens, but those are tracked on this page https://tasvideos.org/TODO/CrossGameObsoletions and don't need any additional code to be fixed.
