### ISSUE TITLE
Highlight inline (word) difference for wiki edits

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#987]
The old site used to show inline diff only, which was very helpful when checking what was edited and making sure the page can serve as official documentation:

![изображение](https://user-images.githubusercontent.com/7092625/149618145-08d82137-0a92-42d1-9918-b2d4fc432ef9.png)

New site shows it like the entire paragraph was changed, not just a single word:

https://tasvideos.org/Wiki/PageHistory?path=HomePages%2Ffeos

![изображение](https://user-images.githubusercontent.com/7092625/149618178-502412e9-e871-48c5-a380-1adc39cf4b21.png)

So when verifying the new wording it may be extremely difficult to figure out what was actually changed. If the paragraph is huge, it gets even harder. You have to read both old and new paragraphs word by word to find what was changed, and then keep them both in mind in full to determine if the change is good. Bonus points if an edit introduced an important spelling mistake that you couldn't spot.

Both "Inline" and "Side by side" view options have this problem.

**Comment by meshuggahtas** [comment]
Haha, had the same issue but thought I'm an idiot in not understanding the differences

**Comment by nattthebear** [comment]
I tried https://github.com/google/diff-match-patch and it seems to produce better results.

**Comment by nattthebear** [comment]
@vadosnaprimer Would you mind taking a few examples of things you'd like to diff well and try them against https://neil.fraser.name/software/diff_match_patch/demos/diff.html?  If it produces good diff results we an integrate it (but with a better visual presentation)

**Comment by vadosnaprimer** [comment]
I achieved really good results with `Efficiency Cleanup, edit cost 20`. Was testing on https://tasvideos.org/Wiki/PageHistory?path=MovieRules%2FLegacy which has quite some good test cases. `Semantic Cleanup` is still too per-char and makes it hard to figure things out at times. `No Cleanup` is mostly useless.

Since our diffs are mostly tiny, I think we can afford the computation for `Efficiency Cleanup 20`. Going higher approaches our current diff tool.
