### ISSUE TITLE
No forum markup buttons for PMs

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#990]
![изображение](https://user-images.githubusercontent.com/7092625/149635993-4885e8dd-fc7d-4390-8c50-40122dbf2188.png)

I hope it's not by design, because forum PMs would be much harder to use productively if all forum tags had to be entered by hand.

**Comment by adelikat** [comment]
It's not by design

**Comment by Masterjun3** [comment]
This was also fixed by #1123.
